# 5. Ajuste fino de hiperparámetros

`GridSearchCV` con **validación cruzada temporal** sobre el entrenamiento (criterio: MSE),
reentrenamiento del mejor con todo el entrenamiento y evaluación **una sola vez** en la prueba
(capítulo 9.2 del curso). Las mallas están en la celda de configuración: se pueden ampliar o reducir.
En P3, Prophet ajusta `changepoint_prior_scale` en un periodo de validación previo a la prueba y VAR
elige rezagos por AIC; los modelos de ML se reajustan en cada origen con su propia búsqueda.

Tiempo aproximado en una RTX 4050 con las mallas por defecto: P1 ~10 min, P2 ~2 h, P3 ~1 h.

In [1]:
import sys, warnings, json, time
from pathlib import Path
ML = Path.cwd().parent                      # carpeta ml/
sys.path.insert(0, str(ML))
warnings.filterwarnings("ignore")
import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
PROCESSED, REPORTS = ML / "data" / "processed", ML / "reports"
PRED = REPORTS / "predicciones"; PRED.mkdir(parents=True, exist_ok=True)
pd.set_option("display.max_columns", None); pd.set_option("display.width", 200)
sns.set_theme(style="whitegrid", palette="deep")

In [2]:
# ===================== CONFIGURACIÓN =====================
USAR_GPU = True
CORRER = {"p1": False, "p2": True, "p3": True}
P3_HORIZONTES = [1, 3, 6, 12]
PROPHET_CPS = [0.01, 0.05, 0.2, 0.5]     # malla de changepoint_prior_scale
VAR_MAXLAGS = 6

In [3]:
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.dummy import DummyRegressor
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
from mirage.ml import gpu as G
CFG = json.load(open(PROCESSED / "configuracion_particion.json"))
DEV = "cuda" if USAR_GPU else "cpu"
print("Dispositivo de los modelos:", DEV, "| GPU disponible:", G.device_disponible())

def preprocesador(num, cat):
    numerico = Pipeline([("imputar", SimpleImputer(strategy="median")), ("escalar", StandardScaler())])
    categorico = Pipeline([("imputar", SimpleImputer(strategy="most_frequent")),
                           ("codificar", OneHotEncoder(handle_unknown="ignore", min_frequency=20, sparse_output=False))])
    return ColumnTransformer([("num", numerico, num)] + ([("cat", categorico, cat)] if cat else []))

def pipeline(est, num, cat):
    return Pipeline([("prep", preprocesador(num, cat)), ("modelo", est)])

def pliegues_temporales(periodos, n_splits=CFG["N_PLIEGUES_CV"]):
    u = np.sort(pd.Series(periodos).unique())
    return [(np.where(pd.Series(periodos).isin(u[a]))[0], np.where(pd.Series(periodos).isin(u[b]))[0])
            for a, b in TimeSeriesSplit(n_splits=min(n_splits, len(u) - 1)).split(u)]

def metricas(y, p):
    y, p = np.asarray(y, float), np.asarray(p, float); nz = np.abs(y) > 1e-9
    return {"R2": r2_score(y, p), "MAE": mean_absolute_error(y, p), "RMSE": float(np.sqrt(mean_squared_error(y, p))),
            "MAPE_%": 100 * mean_absolute_percentage_error(y[nz], p[nz])}

def cargar(problema):
    """X, Y, periodo, columnas y máscara de entrenamiento de P1 o P2, con la partición guardada."""
    d = pd.read_parquet(PROCESSED / f"dataset_{problema}.parquet")
    d = d.merge(pd.read_parquet(PROCESSED / f"particion_{problema}.parquet"), on="id")
    if problema == "p1":
        Y = d[[c for c in d.columns if c.startswith("y_")]]; periodo = d["mes"]
        X = d.drop(columns=list(Y.columns) + ["split", "id", "mes"])
    else:
        Y = d[["y_de", "y_cob", "y_kd", "y_roa"]]; periodo = d["anio_objetivo"]
        X = d[["ciiu_division", "log_activos", "de", "de_l1", "cob", "kd", "roa", "roa_l1", "margen", "caja_activos",
               "deuda_activos", "crec_deuda", "tasa_impuesto_efectiva", "tasa_politica", "tes_10a_banrep", "ust_10a"]]
    cat = ["ciiu_division"]; num = [c for c in X.columns if c not in cat]
    return X, Y, periodo, num, cat, (d["split"] == "train").to_numpy(), d["id"].to_numpy()

def persistencia(problema, X, Y):
    fuente = {"p1": {c: c.replace("y_", "") + "_l0" for c in Y.columns},
              "p2": {"y_de": "de", "y_cob": "cob", "y_kd": "kd", "y_roa": "roa"}}[problema]
    return pd.DataFrame({c: X[s].to_numpy() for c, s in fuente.items()}).fillna(Y.median())

Dispositivo de los modelos: cuda | GPU disponible: cuda

In [4]:
# ===================== MODELOS Y MALLAS DE BÚSQUEDA =====================
# Los parámetros llevan el prefijo "modelo__" (nombre del paso en el pipeline).
MODELOS = {
    "Ridge":              (G.GPULinear(device=DEV), DEV),
    "Lasso":              (G.GPULasso(device=DEV), DEV),
    "k-NN":               (G.GPUKNN(device=DEV), DEV),
    "Árbol de decisión":  (G.xgb_tree(device=DEV), DEV),
    "Random Forest":      (G.xgb_forest(device=DEV), DEV),
    "Gradient Boosting":  (G.xgb_boost(learning_rate=0.1, device=DEV), DEV),
    "XGBoost":            (G.xgb_boost(device=DEV), DEV),
    "SVR":                (G.GPUSVR(device=DEV), DEV),
    "Red neuronal (MLP)": (G.GPUMLP(device=DEV), DEV),
}
MALLAS = {
    "Ridge":             {"modelo__alpha": [0.01, 0.1, 1, 10, 100]},
    "Lasso":             {"modelo__alpha": [1e-4, 1e-3, 1e-2, 1e-1]},
    "k-NN":              {"modelo__n_neighbors": [5, 15, 30, 60], "modelo__weights": ["uniform", "distance"]},
    "Árbol de decisión": {"modelo__max_depth": [4, 8, 12], "modelo__min_child_weight": [20, 100]},
    "Random Forest":     {"modelo__n_estimators": [100, 300], "modelo__max_depth": [8, 12, 16],
                          "modelo__subsample": [0.6], "modelo__colsample_bynode": [0.6]},
    "Gradient Boosting": {"modelo__n_estimators": [200, 500], "modelo__max_depth": [3, 6], "modelo__learning_rate": [0.03, 0.1]},
    "XGBoost":           {"modelo__n_estimators": [200, 500], "modelo__max_depth": [3, 6], "modelo__learning_rate": [0.03, 0.1],
                          "modelo__subsample": [0.8, 1.0], "modelo__reg_lambda": [1, 10]},
    "SVR":               {"modelo__C": [0.1, 1, 10], "modelo__epsilon": [0.01, 0.1], "modelo__n_components": [2000]},
    "Red neuronal (MLP)": {"modelo__hidden_layer_sizes": [(32,), (64, 32), (128, 64)], "modelo__alpha": [1e-4, 1e-2],
                           "modelo__learning_rate_init": [1e-3, 1e-2]},
}
# P3 tiene 127 meses y reentrena en cada uno de los 36 meses de prueba × 4 horizontes:
# mallas pequeñas para que la búsqueda sea viable (cada combinación se ajusta 36 × 4 × 3 veces).
MALLAS_P3 = {
    "Ridge":         {"modelo__alpha": [0.1, 1, 10, 100]},
    "Random Forest": {"modelo__n_estimators": [100], "modelo__max_depth": [4, 8]},
    "XGBoost":       {"modelo__n_estimators": [200], "modelo__max_depth": [2, 4], "modelo__learning_rate": [0.03, 0.1]},
}
pd.DataFrame({"modelo": list(MALLAS), "combinaciones": [int(np.prod([len(v) for v in m.values()])) for m in MALLAS.values()],
              "dispositivo": [MODELOS[k][1] for k in MALLAS]})

               modelo  combinaciones dispositivo
0               Ridge              5        cuda
1               Lasso              4        cuda
2                k-NN              8        cuda
3   Árbol de decisión              6        cuda
4       Random Forest              6        cuda
5   Gradient Boosting              8        cuda
6             XGBoost             32        cuda
7                 SVR              6        cuda
8  Red neuronal (MLP)             12        cuda

In [5]:
def correr(problema, modelos, etapa, mallas=None):
    X, Y, periodo, num, cat, tr, ids = cargar(problema)
    filas = []
    for nombre, (est, dev) in modelos.items():
        t0 = time.time(); pipe = pipeline(clone(est), num, cat); info = {}
        malla = (mallas or {}).get(nombre)
        if malla:
            gs = GridSearchCV(pipe, malla, cv=pliegues_temporales(periodo[tr].reset_index(drop=True)),
                              scoring="neg_mean_squared_error", n_jobs=1, refit=True)
            gs.fit(X[tr].reset_index(drop=True), Y[tr].reset_index(drop=True)); modelo = gs.best_estimator_
            info = {"mejores_parametros": {k: str(v) for k, v in gs.best_params_.items()}, "mse_cv": -gs.best_score_}
        else:
            modelo = pipe.fit(X[tr], Y[tr])
        seg = time.time() - t0
        P_tr = pd.DataFrame(np.asarray(modelo.predict(X[tr])).reshape(tr.sum(), -1), columns=Y.columns)
        P_te = pd.DataFrame(np.asarray(modelo.predict(X[~tr])).reshape((~tr).sum(), -1), columns=Y.columns)
        P_te.assign(id=ids[~tr]).to_parquet(PRED / f"{problema}_{etapa}_{nombre}.parquet", index=False)
        for c in Y.columns:
            filas.append({"modelo": nombre, "objetivo": c, "dispositivo": dev, "segundos": seg,
                          "R2_entrenamiento": r2_score(Y.loc[tr, c], P_tr[c]), **metricas(Y.loc[~tr, c], P_te[c]),
                          "parametros": json.dumps(info.get("mejores_parametros", {}), ensure_ascii=False)})
        print(f"{problema} · {nombre:20s} [{dev}] {seg:7.1f} s", flush=True)
    pers = persistencia(problema, X[~tr].reset_index(drop=True), Y[tr])
    pers.assign(id=ids[~tr]).to_parquet(PRED / f"{problema}_{etapa}_Persistencia.parquet", index=False)
    for c in Y.columns:
        filas.append({"modelo": "Persistencia", "objetivo": c, "dispositivo": "-", "segundos": 0, "R2_entrenamiento": np.nan,
                      **metricas(Y.loc[~tr, c], pers[c]), "parametros": "{}"})
    Y[~tr].assign(id=ids[~tr]).to_parquet(PRED / f"{problema}_real.parquet", index=False)
    res = pd.DataFrame(filas); res.to_csv(REPORTS / f"{problema}_{etapa}_metricas.csv", index=False)
    return res

def resumen(res):
    # Tolera tablas de corridas anteriores sin todas las columnas
    for c, v in (("dispositivo", "cpu"), ("segundos", np.nan), ("R2_entrenamiento", np.nan)):
        if c not in res: res[c] = v
    if "conjunto" in res:   # formato de la corrida con scripts: separar entrenamiento y prueba
        tr = res[res.conjunto == "entrenamiento"].set_index(["modelo", "objetivo"])["R2"]
        res = res[res.conjunto == "prueba"].copy(); res["R2_entrenamiento"] = res.set_index(["modelo", "objetivo"]).index.map(tr)
    t = res.groupby("modelo").agg(dispositivo=("dispositivo", "first"), segundos=("segundos", "first"), R2_entrenamiento=("R2_entrenamiento", "mean"),
                                  R2=("R2", "mean"), MAE=("MAE", "mean"), RMSE=("RMSE", "mean"))
    t["brecha_%"] = 100 * (t.R2_entrenamiento - t.R2) / t.R2_entrenamiento.abs()
    t["diagnostico"] = np.select([t["brecha_%"] < 10, t["brecha_%"] < 15], ["aceptable", "revisar"], "sobreajuste")
    return t.sort_values("RMSE").round(3)

## 5.1 P1 · Kd por sector y tamaño

In [6]:
if CORRER["p1"]: a1 = correr("p1", MODELOS, "ajuste_fino", MALLAS)
a1 = pd.read_csv(REPORTS / "p1_ajuste_fino_metricas.csv"); resumen(a1)

                   dispositivo  segundos  R2_entrenamiento     R2    MAE   RMSE  brecha_%  diagnostico
modelo
XGBoost                    cpu    91.712             0.901  0.642  1.081  1.465    28.745  sobreajuste
Lasso                      cpu     0.141             0.743  0.557  1.239  1.635    25.068  sobreajuste
Persistencia               cpu     0.000             0.626  0.564  1.115  1.643     9.910    aceptable
Random Forest              cpu    14.419             0.787  0.553  1.216  1.645    29.656  sobreajuste
Gradient Boosting          cpu     4.094             0.878  0.525  1.277  1.700    40.134  sobreajuste
Ridge                      cpu    10.235             0.745  0.463  1.386  1.793    37.845  sobreajuste
Regresión lineal           cpu     0.023             0.780  0.243  1.675  2.123    68.785  sobreajuste
Árbol de decisión          cpu     0.325             0.646  0.235  1.654  2.157    63.676  sobreajuste
k-NN                       cpu     0.615             0.802  0.212  1.585  2.161    73.628  sobreajuste
SVR                        cpu     0.312             0.912  0.217  1.744  2.211    76.245  sobreajuste
Base (media)               cpu     1.167             0.000 -0.616  2.544  3.140       inf  sobreajuste
Red neuronal (MLP)         cpu     4.146             0.721 -0.673  2.326  3.142   193.255  sobreajuste

## 5.2 P2 · Estructura de capital por empresa

In [7]:
if CORRER["p2"]: a2 = correr("p2", MODELOS, "ajuste_fino", MALLAS)
a2 = pd.read_csv(REPORTS / "p2_ajuste_fino_metricas.csv"); resumen(a2)

p2 · Ridge                [cuda]     7.0 s

p2 · Lasso                [cuda]    60.8 s

p2 · k-NN                 [cuda]    11.3 s

p2 · Árbol de decisión    [cuda]     8.6 s

p2 · Random Forest        [cuda]  3788.2 s

p2 · Gradient Boosting    [cuda]   148.9 s

p2 · XGBoost              [cuda]   436.2 s

p2 · SVR                  [cuda]   337.2 s

p2 · Red neuronal (MLP)   [cuda]   465.3 s

                   dispositivo  segundos  R2_entrenamiento     R2    MAE   RMSE  brecha_%  diagnostico
modelo
Random Forest             cuda  3788.158             0.501  0.429  0.313  0.489    14.266      revisar
XGBoost                   cuda   436.198             0.440  0.427  0.314  0.489     2.765    aceptable
Gradient Boosting         cuda   148.893             0.441  0.427  0.314  0.490     3.148    aceptable
Árbol de decisión         cuda     8.565             0.400  0.408  0.321  0.499    -1.852    aceptable
Red neuronal (MLP)        cuda   465.297             0.403  0.398  0.326  0.503     1.339    aceptable
k-NN                      cuda    11.293             1.000  0.377  0.336  0.511    62.281  sobreajuste
Ridge                     cuda     7.046             0.399  0.359  0.337  0.512     9.946    aceptable
SVR                       cuda   337.234             0.374  0.359  0.323  0.516     4.121    aceptable
Lasso                     cuda    60.840             0.218  0.222  0.345  0.519    -1.540    aceptable
Persistencia                 -     0.000               NaN  0.261  0.310  0.550       NaN  sobreajuste

## 5.3 P3 · Insumos de mercado

In [8]:
P3 = pd.read_parquet(PROCESSED / "dataset_p3.parquet")
OBJ3 = ["spread_soberano", "tes_cop_10a", "tes_uvr_10a", "inflacion_implicita_10a", "tasa_politica", "ust_10a"]

In [9]:
# ---------- Modelos de series de tiempo (CPU: no tienen versión en GPU) ----------
import logging; logging.getLogger("cmdstanpy").setLevel(logging.ERROR); logging.getLogger("prophet").setLevel(logging.ERROR)
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.api import VAR
from prophet import Prophet

def paseo_aleatorio(train, h, **kw): return train.iloc[-1]

def arima(train, h, ordenes=((1, 1, 0), (0, 1, 1), (1, 1, 1), (2, 1, 0)), **kw):
    out = {}
    for c in train.columns:
        mejor, aic = None, np.inf
        for o in ordenes:
            try:
                r = ARIMA(train[c].values, order=o).fit()
                if r.aic < aic: mejor, aic = r, r.aic
            except Exception: pass
        out[c] = mejor.forecast(h)[-1] if mejor is not None else train[c].iloc[-1]
    return pd.Series(out)

def var(train, h, maxlags=2, **kw):
    d = train.diff().dropna()
    try:
        r = VAR(d).fit(maxlags=maxlags, ic="aic"); k = max(r.k_ar, 1)
        return train.iloc[-1] + r.forecast(d.values[-k:], steps=h).sum(axis=0)
    except Exception:
        return train.iloc[-1]

def prophet(train, h, cps=0.05, **kw):
    out = {}
    for c in train.columns:
        m = Prophet(changepoint_prior_scale=cps, yearly_seasonality=True, weekly_seasonality=False,
                    daily_seasonality=False, uncertainty_samples=0).fit(pd.DataFrame({"ds": train.index, "y": train[c].values}))
        out[c] = float(m.predict(pd.DataFrame({"ds": [train.index[-1] + pd.offsets.MonthEnd(h)]}))["yhat"].iloc[0])
    return pd.Series(out)

def origen_movil(S, modelo, h, meses_prueba, minimo=48, **kw):
    """En cada mes t del periodo de prueba se reentrena con la historia hasta t y se pronostica t+h."""
    idx, filas = S.index, {}
    for t in idx[-(meses_prueba + h):-h]:
        tr = S.loc[:t]
        if len(tr) >= minimo: filas[idx[idx.get_loc(t) + h]] = modelo(tr, h, **kw)
    return pd.DataFrame(filas).T.sort_index()

def supervisado_p3(P3, h, rezagos=3):
    """Estrategia directa: con la información hasta t, predecir el vector de objetivos en t+h."""
    f = {}
    for c in OBJ3 + ["ibr_3m", "bei_usd_10a"]:
        for k in range(rezagos): f[f"{c}_l{k}"] = P3[c].shift(k)
        f[f"{c}_d1"] = P3[c].diff()
    f["colcap_ret"] = P3["colcap"].pct_change(fill_method=None); f["trm_ret"] = P3["trm"].pct_change(fill_method=None)
    X = pd.DataFrame(f, index=P3.index); Y = P3[OBJ3].shift(-h); ok = X.notna().all(1) & Y.notna().all(1)
    return X[ok], Y[ok]

def ml_origen_movil(P3, h, estimador, malla=None, meses_prueba=36):
    """Modelos de ML con rezagos, reentrenados en cada origen (y con GridSearchCV si se pasa malla)."""
    X, Y = supervisado_p3(P3, h); S = P3[OBJ3]; preds = {}
    for t in Y.index[-meses_prueba:]:
        pos = Y.index.get_loc(t); tr = Y.index[:max(pos - h + 1, 0)]   # solo filas cuyo objetivo ya se conoce en t
        if len(tr) < 36: continue
        pipe = pipeline(clone(estimador), list(X.columns), [])
        if malla: pipe = GridSearchCV(pipe, malla, cv=TimeSeriesSplit(n_splits=3), scoring="neg_mean_squared_error")
        pipe.fit(X.loc[tr], Y.loc[tr]); j = S.index.get_loc(t) + h
        if j < len(S): preds[S.index[j]] = pd.Series(np.ravel(pipe.predict(X.loc[[t]]))[:len(OBJ3)], index=OBJ3)
    return pd.DataFrame(preds).T.sort_index()

Importing plotly failed. Interactive plots will not work.

In [10]:
def correr_p3_ajuste():
    S, filas = P3[OBJ3], []
    val = S.iloc[:-CFG["P3_MESES_PRUEBA"]]          # validación: antes del periodo de prueba
    for h in P3_HORIZONTES:
        err = {c: ((origen_movil(val, prophet, h, 12, cps=c) - val) ** 2).mean().mean() for c in PROPHET_CPS}
        cps = min(err, key=err.get); print(f"h={h}: Prophet cps elegido {cps}")
        series = {"Paseo aleatorio": (paseo_aleatorio, {}), "ARIMA": (arima, {}), "VAR": (var, {"maxlags": VAR_MAXLAGS}),
                  "Prophet": (prophet, {"cps": cps})}
        for nombre, (fn, kw) in series.items():
            t0 = time.time(); f = origen_movil(S, fn, h, CFG["P3_MESES_PRUEBA"], **kw); seg = time.time() - t0
            f.to_parquet(PRED / f"p3_ajuste_fino_h{h}_{nombre}.parquet")
            for c in OBJ3: filas.append({"modelo": nombre, "h": h, "objetivo": c, "dispositivo": "cpu", "segundos": seg, "parametros": json.dumps(kw), **metricas(S.loc[f.index, c], f[c])})
            print(f"h={h:2d} {nombre:16s} [cpu] {seg:6.1f} s", flush=True)
        for nombre in ("Ridge", "Random Forest", "XGBoost"):
            est, dev = MODELOS[nombre]
            t0 = time.time(); f = ml_origen_movil(P3, h, est, MALLAS_P3[nombre], CFG["P3_MESES_PRUEBA"]); seg = time.time() - t0
            f.to_parquet(PRED / f"p3_ajuste_fino_h{h}_{nombre}.parquet")
            for c in OBJ3: filas.append({"modelo": nombre, "h": h, "objetivo": c, "dispositivo": dev, "segundos": seg, "parametros": "", **metricas(S.loc[f.index, c], f[c])})
            print(f"h={h:2d} {nombre:16s} [{dev}] {seg:6.1f} s", flush=True)
    res = pd.DataFrame(filas); res.to_csv(REPORTS / "p3_ajuste_fino_metricas.csv", index=False); return res
if CORRER["p3"]: a3 = correr_p3_ajuste()
a3 = pd.read_csv(REPORTS / "p3_ajuste_fino_metricas.csv"); a3.pivot_table(index="modelo", columns="h", values="RMSE").round(3).sort_values(1)

01:32:29 - cmdstanpy - INFO - Chain [1] start processing

01:32:31 - cmdstanpy - INFO - Chain [1] done processing

01:32:31 - cmdstanpy - INFO - Chain [1] start processing

01:32:32 - cmdstanpy - INFO - Chain [1] done processing

01:32:32 - cmdstanpy - INFO - Chain [1] start processing

01:32:33 - cmdstanpy - INFO - Chain [1] done processing

01:32:33 - cmdstanpy - INFO - Chain [1] start processing

01:32:34 - cmdstanpy - INFO - Chain [1] done processing

01:32:35 - cmdstanpy - INFO - Chain [1] start processing

01:32:35 - cmdstanpy - INFO - Chain [1] done processing

01:32:36 - cmdstanpy - INFO - Chain [1] start processing

01:32:36 - cmdstanpy - INFO - Chain [1] done processing

01:32:37 - cmdstanpy - INFO - Chain [1] start processing

01:32:37 - cmdstanpy - INFO - Chain [1] done processing

01:32:38 - cmdstanpy - INFO - Chain [1] start processing

01:32:39 - cmdstanpy - INFO - Chain [1] done processing

01:32:39 - cmdstanpy - INFO - Chain [1] start processing

01:32:40 - cmdstanpy - INFO - Chain [1] done processing

01:32:40 - cmdstanpy - INFO - Chain [1] start processing

01:32:41 - cmdstanpy - INFO - Chain [1] done processing

01:32:42 - cmdstanpy - INFO - Chain [1] start processing

01:32:42 - cmdstanpy - INFO - Chain [1] done processing

01:32:43 - cmdstanpy - INFO - Chain [1] start processing

01:32:43 - cmdstanpy - INFO - Chain [1] done processing

01:32:44 - cmdstanpy - INFO - Chain [1] start processing

01:32:44 - cmdstanpy - INFO - Chain [1] done processing

01:32:45 - cmdstanpy - INFO - Chain [1] start processing

01:32:45 - cmdstanpy - INFO - Chain [1] done processing

01:32:46 - cmdstanpy - INFO - Chain [1] start processing

01:32:47 - cmdstanpy - INFO - Chain [1] done processing

01:32:47 - cmdstanpy - INFO - Chain [1] start processing

01:32:48 - cmdstanpy - INFO - Chain [1] done processing

01:32:48 - cmdstanpy - INFO - Chain [1] start processing

01:32:49 - cmdstanpy - INFO - Chain [1] done processing

01:32:49 - cmdstanpy - INFO - Chain [1] start processing

01:32:50 - cmdstanpy - INFO - Chain [1] done processing

01:32:50 - cmdstanpy - INFO - Chain [1] start processing

01:32:51 - cmdstanpy - INFO - Chain [1] done processing

01:32:51 - cmdstanpy - INFO - Chain [1] start processing

01:32:53 - cmdstanpy - INFO - Chain [1] done processing

01:32:53 - cmdstanpy - INFO - Chain [1] start processing

01:32:54 - cmdstanpy - INFO - Chain [1] done processing

01:32:54 - cmdstanpy - INFO - Chain [1] start processing

01:32:55 - cmdstanpy - INFO - Chain [1] done processing

01:32:55 - cmdstanpy - INFO - Chain [1] start processing

01:32:56 - cmdstanpy - INFO - Chain [1] done processing

01:32:56 - cmdstanpy - INFO - Chain [1] start processing

01:32:57 - cmdstanpy - INFO - Chain [1] done processing

01:32:57 - cmdstanpy - INFO - Chain [1] start processing

01:32:58 - cmdstanpy - INFO - Chain [1] done processing

01:32:58 - cmdstanpy - INFO - Chain [1] start processing

01:32:59 - cmdstanpy - INFO - Chain [1] done processing

01:33:00 - cmdstanpy - INFO - Chain [1] start processing

01:33:01 - cmdstanpy - INFO - Chain [1] done processing

01:33:01 - cmdstanpy - INFO - Chain [1] start processing

01:33:02 - cmdstanpy - INFO - Chain [1] done processing

01:33:02 - cmdstanpy - INFO - Chain [1] start processing

01:33:03 - cmdstanpy - INFO - Chain [1] done processing

01:33:03 - cmdstanpy - INFO - Chain [1] start processing

01:33:04 - cmdstanpy - INFO - Chain [1] done processing

01:33:05 - cmdstanpy - INFO - Chain [1] start processing

01:33:05 - cmdstanpy - INFO - Chain [1] done processing

01:33:06 - cmdstanpy - INFO - Chain [1] start processing

01:33:07 - cmdstanpy - INFO - Chain [1] done processing

01:33:07 - cmdstanpy - INFO - Chain [1] start processing

01:33:08 - cmdstanpy - INFO - Chain [1] done processing

01:33:08 - cmdstanpy - INFO - Chain [1] start processing

01:33:09 - cmdstanpy - INFO - Chain [1] done processing

01:33:10 - cmdstanpy - INFO - Chain [1] start processing

01:33:10 - cmdstanpy - INFO - Chain [1] done processing

01:33:11 - cmdstanpy - INFO - Chain [1] start processing

01:33:11 - cmdstanpy - INFO - Chain [1] done processing

01:33:12 - cmdstanpy - INFO - Chain [1] start processing

01:33:13 - cmdstanpy - INFO - Chain [1] done processing

01:33:13 - cmdstanpy - INFO - Chain [1] start processing

01:33:14 - cmdstanpy - INFO - Chain [1] done processing

01:33:14 - cmdstanpy - INFO - Chain [1] start processing

01:33:15 - cmdstanpy - INFO - Chain [1] done processing

01:33:15 - cmdstanpy - INFO - Chain [1] start processing

01:33:16 - cmdstanpy - INFO - Chain [1] done processing

01:33:16 - cmdstanpy - INFO - Chain [1] start processing

01:33:17 - cmdstanpy - INFO - Chain [1] done processing

01:33:18 - cmdstanpy - INFO - Chain [1] start processing

01:33:18 - cmdstanpy - INFO - Chain [1] done processing

01:33:18 - cmdstanpy - INFO - Chain [1] start processing

01:33:19 - cmdstanpy - INFO - Chain [1] done processing

01:33:20 - cmdstanpy - INFO - Chain [1] start processing

01:33:20 - cmdstanpy - INFO - Chain [1] done processing

01:33:21 - cmdstanpy - INFO - Chain [1] start processing

01:33:22 - cmdstanpy - INFO - Chain [1] done processing

01:33:22 - cmdstanpy - INFO - Chain [1] start processing

01:33:23 - cmdstanpy - INFO - Chain [1] done processing

01:33:23 - cmdstanpy - INFO - Chain [1] start processing

01:33:24 - cmdstanpy - INFO - Chain [1] done processing

01:33:24 - cmdstanpy - INFO - Chain [1] start processing

01:33:25 - cmdstanpy - INFO - Chain [1] done processing

01:33:26 - cmdstanpy - INFO - Chain [1] start processing

01:33:26 - cmdstanpy - INFO - Chain [1] done processing

01:33:27 - cmdstanpy - INFO - Chain [1] start processing

01:33:28 - cmdstanpy - INFO - Chain [1] done processing

01:33:28 - cmdstanpy - INFO - Chain [1] start processing

01:33:29 - cmdstanpy - INFO - Chain [1] done processing

01:33:29 - cmdstanpy - INFO - Chain [1] start processing

01:33:30 - cmdstanpy - INFO - Chain [1] done processing

01:33:31 - cmdstanpy - INFO - Chain [1] start processing

01:33:31 - cmdstanpy - INFO - Chain [1] done processing

01:33:32 - cmdstanpy - INFO - Chain [1] start processing

01:33:33 - cmdstanpy - INFO - Chain [1] done processing

01:33:33 - cmdstanpy - INFO - Chain [1] start processing

01:33:34 - cmdstanpy - INFO - Chain [1] done processing

01:33:34 - cmdstanpy - INFO - Chain [1] start processing

01:33:35 - cmdstanpy - INFO - Chain [1] done processing

01:33:35 - cmdstanpy - INFO - Chain [1] start processing

01:33:36 - cmdstanpy - INFO - Chain [1] done processing

01:33:36 - cmdstanpy - INFO - Chain [1] start processing

01:33:37 - cmdstanpy - INFO - Chain [1] done processing

01:33:38 - cmdstanpy - INFO - Chain [1] start processing

01:33:38 - cmdstanpy - INFO - Chain [1] done processing

01:33:39 - cmdstanpy - INFO - Chain [1] start processing

01:33:39 - cmdstanpy - INFO - Chain [1] done processing

01:33:40 - cmdstanpy - INFO - Chain [1] start processing

01:33:40 - cmdstanpy - INFO - Chain [1] done processing

01:33:41 - cmdstanpy - INFO - Chain [1] start processing

01:33:42 - cmdstanpy - INFO - Chain [1] done processing

01:33:42 - cmdstanpy - INFO - Chain [1] start processing

01:33:43 - cmdstanpy - INFO - Chain [1] done processing

01:33:43 - cmdstanpy - INFO - Chain [1] start processing

01:33:44 - cmdstanpy - INFO - Chain [1] done processing

01:33:45 - cmdstanpy - INFO - Chain [1] start processing

01:33:46 - cmdstanpy - INFO - Chain [1] done processing

01:33:46 - cmdstanpy - INFO - Chain [1] start processing

01:33:46 - cmdstanpy - INFO - Chain [1] done processing

01:33:47 - cmdstanpy - INFO - Chain [1] start processing

01:33:48 - cmdstanpy - INFO - Chain [1] done processing

01:33:48 - cmdstanpy - INFO - Chain [1] start processing

01:33:49 - cmdstanpy - INFO - Chain [1] done processing

01:33:50 - cmdstanpy - INFO - Chain [1] start processing

01:33:50 - cmdstanpy - INFO - Chain [1] done processing

01:33:51 - cmdstanpy - INFO - Chain [1] start processing

01:33:51 - cmdstanpy - INFO - Chain [1] done processing

01:33:52 - cmdstanpy - INFO - Chain [1] start processing

01:33:52 - cmdstanpy - INFO - Chain [1] done processing

01:33:53 - cmdstanpy - INFO - Chain [1] start processing

01:33:54 - cmdstanpy - INFO - Chain [1] done processing

01:33:54 - cmdstanpy - INFO - Chain [1] start processing

01:33:55 - cmdstanpy - INFO - Chain [1] done processing

01:33:56 - cmdstanpy - INFO - Chain [1] start processing

01:33:57 - cmdstanpy - INFO - Chain [1] done processing

01:33:58 - cmdstanpy - INFO - Chain [1] start processing

01:33:59 - cmdstanpy - INFO - Chain [1] done processing

01:33:59 - cmdstanpy - INFO - Chain [1] start processing

01:34:01 - cmdstanpy - INFO - Chain [1] done processing

01:34:01 - cmdstanpy - INFO - Chain [1] start processing

01:34:02 - cmdstanpy - INFO - Chain [1] done processing

01:34:02 - cmdstanpy - INFO - Chain [1] start processing

01:34:03 - cmdstanpy - INFO - Chain [1] done processing

01:34:03 - cmdstanpy - INFO - Chain [1] start processing

01:34:05 - cmdstanpy - INFO - Chain [1] done processing

01:34:05 - cmdstanpy - INFO - Chain [1] start processing

01:34:07 - cmdstanpy - INFO - Chain [1] done processing

01:34:07 - cmdstanpy - INFO - Chain [1] start processing

01:34:08 - cmdstanpy - INFO - Chain [1] done processing

01:34:09 - cmdstanpy - INFO - Chain [1] start processing

01:34:10 - cmdstanpy - INFO - Chain [1] done processing

01:34:10 - cmdstanpy - INFO - Chain [1] start processing

01:34:11 - cmdstanpy - INFO - Chain [1] done processing

01:34:11 - cmdstanpy - INFO - Chain [1] start processing

01:34:12 - cmdstanpy - INFO - Chain [1] done processing

01:34:12 - cmdstanpy - INFO - Chain [1] start processing

01:34:14 - cmdstanpy - INFO - Chain [1] done processing

01:34:14 - cmdstanpy - INFO - Chain [1] start processing

01:34:16 - cmdstanpy - INFO - Chain [1] done processing

01:34:17 - cmdstanpy - INFO - Chain [1] start processing

01:34:18 - cmdstanpy - INFO - Chain [1] done processing

01:34:18 - cmdstanpy - INFO - Chain [1] start processing

01:34:20 - cmdstanpy - INFO - Chain [1] done processing

01:34:20 - cmdstanpy - INFO - Chain [1] start processing

01:34:21 - cmdstanpy - INFO - Chain [1] done processing

01:34:21 - cmdstanpy - INFO - Chain [1] start processing

01:34:22 - cmdstanpy - INFO - Chain [1] done processing

01:34:23 - cmdstanpy - INFO - Chain [1] start processing

01:34:24 - cmdstanpy - INFO - Chain [1] done processing

01:34:24 - cmdstanpy - INFO - Chain [1] start processing

01:34:26 - cmdstanpy - INFO - Chain [1] done processing

01:34:27 - cmdstanpy - INFO - Chain [1] start processing

01:34:28 - cmdstanpy - INFO - Chain [1] done processing

01:34:28 - cmdstanpy - INFO - Chain [1] start processing

01:34:30 - cmdstanpy - INFO - Chain [1] done processing

01:34:30 - cmdstanpy - INFO - Chain [1] start processing

01:34:31 - cmdstanpy - INFO - Chain [1] done processing

01:34:31 - cmdstanpy - INFO - Chain [1] start processing

01:34:33 - cmdstanpy - INFO - Chain [1] done processing

01:34:33 - cmdstanpy - INFO - Chain [1] start processing

01:34:34 - cmdstanpy - INFO - Chain [1] done processing

01:34:34 - cmdstanpy - INFO - Chain [1] start processing

01:34:36 - cmdstanpy - INFO - Chain [1] done processing

01:34:37 - cmdstanpy - INFO - Chain [1] start processing

01:34:38 - cmdstanpy - INFO - Chain [1] done processing

01:34:38 - cmdstanpy - INFO - Chain [1] start processing

01:34:39 - cmdstanpy - INFO - Chain [1] done processing

01:34:40 - cmdstanpy - INFO - Chain [1] start processing

01:34:40 - cmdstanpy - INFO - Chain [1] done processing

01:34:41 - cmdstanpy - INFO - Chain [1] start processing

01:34:42 - cmdstanpy - INFO - Chain [1] done processing

01:34:43 - cmdstanpy - INFO - Chain [1] start processing

01:34:43 - cmdstanpy - INFO - Chain [1] done processing

01:34:44 - cmdstanpy - INFO - Chain [1] start processing

01:34:45 - cmdstanpy - INFO - Chain [1] done processing

01:34:45 - cmdstanpy - INFO - Chain [1] start processing

01:34:46 - cmdstanpy - INFO - Chain [1] done processing

01:34:47 - cmdstanpy - INFO - Chain [1] start processing

01:34:48 - cmdstanpy - INFO - Chain [1] done processing

01:34:49 - cmdstanpy - INFO - Chain [1] start processing

01:34:49 - cmdstanpy - INFO - Chain [1] done processing

01:34:50 - cmdstanpy - INFO - Chain [1] start processing

01:34:50 - cmdstanpy - INFO - Chain [1] done processing

01:34:51 - cmdstanpy - INFO - Chain [1] start processing

01:34:52 - cmdstanpy - INFO - Chain [1] done processing

01:34:53 - cmdstanpy - INFO - Chain [1] start processing

01:34:54 - cmdstanpy - INFO - Chain [1] done processing

01:34:55 - cmdstanpy - INFO - Chain [1] start processing

01:34:56 - cmdstanpy - INFO - Chain [1] done processing

01:34:57 - cmdstanpy - INFO - Chain [1] start processing

01:34:58 - cmdstanpy - INFO - Chain [1] done processing

01:34:58 - cmdstanpy - INFO - Chain [1] start processing

01:34:59 - cmdstanpy - INFO - Chain [1] done processing

01:35:00 - cmdstanpy - INFO - Chain [1] start processing

01:35:01 - cmdstanpy - INFO - Chain [1] done processing

01:35:01 - cmdstanpy - INFO - Chain [1] start processing

01:35:03 - cmdstanpy - INFO - Chain [1] done processing

01:35:03 - cmdstanpy - INFO - Chain [1] start processing

01:35:05 - cmdstanpy - INFO - Chain [1] done processing

01:35:05 - cmdstanpy - INFO - Chain [1] start processing

01:35:06 - cmdstanpy - INFO - Chain [1] done processing

01:35:06 - cmdstanpy - INFO - Chain [1] start processing

01:35:08 - cmdstanpy - INFO - Chain [1] done processing

01:35:09 - cmdstanpy - INFO - Chain [1] start processing

01:35:09 - cmdstanpy - INFO - Chain [1] done processing

01:35:10 - cmdstanpy - INFO - Chain [1] start processing

01:35:11 - cmdstanpy - INFO - Chain [1] done processing

01:35:11 - cmdstanpy - INFO - Chain [1] start processing

01:35:13 - cmdstanpy - INFO - Chain [1] done processing

01:35:14 - cmdstanpy - INFO - Chain [1] start processing

01:35:15 - cmdstanpy - INFO - Chain [1] done processing

01:35:15 - cmdstanpy - INFO - Chain [1] start processing

01:35:17 - cmdstanpy - INFO - Chain [1] done processing

01:35:17 - cmdstanpy - INFO - Chain [1] start processing

01:35:19 - cmdstanpy - INFO - Chain [1] done processing

01:35:19 - cmdstanpy - INFO - Chain [1] start processing

01:35:19 - cmdstanpy - INFO - Chain [1] done processing

01:35:20 - cmdstanpy - INFO - Chain [1] start processing

01:35:21 - cmdstanpy - INFO - Chain [1] done processing

01:35:21 - cmdstanpy - INFO - Chain [1] start processing

01:35:22 - cmdstanpy - INFO - Chain [1] done processing

01:35:23 - cmdstanpy - INFO - Chain [1] start processing

01:35:24 - cmdstanpy - INFO - Chain [1] done processing

01:35:25 - cmdstanpy - INFO - Chain [1] start processing

01:35:26 - cmdstanpy - INFO - Chain [1] done processing

01:35:26 - cmdstanpy - INFO - Chain [1] start processing

01:35:28 - cmdstanpy - INFO - Chain [1] done processing

01:35:28 - cmdstanpy - INFO - Chain [1] start processing

01:35:30 - cmdstanpy - INFO - Chain [1] done processing

01:35:30 - cmdstanpy - INFO - Chain [1] start processing

01:35:31 - cmdstanpy - INFO - Chain [1] done processing

01:35:31 - cmdstanpy - INFO - Chain [1] start processing

01:35:32 - cmdstanpy - INFO - Chain [1] done processing

01:35:33 - cmdstanpy - INFO - Chain [1] start processing

01:35:35 - cmdstanpy - INFO - Chain [1] done processing

01:35:35 - cmdstanpy - INFO - Chain [1] start processing

01:35:36 - cmdstanpy - INFO - Chain [1] done processing

01:35:37 - cmdstanpy - INFO - Chain [1] start processing

01:35:39 - cmdstanpy - INFO - Chain [1] done processing

01:35:39 - cmdstanpy - INFO - Chain [1] start processing

01:35:40 - cmdstanpy - INFO - Chain [1] done processing

01:35:40 - cmdstanpy - INFO - Chain [1] start processing

01:35:41 - cmdstanpy - INFO - Chain [1] done processing

01:35:42 - cmdstanpy - INFO - Chain [1] start processing

01:35:43 - cmdstanpy - INFO - Chain [1] done processing

01:35:43 - cmdstanpy - INFO - Chain [1] start processing

01:35:45 - cmdstanpy - INFO - Chain [1] done processing

01:35:45 - cmdstanpy - INFO - Chain [1] start processing

01:35:46 - cmdstanpy - INFO - Chain [1] done processing

01:35:47 - cmdstanpy - INFO - Chain [1] start processing

01:35:48 - cmdstanpy - INFO - Chain [1] done processing

01:35:49 - cmdstanpy - INFO - Chain [1] start processing

01:35:50 - cmdstanpy - INFO - Chain [1] done processing

01:35:50 - cmdstanpy - INFO - Chain [1] start processing

01:35:52 - cmdstanpy - INFO - Chain [1] done processing

01:35:52 - cmdstanpy - INFO - Chain [1] start processing

01:35:54 - cmdstanpy - INFO - Chain [1] done processing

01:35:54 - cmdstanpy - INFO - Chain [1] start processing

01:35:56 - cmdstanpy - INFO - Chain [1] done processing

01:35:57 - cmdstanpy - INFO - Chain [1] start processing

01:35:59 - cmdstanpy - INFO - Chain [1] done processing

01:35:59 - cmdstanpy - INFO - Chain [1] start processing

01:36:01 - cmdstanpy - INFO - Chain [1] done processing

01:36:01 - cmdstanpy - INFO - Chain [1] start processing

01:36:03 - cmdstanpy - INFO - Chain [1] done processing

01:36:03 - cmdstanpy - INFO - Chain [1] start processing

01:36:05 - cmdstanpy - INFO - Chain [1] done processing

01:36:05 - cmdstanpy - INFO - Chain [1] start processing

01:36:06 - cmdstanpy - INFO - Chain [1] done processing

01:36:07 - cmdstanpy - INFO - Chain [1] start processing

01:36:09 - cmdstanpy - INFO - Chain [1] done processing

01:36:09 - cmdstanpy - INFO - Chain [1] start processing

01:36:11 - cmdstanpy - INFO - Chain [1] done processing

01:36:12 - cmdstanpy - INFO - Chain [1] start processing

01:36:14 - cmdstanpy - INFO - Chain [1] done processing

01:36:14 - cmdstanpy - INFO - Chain [1] start processing

01:36:16 - cmdstanpy - INFO - Chain [1] done processing

01:36:17 - cmdstanpy - INFO - Chain [1] start processing

01:36:19 - cmdstanpy - INFO - Chain [1] done processing

01:36:19 - cmdstanpy - INFO - Chain [1] start processing

01:36:20 - cmdstanpy - INFO - Chain [1] done processing

01:36:21 - cmdstanpy - INFO - Chain [1] start processing

01:36:23 - cmdstanpy - INFO - Chain [1] done processing

01:36:23 - cmdstanpy - INFO - Chain [1] start processing

01:36:26 - cmdstanpy - INFO - Chain [1] done processing

01:36:26 - cmdstanpy - INFO - Chain [1] start processing

01:36:28 - cmdstanpy - INFO - Chain [1] done processing

01:36:28 - cmdstanpy - INFO - Chain [1] start processing

01:36:30 - cmdstanpy - INFO - Chain [1] done processing

01:36:31 - cmdstanpy - INFO - Chain [1] start processing

01:36:32 - cmdstanpy - INFO - Chain [1] done processing

01:36:32 - cmdstanpy - INFO - Chain [1] start processing

01:36:34 - cmdstanpy - INFO - Chain [1] done processing

01:36:34 - cmdstanpy - INFO - Chain [1] start processing

01:36:37 - cmdstanpy - INFO - Chain [1] done processing

01:36:38 - cmdstanpy - INFO - Chain [1] start processing

01:36:40 - cmdstanpy - INFO - Chain [1] done processing

01:36:40 - cmdstanpy - INFO - Chain [1] start processing

01:36:42 - cmdstanpy - INFO - Chain [1] done processing

01:36:42 - cmdstanpy - INFO - Chain [1] start processing

01:36:44 - cmdstanpy - INFO - Chain [1] done processing

01:36:45 - cmdstanpy - INFO - Chain [1] start processing

01:36:46 - cmdstanpy - INFO - Chain [1] done processing

01:36:47 - cmdstanpy - INFO - Chain [1] start processing

01:36:49 - cmdstanpy - INFO - Chain [1] done processing

01:36:49 - cmdstanpy - INFO - Chain [1] start processing

01:36:51 - cmdstanpy - INFO - Chain [1] done processing

01:36:51 - cmdstanpy - INFO - Chain [1] start processing

01:36:53 - cmdstanpy - INFO - Chain [1] done processing

01:36:53 - cmdstanpy - INFO - Chain [1] start processing

01:36:55 - cmdstanpy - INFO - Chain [1] done processing

01:36:56 - cmdstanpy - INFO - Chain [1] start processing

01:36:58 - cmdstanpy - INFO - Chain [1] done processing

01:36:59 - cmdstanpy - INFO - Chain [1] start processing

01:37:01 - cmdstanpy - INFO - Chain [1] done processing

01:37:01 - cmdstanpy - INFO - Chain [1] start processing

01:37:02 - cmdstanpy - INFO - Chain [1] done processing

01:37:03 - cmdstanpy - INFO - Chain [1] start processing

01:37:05 - cmdstanpy - INFO - Chain [1] done processing

01:37:06 - cmdstanpy - INFO - Chain [1] start processing

01:37:08 - cmdstanpy - INFO - Chain [1] done processing

01:37:08 - cmdstanpy - INFO - Chain [1] start processing

01:37:11 - cmdstanpy - INFO - Chain [1] done processing

01:37:11 - cmdstanpy - INFO - Chain [1] start processing

01:37:13 - cmdstanpy - INFO - Chain [1] done processing

01:37:13 - cmdstanpy - INFO - Chain [1] start processing

01:37:15 - cmdstanpy - INFO - Chain [1] done processing

01:37:16 - cmdstanpy - INFO - Chain [1] start processing

01:37:18 - cmdstanpy - INFO - Chain [1] done processing

01:37:18 - cmdstanpy - INFO - Chain [1] start processing

01:37:21 - cmdstanpy - INFO - Chain [1] done processing

01:37:21 - cmdstanpy - INFO - Chain [1] start processing

01:37:23 - cmdstanpy - INFO - Chain [1] done processing

01:37:24 - cmdstanpy - INFO - Chain [1] start processing

01:37:26 - cmdstanpy - INFO - Chain [1] done processing

01:37:26 - cmdstanpy - INFO - Chain [1] start processing

01:37:29 - cmdstanpy - INFO - Chain [1] done processing

01:37:29 - cmdstanpy - INFO - Chain [1] start processing

01:37:31 - cmdstanpy - INFO - Chain [1] done processing

01:37:31 - cmdstanpy - INFO - Chain [1] start processing

01:37:34 - cmdstanpy - INFO - Chain [1] done processing

01:37:34 - cmdstanpy - INFO - Chain [1] start processing

01:37:37 - cmdstanpy - INFO - Chain [1] done processing

01:37:37 - cmdstanpy - INFO - Chain [1] start processing

01:37:39 - cmdstanpy - INFO - Chain [1] done processing

01:37:40 - cmdstanpy - INFO - Chain [1] start processing

01:37:42 - cmdstanpy - INFO - Chain [1] done processing

01:37:42 - cmdstanpy - INFO - Chain [1] start processing

01:37:45 - cmdstanpy - INFO - Chain [1] done processing

01:37:45 - cmdstanpy - INFO - Chain [1] start processing

01:37:47 - cmdstanpy - INFO - Chain [1] done processing

01:37:48 - cmdstanpy - INFO - Chain [1] start processing

01:37:50 - cmdstanpy - INFO - Chain [1] done processing

01:37:50 - cmdstanpy - INFO - Chain [1] start processing

01:37:52 - cmdstanpy - INFO - Chain [1] done processing

01:37:52 - cmdstanpy - INFO - Chain [1] start processing

01:37:54 - cmdstanpy - INFO - Chain [1] done processing

01:37:54 - cmdstanpy - INFO - Chain [1] start processing

01:37:57 - cmdstanpy - INFO - Chain [1] done processing

01:37:57 - cmdstanpy - INFO - Chain [1] start processing

01:37:59 - cmdstanpy - INFO - Chain [1] done processing

01:37:59 - cmdstanpy - INFO - Chain [1] start processing

01:38:01 - cmdstanpy - INFO - Chain [1] done processing

01:38:02 - cmdstanpy - INFO - Chain [1] start processing

01:38:04 - cmdstanpy - INFO - Chain [1] done processing

01:38:05 - cmdstanpy - INFO - Chain [1] start processing

01:38:06 - cmdstanpy - INFO - Chain [1] done processing

01:38:07 - cmdstanpy - INFO - Chain [1] start processing

01:38:08 - cmdstanpy - INFO - Chain [1] done processing

01:38:09 - cmdstanpy - INFO - Chain [1] start processing

01:38:11 - cmdstanpy - INFO - Chain [1] done processing

01:38:11 - cmdstanpy - INFO - Chain [1] start processing

01:38:13 - cmdstanpy - INFO - Chain [1] done processing

01:38:14 - cmdstanpy - INFO - Chain [1] start processing

01:38:15 - cmdstanpy - INFO - Chain [1] done processing

01:38:15 - cmdstanpy - INFO - Chain [1] start processing

01:38:17 - cmdstanpy - INFO - Chain [1] done processing

01:38:18 - cmdstanpy - INFO - Chain [1] start processing

01:38:20 - cmdstanpy - INFO - Chain [1] done processing

01:38:20 - cmdstanpy - INFO - Chain [1] start processing

01:38:22 - cmdstanpy - INFO - Chain [1] done processing

01:38:22 - cmdstanpy - INFO - Chain [1] start processing

01:38:24 - cmdstanpy - INFO - Chain [1] done processing

01:38:24 - cmdstanpy - INFO - Chain [1] start processing

01:38:26 - cmdstanpy - INFO - Chain [1] done processing

01:38:26 - cmdstanpy - INFO - Chain [1] start processing

01:38:28 - cmdstanpy - INFO - Chain [1] done processing

01:38:29 - cmdstanpy - INFO - Chain [1] start processing

01:38:31 - cmdstanpy - INFO - Chain [1] done processing

01:38:31 - cmdstanpy - INFO - Chain [1] start processing

01:38:33 - cmdstanpy - INFO - Chain [1] done processing

01:38:33 - cmdstanpy - INFO - Chain [1] start processing

01:38:35 - cmdstanpy - INFO - Chain [1] done processing

01:38:35 - cmdstanpy - INFO - Chain [1] start processing

01:38:37 - cmdstanpy - INFO - Chain [1] done processing

01:38:38 - cmdstanpy - INFO - Chain [1] start processing

01:38:41 - cmdstanpy - INFO - Chain [1] done processing

01:38:41 - cmdstanpy - INFO - Chain [1] start processing

01:38:44 - cmdstanpy - INFO - Chain [1] done processing

01:38:44 - cmdstanpy - INFO - Chain [1] start processing

01:38:46 - cmdstanpy - INFO - Chain [1] done processing

01:38:46 - cmdstanpy - INFO - Chain [1] start processing

01:38:47 - cmdstanpy - INFO - Chain [1] done processing

01:38:48 - cmdstanpy - INFO - Chain [1] start processing

01:38:50 - cmdstanpy - INFO - Chain [1] done processing

01:38:51 - cmdstanpy - INFO - Chain [1] start processing

01:38:52 - cmdstanpy - INFO - Chain [1] done processing

01:38:53 - cmdstanpy - INFO - Chain [1] start processing

01:38:54 - cmdstanpy - INFO - Chain [1] done processing

01:38:55 - cmdstanpy - INFO - Chain [1] start processing

01:38:57 - cmdstanpy - INFO - Chain [1] done processing

01:38:57 - cmdstanpy - INFO - Chain [1] start processing

01:38:59 - cmdstanpy - INFO - Chain [1] done processing

01:38:59 - cmdstanpy - INFO - Chain [1] start processing

01:39:01 - cmdstanpy - INFO - Chain [1] done processing

01:39:02 - cmdstanpy - INFO - Chain [1] start processing

01:39:04 - cmdstanpy - INFO - Chain [1] done processing

01:39:04 - cmdstanpy - INFO - Chain [1] start processing

01:39:06 - cmdstanpy - INFO - Chain [1] done processing

01:39:06 - cmdstanpy - INFO - Chain [1] start processing

01:39:09 - cmdstanpy - INFO - Chain [1] done processing

01:39:09 - cmdstanpy - INFO - Chain [1] start processing

01:39:12 - cmdstanpy - INFO - Chain [1] done processing

01:39:13 - cmdstanpy - INFO - Chain [1] start processing

01:39:14 - cmdstanpy - INFO - Chain [1] done processing

01:39:15 - cmdstanpy - INFO - Chain [1] start processing

01:39:16 - cmdstanpy - INFO - Chain [1] done processing

01:39:17 - cmdstanpy - INFO - Chain [1] start processing

01:39:19 - cmdstanpy - INFO - Chain [1] done processing

01:39:20 - cmdstanpy - INFO - Chain [1] start processing

01:39:21 - cmdstanpy - INFO - Chain [1] done processing

01:39:22 - cmdstanpy - INFO - Chain [1] start processing

01:39:24 - cmdstanpy - INFO - Chain [1] done processing

01:39:24 - cmdstanpy - INFO - Chain [1] start processing

01:39:26 - cmdstanpy - INFO - Chain [1] done processing

01:39:27 - cmdstanpy - INFO - Chain [1] start processing

01:39:29 - cmdstanpy - INFO - Chain [1] done processing

01:39:29 - cmdstanpy - INFO - Chain [1] start processing

01:39:31 - cmdstanpy - INFO - Chain [1] done processing

01:39:31 - cmdstanpy - INFO - Chain [1] start processing

01:39:33 - cmdstanpy - INFO - Chain [1] done processing

01:39:34 - cmdstanpy - INFO - Chain [1] start processing

01:39:36 - cmdstanpy - INFO - Chain [1] done processing

01:39:36 - cmdstanpy - INFO - Chain [1] start processing

01:39:38 - cmdstanpy - INFO - Chain [1] done processing

01:39:39 - cmdstanpy - INFO - Chain [1] start processing

01:39:42 - cmdstanpy - INFO - Chain [1] done processing

01:39:42 - cmdstanpy - INFO - Chain [1] start processing

01:39:44 - cmdstanpy - INFO - Chain [1] done processing

01:39:44 - cmdstanpy - INFO - Chain [1] start processing

01:39:46 - cmdstanpy - INFO - Chain [1] done processing

01:39:47 - cmdstanpy - INFO - Chain [1] start processing

01:39:49 - cmdstanpy - INFO - Chain [1] done processing

01:39:49 - cmdstanpy - INFO - Chain [1] start processing

01:39:51 - cmdstanpy - INFO - Chain [1] done processing

01:39:51 - cmdstanpy - INFO - Chain [1] start processing

01:39:54 - cmdstanpy - INFO - Chain [1] done processing

01:39:54 - cmdstanpy - INFO - Chain [1] start processing

01:39:57 - cmdstanpy - INFO - Chain [1] done processing

01:39:58 - cmdstanpy - INFO - Chain [1] start processing

01:39:59 - cmdstanpy - INFO - Chain [1] done processing

01:40:00 - cmdstanpy - INFO - Chain [1] start processing

01:40:01 - cmdstanpy - INFO - Chain [1] done processing

01:40:02 - cmdstanpy - INFO - Chain [1] start processing

01:40:04 - cmdstanpy - INFO - Chain [1] done processing

01:40:04 - cmdstanpy - INFO - Chain [1] start processing

01:40:07 - cmdstanpy - INFO - Chain [1] done processing

01:40:07 - cmdstanpy - INFO - Chain [1] start processing

01:40:09 - cmdstanpy - INFO - Chain [1] done processing

01:40:10 - cmdstanpy - INFO - Chain [1] start processing

01:40:13 - cmdstanpy - INFO - Chain [1] done processing

01:40:13 - cmdstanpy - INFO - Chain [1] start processing

01:40:16 - cmdstanpy - INFO - Chain [1] done processing

01:40:16 - cmdstanpy - INFO - Chain [1] start processing

01:40:18 - cmdstanpy - INFO - Chain [1] done processing

01:40:19 - cmdstanpy - INFO - Chain [1] start processing

01:40:20 - cmdstanpy - INFO - Chain [1] done processing

01:40:21 - cmdstanpy - INFO - Chain [1] start processing

01:40:23 - cmdstanpy - INFO - Chain [1] done processing

01:40:23 - cmdstanpy - INFO - Chain [1] start processing

01:40:25 - cmdstanpy - INFO - Chain [1] done processing

01:40:26 - cmdstanpy - INFO - Chain [1] start processing

01:40:29 - cmdstanpy - INFO - Chain [1] done processing

01:40:29 - cmdstanpy - INFO - Chain [1] start processing

01:40:32 - cmdstanpy - INFO - Chain [1] done processing

01:40:32 - cmdstanpy - INFO - Chain [1] start processing

01:40:35 - cmdstanpy - INFO - Chain [1] done processing

01:40:36 - cmdstanpy - INFO - Chain [1] start processing

01:40:37 - cmdstanpy - INFO - Chain [1] done processing

01:40:38 - cmdstanpy - INFO - Chain [1] start processing

01:40:40 - cmdstanpy - INFO - Chain [1] done processing

01:40:40 - cmdstanpy - INFO - Chain [1] start processing

01:40:43 - cmdstanpy - INFO - Chain [1] done processing

01:40:44 - cmdstanpy - INFO - Chain [1] start processing

01:40:47 - cmdstanpy - INFO - Chain [1] done processing

01:40:47 - cmdstanpy - INFO - Chain [1] start processing

01:40:49 - cmdstanpy - INFO - Chain [1] done processing

01:40:50 - cmdstanpy - INFO - Chain [1] start processing

01:40:52 - cmdstanpy - INFO - Chain [1] done processing

01:40:52 - cmdstanpy - INFO - Chain [1] start processing

01:40:54 - cmdstanpy - INFO - Chain [1] done processing

01:40:55 - cmdstanpy - INFO - Chain [1] start processing

01:40:56 - cmdstanpy - INFO - Chain [1] done processing

01:40:57 - cmdstanpy - INFO - Chain [1] start processing

01:40:59 - cmdstanpy - INFO - Chain [1] done processing

01:40:59 - cmdstanpy - INFO - Chain [1] start processing

01:41:01 - cmdstanpy - INFO - Chain [1] done processing

01:41:01 - cmdstanpy - INFO - Chain [1] start processing

01:41:04 - cmdstanpy - INFO - Chain [1] done processing

01:41:05 - cmdstanpy - INFO - Chain [1] start processing

01:41:07 - cmdstanpy - INFO - Chain [1] done processing

01:41:07 - cmdstanpy - INFO - Chain [1] start processing

01:41:09 - cmdstanpy - INFO - Chain [1] done processing

01:41:10 - cmdstanpy - INFO - Chain [1] start processing

01:41:12 - cmdstanpy - INFO - Chain [1] done processing

01:41:12 - cmdstanpy - INFO - Chain [1] start processing

01:41:15 - cmdstanpy - INFO - Chain [1] done processing

01:41:16 - cmdstanpy - INFO - Chain [1] start processing

01:41:18 - cmdstanpy - INFO - Chain [1] done processing

01:41:19 - cmdstanpy - INFO - Chain [1] start processing

01:41:21 - cmdstanpy - INFO - Chain [1] done processing

01:41:21 - cmdstanpy - INFO - Chain [1] start processing

01:41:23 - cmdstanpy - INFO - Chain [1] done processing

01:41:24 - cmdstanpy - INFO - Chain [1] start processing

01:41:26 - cmdstanpy - INFO - Chain [1] done processing

01:41:26 - cmdstanpy - INFO - Chain [1] start processing

01:41:29 - cmdstanpy - INFO - Chain [1] done processing

01:41:29 - cmdstanpy - INFO - Chain [1] start processing

01:41:31 - cmdstanpy - INFO - Chain [1] done processing

01:41:31 - cmdstanpy - INFO - Chain [1] start processing

01:41:34 - cmdstanpy - INFO - Chain [1] done processing

01:41:34 - cmdstanpy - INFO - Chain [1] start processing

01:41:37 - cmdstanpy - INFO - Chain [1] done processing

01:41:38 - cmdstanpy - INFO - Chain [1] start processing

01:41:40 - cmdstanpy - INFO - Chain [1] done processing

01:41:40 - cmdstanpy - INFO - Chain [1] start processing

01:41:43 - cmdstanpy - INFO - Chain [1] done processing

01:41:43 - cmdstanpy - INFO - Chain [1] start processing

01:41:45 - cmdstanpy - INFO - Chain [1] done processing

01:41:45 - cmdstanpy - INFO - Chain [1] start processing

01:41:48 - cmdstanpy - INFO - Chain [1] done processing

01:41:48 - cmdstanpy - INFO - Chain [1] start processing

01:41:51 - cmdstanpy - INFO - Chain [1] done processing

h=1: Prophet cps elegido 0.5
h= 1 Paseo aleatorio  [cpu]    0.0 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

h= 1 ARIMA            [cpu]   64.5 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

h= 1 VAR              [cpu]    1.0 s

01:42:57 - cmdstanpy - INFO - Chain [1] start processing

01:42:59 - cmdstanpy - INFO - Chain [1] done processing

01:43:00 - cmdstanpy - INFO - Chain [1] start processing

01:43:02 - cmdstanpy - INFO - Chain [1] done processing

01:43:03 - cmdstanpy - INFO - Chain [1] start processing

01:43:05 - cmdstanpy - INFO - Chain [1] done processing

01:43:05 - cmdstanpy - INFO - Chain [1] start processing

01:43:07 - cmdstanpy - INFO - Chain [1] done processing

01:43:08 - cmdstanpy - INFO - Chain [1] start processing

01:43:10 - cmdstanpy - INFO - Chain [1] done processing

01:43:11 - cmdstanpy - INFO - Chain [1] start processing

01:43:13 - cmdstanpy - INFO - Chain [1] done processing

01:43:14 - cmdstanpy - INFO - Chain [1] start processing

01:43:17 - cmdstanpy - INFO - Chain [1] done processing

01:43:17 - cmdstanpy - INFO - Chain [1] start processing

01:43:19 - cmdstanpy - INFO - Chain [1] done processing

01:43:19 - cmdstanpy - INFO - Chain [1] start processing

01:43:22 - cmdstanpy - INFO - Chain [1] done processing

01:43:22 - cmdstanpy - INFO - Chain [1] start processing

01:43:24 - cmdstanpy - INFO - Chain [1] done processing

01:43:24 - cmdstanpy - INFO - Chain [1] start processing

01:43:27 - cmdstanpy - INFO - Chain [1] done processing

01:43:28 - cmdstanpy - INFO - Chain [1] start processing

01:43:30 - cmdstanpy - INFO - Chain [1] done processing

01:43:30 - cmdstanpy - INFO - Chain [1] start processing

01:43:33 - cmdstanpy - INFO - Chain [1] done processing

01:43:34 - cmdstanpy - INFO - Chain [1] start processing

01:43:36 - cmdstanpy - INFO - Chain [1] done processing

01:43:36 - cmdstanpy - INFO - Chain [1] start processing

01:43:38 - cmdstanpy - INFO - Chain [1] done processing

01:43:38 - cmdstanpy - INFO - Chain [1] start processing

01:43:41 - cmdstanpy - INFO - Chain [1] done processing

01:43:41 - cmdstanpy - INFO - Chain [1] start processing

01:43:44 - cmdstanpy - INFO - Chain [1] done processing

01:43:44 - cmdstanpy - INFO - Chain [1] start processing

01:43:46 - cmdstanpy - INFO - Chain [1] done processing

01:43:47 - cmdstanpy - INFO - Chain [1] start processing

01:43:48 - cmdstanpy - INFO - Chain [1] done processing

01:43:49 - cmdstanpy - INFO - Chain [1] start processing

01:43:51 - cmdstanpy - INFO - Chain [1] done processing

01:43:51 - cmdstanpy - INFO - Chain [1] start processing

01:43:53 - cmdstanpy - INFO - Chain [1] done processing

01:43:54 - cmdstanpy - INFO - Chain [1] start processing

01:43:56 - cmdstanpy - INFO - Chain [1] done processing

01:43:57 - cmdstanpy - INFO - Chain [1] start processing

01:43:59 - cmdstanpy - INFO - Chain [1] done processing

01:44:00 - cmdstanpy - INFO - Chain [1] start processing

01:44:03 - cmdstanpy - INFO - Chain [1] done processing

01:44:03 - cmdstanpy - INFO - Chain [1] start processing

01:44:06 - cmdstanpy - INFO - Chain [1] done processing

01:44:06 - cmdstanpy - INFO - Chain [1] start processing

01:44:09 - cmdstanpy - INFO - Chain [1] done processing

01:44:10 - cmdstanpy - INFO - Chain [1] start processing

01:44:12 - cmdstanpy - INFO - Chain [1] done processing

01:44:12 - cmdstanpy - INFO - Chain [1] start processing

01:44:14 - cmdstanpy - INFO - Chain [1] done processing

01:44:15 - cmdstanpy - INFO - Chain [1] start processing

01:44:17 - cmdstanpy - INFO - Chain [1] done processing

01:44:17 - cmdstanpy - INFO - Chain [1] start processing

01:44:19 - cmdstanpy - INFO - Chain [1] done processing

01:44:20 - cmdstanpy - INFO - Chain [1] start processing

01:44:22 - cmdstanpy - INFO - Chain [1] done processing

01:44:23 - cmdstanpy - INFO - Chain [1] start processing

01:44:25 - cmdstanpy - INFO - Chain [1] done processing

01:44:26 - cmdstanpy - INFO - Chain [1] start processing

01:44:28 - cmdstanpy - INFO - Chain [1] done processing

01:44:29 - cmdstanpy - INFO - Chain [1] start processing

01:44:31 - cmdstanpy - INFO - Chain [1] done processing

01:44:31 - cmdstanpy - INFO - Chain [1] start processing

01:44:34 - cmdstanpy - INFO - Chain [1] done processing

01:44:34 - cmdstanpy - INFO - Chain [1] start processing

01:44:36 - cmdstanpy - INFO - Chain [1] done processing

01:44:37 - cmdstanpy - INFO - Chain [1] start processing

01:44:39 - cmdstanpy - INFO - Chain [1] done processing

01:44:40 - cmdstanpy - INFO - Chain [1] start processing

01:44:42 - cmdstanpy - INFO - Chain [1] done processing

01:44:43 - cmdstanpy - INFO - Chain [1] start processing

01:44:45 - cmdstanpy - INFO - Chain [1] done processing

01:44:46 - cmdstanpy - INFO - Chain [1] start processing

01:44:48 - cmdstanpy - INFO - Chain [1] done processing

01:44:48 - cmdstanpy - INFO - Chain [1] start processing

01:44:50 - cmdstanpy - INFO - Chain [1] done processing

01:44:51 - cmdstanpy - INFO - Chain [1] start processing

01:44:53 - cmdstanpy - INFO - Chain [1] done processing

01:44:53 - cmdstanpy - INFO - Chain [1] start processing

01:44:56 - cmdstanpy - INFO - Chain [1] done processing

01:44:56 - cmdstanpy - INFO - Chain [1] start processing

01:44:59 - cmdstanpy - INFO - Chain [1] done processing

01:45:00 - cmdstanpy - INFO - Chain [1] start processing

01:45:02 - cmdstanpy - INFO - Chain [1] done processing

01:45:02 - cmdstanpy - INFO - Chain [1] start processing

01:45:04 - cmdstanpy - INFO - Chain [1] done processing

01:45:05 - cmdstanpy - INFO - Chain [1] start processing

01:45:07 - cmdstanpy - INFO - Chain [1] done processing

01:45:07 - cmdstanpy - INFO - Chain [1] start processing

01:45:10 - cmdstanpy - INFO - Chain [1] done processing

01:45:11 - cmdstanpy - INFO - Chain [1] start processing

01:45:13 - cmdstanpy - INFO - Chain [1] done processing

01:45:13 - cmdstanpy - INFO - Chain [1] start processing

01:45:15 - cmdstanpy - INFO - Chain [1] done processing

01:45:15 - cmdstanpy - INFO - Chain [1] start processing

01:45:18 - cmdstanpy - INFO - Chain [1] done processing

01:45:18 - cmdstanpy - INFO - Chain [1] start processing

01:45:21 - cmdstanpy - INFO - Chain [1] done processing

01:45:22 - cmdstanpy - INFO - Chain [1] start processing

01:45:25 - cmdstanpy - INFO - Chain [1] done processing

01:45:26 - cmdstanpy - INFO - Chain [1] start processing

01:45:28 - cmdstanpy - INFO - Chain [1] done processing

01:45:29 - cmdstanpy - INFO - Chain [1] start processing

01:45:29 - cmdstanpy - INFO - Chain [1] done processing

01:45:30 - cmdstanpy - INFO - Chain [1] start processing

01:45:30 - cmdstanpy - INFO - Chain [1] done processing

01:45:30 - cmdstanpy - INFO - Chain [1] start processing

01:45:30 - cmdstanpy - INFO - Chain [1] done processing

01:45:31 - cmdstanpy - INFO - Chain [1] start processing

01:45:31 - cmdstanpy - INFO - Chain [1] done processing

01:45:32 - cmdstanpy - INFO - Chain [1] start processing

01:45:32 - cmdstanpy - INFO - Chain [1] done processing

01:45:32 - cmdstanpy - INFO - Chain [1] start processing

01:45:33 - cmdstanpy - INFO - Chain [1] done processing

01:45:33 - cmdstanpy - INFO - Chain [1] start processing

01:45:33 - cmdstanpy - INFO - Chain [1] done processing

01:45:34 - cmdstanpy - INFO - Chain [1] start processing

01:45:34 - cmdstanpy - INFO - Chain [1] done processing

01:45:34 - cmdstanpy - INFO - Chain [1] start processing

01:45:35 - cmdstanpy - INFO - Chain [1] done processing

01:45:35 - cmdstanpy - INFO - Chain [1] start processing

01:45:35 - cmdstanpy - INFO - Chain [1] done processing

01:45:36 - cmdstanpy - INFO - Chain [1] start processing

01:45:36 - cmdstanpy - INFO - Chain [1] done processing

01:45:37 - cmdstanpy - INFO - Chain [1] start processing

01:45:37 - cmdstanpy - INFO - Chain [1] done processing

01:45:37 - cmdstanpy - INFO - Chain [1] start processing

01:45:38 - cmdstanpy - INFO - Chain [1] done processing

01:45:38 - cmdstanpy - INFO - Chain [1] start processing

01:45:38 - cmdstanpy - INFO - Chain [1] done processing

01:45:39 - cmdstanpy - INFO - Chain [1] start processing

01:45:39 - cmdstanpy - INFO - Chain [1] done processing

01:45:40 - cmdstanpy - INFO - Chain [1] start processing

01:45:40 - cmdstanpy - INFO - Chain [1] done processing

01:45:40 - cmdstanpy - INFO - Chain [1] start processing

01:45:41 - cmdstanpy - INFO - Chain [1] done processing

01:45:41 - cmdstanpy - INFO - Chain [1] start processing

01:45:41 - cmdstanpy - INFO - Chain [1] done processing

01:45:42 - cmdstanpy - INFO - Chain [1] start processing

01:45:42 - cmdstanpy - INFO - Chain [1] done processing

01:45:43 - cmdstanpy - INFO - Chain [1] start processing

01:45:43 - cmdstanpy - INFO - Chain [1] done processing

01:45:43 - cmdstanpy - INFO - Chain [1] start processing

01:45:43 - cmdstanpy - INFO - Chain [1] done processing

01:45:44 - cmdstanpy - INFO - Chain [1] start processing

01:45:44 - cmdstanpy - INFO - Chain [1] done processing

01:45:45 - cmdstanpy - INFO - Chain [1] start processing

01:45:45 - cmdstanpy - INFO - Chain [1] done processing

01:45:46 - cmdstanpy - INFO - Chain [1] start processing

01:45:46 - cmdstanpy - INFO - Chain [1] done processing

01:45:46 - cmdstanpy - INFO - Chain [1] start processing

01:45:46 - cmdstanpy - INFO - Chain [1] done processing

01:45:47 - cmdstanpy - INFO - Chain [1] start processing

01:45:47 - cmdstanpy - INFO - Chain [1] done processing

01:45:48 - cmdstanpy - INFO - Chain [1] start processing

01:45:48 - cmdstanpy - INFO - Chain [1] done processing

01:45:48 - cmdstanpy - INFO - Chain [1] start processing

01:45:49 - cmdstanpy - INFO - Chain [1] done processing

01:45:49 - cmdstanpy - INFO - Chain [1] start processing

01:45:49 - cmdstanpy - INFO - Chain [1] done processing

01:45:50 - cmdstanpy - INFO - Chain [1] start processing

01:45:50 - cmdstanpy - INFO - Chain [1] done processing

01:45:50 - cmdstanpy - INFO - Chain [1] start processing

01:45:51 - cmdstanpy - INFO - Chain [1] done processing

01:45:51 - cmdstanpy - INFO - Chain [1] start processing

01:45:51 - cmdstanpy - INFO - Chain [1] done processing

01:45:52 - cmdstanpy - INFO - Chain [1] start processing

01:45:52 - cmdstanpy - INFO - Chain [1] done processing

01:45:52 - cmdstanpy - INFO - Chain [1] start processing

01:45:53 - cmdstanpy - INFO - Chain [1] done processing

01:45:53 - cmdstanpy - INFO - Chain [1] start processing

01:45:53 - cmdstanpy - INFO - Chain [1] done processing

01:45:54 - cmdstanpy - INFO - Chain [1] start processing

01:45:54 - cmdstanpy - INFO - Chain [1] done processing

01:45:54 - cmdstanpy - INFO - Chain [1] start processing

01:45:55 - cmdstanpy - INFO - Chain [1] done processing

01:45:55 - cmdstanpy - INFO - Chain [1] start processing

01:45:56 - cmdstanpy - INFO - Chain [1] done processing

01:45:56 - cmdstanpy - INFO - Chain [1] start processing

01:45:56 - cmdstanpy - INFO - Chain [1] done processing

01:45:57 - cmdstanpy - INFO - Chain [1] start processing

01:45:57 - cmdstanpy - INFO - Chain [1] done processing

01:45:58 - cmdstanpy - INFO - Chain [1] start processing

01:45:58 - cmdstanpy - INFO - Chain [1] done processing

01:45:58 - cmdstanpy - INFO - Chain [1] start processing

01:45:59 - cmdstanpy - INFO - Chain [1] done processing

01:45:59 - cmdstanpy - INFO - Chain [1] start processing

01:45:59 - cmdstanpy - INFO - Chain [1] done processing

01:46:00 - cmdstanpy - INFO - Chain [1] start processing

01:46:00 - cmdstanpy - INFO - Chain [1] done processing

01:46:01 - cmdstanpy - INFO - Chain [1] start processing

01:46:01 - cmdstanpy - INFO - Chain [1] done processing

01:46:01 - cmdstanpy - INFO - Chain [1] start processing

01:46:01 - cmdstanpy - INFO - Chain [1] done processing

01:46:02 - cmdstanpy - INFO - Chain [1] start processing

01:46:02 - cmdstanpy - INFO - Chain [1] done processing

01:46:03 - cmdstanpy - INFO - Chain [1] start processing

01:46:03 - cmdstanpy - INFO - Chain [1] done processing

01:46:03 - cmdstanpy - INFO - Chain [1] start processing

01:46:03 - cmdstanpy - INFO - Chain [1] done processing

01:46:04 - cmdstanpy - INFO - Chain [1] start processing

01:46:04 - cmdstanpy - INFO - Chain [1] done processing

01:46:04 - cmdstanpy - INFO - Chain [1] start processing

01:46:04 - cmdstanpy - INFO - Chain [1] done processing

01:46:05 - cmdstanpy - INFO - Chain [1] start processing

01:46:05 - cmdstanpy - INFO - Chain [1] done processing

01:46:06 - cmdstanpy - INFO - Chain [1] start processing

01:46:06 - cmdstanpy - INFO - Chain [1] done processing

01:46:06 - cmdstanpy - INFO - Chain [1] start processing

01:46:06 - cmdstanpy - INFO - Chain [1] done processing

01:46:07 - cmdstanpy - INFO - Chain [1] start processing

01:46:07 - cmdstanpy - INFO - Chain [1] done processing

01:46:08 - cmdstanpy - INFO - Chain [1] start processing

01:46:08 - cmdstanpy - INFO - Chain [1] done processing

01:46:08 - cmdstanpy - INFO - Chain [1] start processing

01:46:08 - cmdstanpy - INFO - Chain [1] done processing

01:46:09 - cmdstanpy - INFO - Chain [1] start processing

01:46:09 - cmdstanpy - INFO - Chain [1] done processing

01:46:10 - cmdstanpy - INFO - Chain [1] start processing

01:46:10 - cmdstanpy - INFO - Chain [1] done processing

01:46:10 - cmdstanpy - INFO - Chain [1] start processing

01:46:10 - cmdstanpy - INFO - Chain [1] done processing

01:46:11 - cmdstanpy - INFO - Chain [1] start processing

01:46:11 - cmdstanpy - INFO - Chain [1] done processing

01:46:12 - cmdstanpy - INFO - Chain [1] start processing

01:46:12 - cmdstanpy - INFO - Chain [1] done processing

01:46:12 - cmdstanpy - INFO - Chain [1] start processing

01:46:13 - cmdstanpy - INFO - Chain [1] done processing

01:46:13 - cmdstanpy - INFO - Chain [1] start processing

01:46:13 - cmdstanpy - INFO - Chain [1] done processing

01:46:14 - cmdstanpy - INFO - Chain [1] start processing

01:46:14 - cmdstanpy - INFO - Chain [1] done processing

01:46:14 - cmdstanpy - INFO - Chain [1] start processing

01:46:14 - cmdstanpy - INFO - Chain [1] done processing

01:46:15 - cmdstanpy - INFO - Chain [1] start processing

01:46:15 - cmdstanpy - INFO - Chain [1] done processing

01:46:15 - cmdstanpy - INFO - Chain [1] start processing

01:46:16 - cmdstanpy - INFO - Chain [1] done processing

01:46:16 - cmdstanpy - INFO - Chain [1] start processing

01:46:16 - cmdstanpy - INFO - Chain [1] done processing

01:46:17 - cmdstanpy - INFO - Chain [1] start processing

01:46:17 - cmdstanpy - INFO - Chain [1] done processing

01:46:17 - cmdstanpy - INFO - Chain [1] start processing

01:46:18 - cmdstanpy - INFO - Chain [1] done processing

01:46:18 - cmdstanpy - INFO - Chain [1] start processing

01:46:18 - cmdstanpy - INFO - Chain [1] done processing

01:46:19 - cmdstanpy - INFO - Chain [1] start processing

01:46:19 - cmdstanpy - INFO - Chain [1] done processing

01:46:19 - cmdstanpy - INFO - Chain [1] start processing

01:46:19 - cmdstanpy - INFO - Chain [1] done processing

01:46:20 - cmdstanpy - INFO - Chain [1] start processing

01:46:20 - cmdstanpy - INFO - Chain [1] done processing

01:46:20 - cmdstanpy - INFO - Chain [1] start processing

01:46:21 - cmdstanpy - INFO - Chain [1] done processing

01:46:21 - cmdstanpy - INFO - Chain [1] start processing

01:46:21 - cmdstanpy - INFO - Chain [1] done processing

01:46:22 - cmdstanpy - INFO - Chain [1] start processing

01:46:22 - cmdstanpy - INFO - Chain [1] done processing

01:46:22 - cmdstanpy - INFO - Chain [1] start processing

01:46:23 - cmdstanpy - INFO - Chain [1] done processing

01:46:23 - cmdstanpy - INFO - Chain [1] start processing

01:46:23 - cmdstanpy - INFO - Chain [1] done processing

01:46:24 - cmdstanpy - INFO - Chain [1] start processing

01:46:24 - cmdstanpy - INFO - Chain [1] done processing

01:46:24 - cmdstanpy - INFO - Chain [1] start processing

01:46:25 - cmdstanpy - INFO - Chain [1] done processing

01:46:25 - cmdstanpy - INFO - Chain [1] start processing

01:46:25 - cmdstanpy - INFO - Chain [1] done processing

01:46:26 - cmdstanpy - INFO - Chain [1] start processing

01:46:26 - cmdstanpy - INFO - Chain [1] done processing

01:46:26 - cmdstanpy - INFO - Chain [1] start processing

01:46:27 - cmdstanpy - INFO - Chain [1] done processing

01:46:27 - cmdstanpy - INFO - Chain [1] start processing

01:46:27 - cmdstanpy - INFO - Chain [1] done processing

01:46:28 - cmdstanpy - INFO - Chain [1] start processing

01:46:28 - cmdstanpy - INFO - Chain [1] done processing

01:46:28 - cmdstanpy - INFO - Chain [1] start processing

01:46:29 - cmdstanpy - INFO - Chain [1] done processing

01:46:29 - cmdstanpy - INFO - Chain [1] start processing

01:46:29 - cmdstanpy - INFO - Chain [1] done processing

01:46:30 - cmdstanpy - INFO - Chain [1] start processing

01:46:30 - cmdstanpy - INFO - Chain [1] done processing

01:46:30 - cmdstanpy - INFO - Chain [1] start processing

01:46:31 - cmdstanpy - INFO - Chain [1] done processing

01:46:31 - cmdstanpy - INFO - Chain [1] start processing

01:46:31 - cmdstanpy - INFO - Chain [1] done processing

01:46:32 - cmdstanpy - INFO - Chain [1] start processing

01:46:32 - cmdstanpy - INFO - Chain [1] done processing

01:46:32 - cmdstanpy - INFO - Chain [1] start processing

01:46:33 - cmdstanpy - INFO - Chain [1] done processing

01:46:33 - cmdstanpy - INFO - Chain [1] start processing

01:46:33 - cmdstanpy - INFO - Chain [1] done processing

01:46:34 - cmdstanpy - INFO - Chain [1] start processing

01:46:34 - cmdstanpy - INFO - Chain [1] done processing

01:46:34 - cmdstanpy - INFO - Chain [1] start processing

01:46:35 - cmdstanpy - INFO - Chain [1] done processing

01:46:35 - cmdstanpy - INFO - Chain [1] start processing

01:46:35 - cmdstanpy - INFO - Chain [1] done processing

01:46:36 - cmdstanpy - INFO - Chain [1] start processing

01:46:36 - cmdstanpy - INFO - Chain [1] done processing

01:46:36 - cmdstanpy - INFO - Chain [1] start processing

01:46:37 - cmdstanpy - INFO - Chain [1] done processing

01:46:37 - cmdstanpy - INFO - Chain [1] start processing

01:46:37 - cmdstanpy - INFO - Chain [1] done processing

01:46:38 - cmdstanpy - INFO - Chain [1] start processing

01:46:38 - cmdstanpy - INFO - Chain [1] done processing

01:46:38 - cmdstanpy - INFO - Chain [1] start processing

01:46:39 - cmdstanpy - INFO - Chain [1] done processing

01:46:39 - cmdstanpy - INFO - Chain [1] start processing

01:46:39 - cmdstanpy - INFO - Chain [1] done processing

01:46:40 - cmdstanpy - INFO - Chain [1] start processing

01:46:40 - cmdstanpy - INFO - Chain [1] done processing

01:46:41 - cmdstanpy - INFO - Chain [1] start processing

01:46:41 - cmdstanpy - INFO - Chain [1] done processing

01:46:41 - cmdstanpy - INFO - Chain [1] start processing

01:46:41 - cmdstanpy - INFO - Chain [1] done processing

01:46:42 - cmdstanpy - INFO - Chain [1] start processing

01:46:42 - cmdstanpy - INFO - Chain [1] done processing

01:46:42 - cmdstanpy - INFO - Chain [1] start processing

01:46:43 - cmdstanpy - INFO - Chain [1] done processing

01:46:43 - cmdstanpy - INFO - Chain [1] start processing

01:46:43 - cmdstanpy - INFO - Chain [1] done processing

01:46:44 - cmdstanpy - INFO - Chain [1] start processing

01:46:44 - cmdstanpy - INFO - Chain [1] done processing

01:46:44 - cmdstanpy - INFO - Chain [1] start processing

01:46:45 - cmdstanpy - INFO - Chain [1] done processing

01:46:45 - cmdstanpy - INFO - Chain [1] start processing

01:46:45 - cmdstanpy - INFO - Chain [1] done processing

01:46:46 - cmdstanpy - INFO - Chain [1] start processing

01:46:46 - cmdstanpy - INFO - Chain [1] done processing

01:46:47 - cmdstanpy - INFO - Chain [1] start processing

01:46:47 - cmdstanpy - INFO - Chain [1] done processing

01:46:47 - cmdstanpy - INFO - Chain [1] start processing

01:46:47 - cmdstanpy - INFO - Chain [1] done processing

01:46:48 - cmdstanpy - INFO - Chain [1] start processing

01:46:48 - cmdstanpy - INFO - Chain [1] done processing

01:46:49 - cmdstanpy - INFO - Chain [1] start processing

01:46:49 - cmdstanpy - INFO - Chain [1] done processing

01:46:49 - cmdstanpy - INFO - Chain [1] start processing

01:46:50 - cmdstanpy - INFO - Chain [1] done processing

01:46:50 - cmdstanpy - INFO - Chain [1] start processing

01:46:50 - cmdstanpy - INFO - Chain [1] done processing

01:46:51 - cmdstanpy - INFO - Chain [1] start processing

01:46:51 - cmdstanpy - INFO - Chain [1] done processing

01:46:51 - cmdstanpy - INFO - Chain [1] start processing

01:46:52 - cmdstanpy - INFO - Chain [1] done processing

01:46:52 - cmdstanpy - INFO - Chain [1] start processing

01:46:53 - cmdstanpy - INFO - Chain [1] done processing

01:46:53 - cmdstanpy - INFO - Chain [1] start processing

01:46:53 - cmdstanpy - INFO - Chain [1] done processing

01:46:54 - cmdstanpy - INFO - Chain [1] start processing

01:46:54 - cmdstanpy - INFO - Chain [1] done processing

01:46:54 - cmdstanpy - INFO - Chain [1] start processing

01:46:55 - cmdstanpy - INFO - Chain [1] done processing

01:46:55 - cmdstanpy - INFO - Chain [1] start processing

01:46:55 - cmdstanpy - INFO - Chain [1] done processing

01:46:56 - cmdstanpy - INFO - Chain [1] start processing

01:46:56 - cmdstanpy - INFO - Chain [1] done processing

01:46:56 - cmdstanpy - INFO - Chain [1] start processing

01:46:57 - cmdstanpy - INFO - Chain [1] done processing

01:46:57 - cmdstanpy - INFO - Chain [1] start processing

01:46:57 - cmdstanpy - INFO - Chain [1] done processing

01:46:58 - cmdstanpy - INFO - Chain [1] start processing

01:46:58 - cmdstanpy - INFO - Chain [1] done processing

01:46:58 - cmdstanpy - INFO - Chain [1] start processing

01:46:58 - cmdstanpy - INFO - Chain [1] done processing

01:46:59 - cmdstanpy - INFO - Chain [1] start processing

01:46:59 - cmdstanpy - INFO - Chain [1] done processing

01:47:00 - cmdstanpy - INFO - Chain [1] start processing

01:47:00 - cmdstanpy - INFO - Chain [1] done processing

01:47:00 - cmdstanpy - INFO - Chain [1] start processing

01:47:00 - cmdstanpy - INFO - Chain [1] done processing

01:47:01 - cmdstanpy - INFO - Chain [1] start processing

01:47:01 - cmdstanpy - INFO - Chain [1] done processing

01:47:02 - cmdstanpy - INFO - Chain [1] start processing

01:47:02 - cmdstanpy - INFO - Chain [1] done processing

01:47:02 - cmdstanpy - INFO - Chain [1] start processing

01:47:03 - cmdstanpy - INFO - Chain [1] done processing

01:47:03 - cmdstanpy - INFO - Chain [1] start processing

01:47:03 - cmdstanpy - INFO - Chain [1] done processing

01:47:04 - cmdstanpy - INFO - Chain [1] start processing

01:47:04 - cmdstanpy - INFO - Chain [1] done processing

01:47:04 - cmdstanpy - INFO - Chain [1] start processing

01:47:04 - cmdstanpy - INFO - Chain [1] done processing

01:47:05 - cmdstanpy - INFO - Chain [1] start processing

01:47:05 - cmdstanpy - INFO - Chain [1] done processing

01:47:06 - cmdstanpy - INFO - Chain [1] start processing

01:47:06 - cmdstanpy - INFO - Chain [1] done processing

01:47:06 - cmdstanpy - INFO - Chain [1] start processing

01:47:07 - cmdstanpy - INFO - Chain [1] done processing

01:47:07 - cmdstanpy - INFO - Chain [1] start processing

01:47:07 - cmdstanpy - INFO - Chain [1] done processing

01:47:07 - cmdstanpy - INFO - Chain [1] start processing

01:47:08 - cmdstanpy - INFO - Chain [1] done processing

01:47:08 - cmdstanpy - INFO - Chain [1] start processing

01:47:08 - cmdstanpy - INFO - Chain [1] done processing

01:47:09 - cmdstanpy - INFO - Chain [1] start processing

01:47:09 - cmdstanpy - INFO - Chain [1] done processing

01:47:10 - cmdstanpy - INFO - Chain [1] start processing

01:47:10 - cmdstanpy - INFO - Chain [1] done processing

01:47:10 - cmdstanpy - INFO - Chain [1] start processing

01:47:11 - cmdstanpy - INFO - Chain [1] done processing

01:47:11 - cmdstanpy - INFO - Chain [1] start processing

01:47:11 - cmdstanpy - INFO - Chain [1] done processing

01:47:12 - cmdstanpy - INFO - Chain [1] start processing

01:47:12 - cmdstanpy - INFO - Chain [1] done processing

01:47:12 - cmdstanpy - INFO - Chain [1] start processing

01:47:12 - cmdstanpy - INFO - Chain [1] done processing

01:47:13 - cmdstanpy - INFO - Chain [1] start processing

01:47:13 - cmdstanpy - INFO - Chain [1] done processing

01:47:14 - cmdstanpy - INFO - Chain [1] start processing

01:47:14 - cmdstanpy - INFO - Chain [1] done processing

01:47:14 - cmdstanpy - INFO - Chain [1] start processing

01:47:14 - cmdstanpy - INFO - Chain [1] done processing

01:47:15 - cmdstanpy - INFO - Chain [1] start processing

01:47:15 - cmdstanpy - INFO - Chain [1] done processing

01:47:15 - cmdstanpy - INFO - Chain [1] start processing

01:47:16 - cmdstanpy - INFO - Chain [1] done processing

01:47:16 - cmdstanpy - INFO - Chain [1] start processing

01:47:16 - cmdstanpy - INFO - Chain [1] done processing

01:47:17 - cmdstanpy - INFO - Chain [1] start processing

01:47:17 - cmdstanpy - INFO - Chain [1] done processing

01:47:17 - cmdstanpy - INFO - Chain [1] start processing

01:47:18 - cmdstanpy - INFO - Chain [1] done processing

01:47:18 - cmdstanpy - INFO - Chain [1] start processing

01:47:18 - cmdstanpy - INFO - Chain [1] done processing

h= 1 Prophet          [cpu]  261.6 s

h= 1 Ridge            [cuda]   19.2 s

h= 1 Random Forest    [cuda]  761.5 s

h= 1 XGBoost          [cuda]  674.8 s

02:11:34 - cmdstanpy - INFO - Chain [1] start processing

02:11:36 - cmdstanpy - INFO - Chain [1] done processing

02:11:36 - cmdstanpy - INFO - Chain [1] start processing

02:11:37 - cmdstanpy - INFO - Chain [1] done processing

02:11:37 - cmdstanpy - INFO - Chain [1] start processing

02:11:38 - cmdstanpy - INFO - Chain [1] done processing

02:11:38 - cmdstanpy - INFO - Chain [1] start processing

02:11:39 - cmdstanpy - INFO - Chain [1] done processing

02:11:39 - cmdstanpy - INFO - Chain [1] start processing

02:11:40 - cmdstanpy - INFO - Chain [1] done processing

02:11:40 - cmdstanpy - INFO - Chain [1] start processing

02:11:41 - cmdstanpy - INFO - Chain [1] done processing

02:11:41 - cmdstanpy - INFO - Chain [1] start processing

02:11:42 - cmdstanpy - INFO - Chain [1] done processing

02:11:42 - cmdstanpy - INFO - Chain [1] start processing

02:11:43 - cmdstanpy - INFO - Chain [1] done processing

02:11:44 - cmdstanpy - INFO - Chain [1] start processing

02:11:44 - cmdstanpy - INFO - Chain [1] done processing

02:11:45 - cmdstanpy - INFO - Chain [1] start processing

02:11:45 - cmdstanpy - INFO - Chain [1] done processing

02:11:46 - cmdstanpy - INFO - Chain [1] start processing

02:11:46 - cmdstanpy - INFO - Chain [1] done processing

02:11:47 - cmdstanpy - INFO - Chain [1] start processing

02:11:47 - cmdstanpy - INFO - Chain [1] done processing

02:11:47 - cmdstanpy - INFO - Chain [1] start processing

02:11:48 - cmdstanpy - INFO - Chain [1] done processing

02:11:48 - cmdstanpy - INFO - Chain [1] start processing

02:11:49 - cmdstanpy - INFO - Chain [1] done processing

02:11:50 - cmdstanpy - INFO - Chain [1] start processing

02:11:51 - cmdstanpy - INFO - Chain [1] done processing

02:11:51 - cmdstanpy - INFO - Chain [1] start processing

02:11:52 - cmdstanpy - INFO - Chain [1] done processing

02:11:52 - cmdstanpy - INFO - Chain [1] start processing

02:11:53 - cmdstanpy - INFO - Chain [1] done processing

02:11:53 - cmdstanpy - INFO - Chain [1] start processing

02:11:54 - cmdstanpy - INFO - Chain [1] done processing

02:11:54 - cmdstanpy - INFO - Chain [1] start processing

02:11:55 - cmdstanpy - INFO - Chain [1] done processing

02:11:55 - cmdstanpy - INFO - Chain [1] start processing

02:11:56 - cmdstanpy - INFO - Chain [1] done processing

02:11:57 - cmdstanpy - INFO - Chain [1] start processing

02:11:57 - cmdstanpy - INFO - Chain [1] done processing

02:11:58 - cmdstanpy - INFO - Chain [1] start processing

02:11:58 - cmdstanpy - INFO - Chain [1] done processing

02:11:59 - cmdstanpy - INFO - Chain [1] start processing

02:11:59 - cmdstanpy - INFO - Chain [1] done processing

02:12:00 - cmdstanpy - INFO - Chain [1] start processing

02:12:00 - cmdstanpy - INFO - Chain [1] done processing

02:12:01 - cmdstanpy - INFO - Chain [1] start processing

02:12:01 - cmdstanpy - INFO - Chain [1] done processing

02:12:01 - cmdstanpy - INFO - Chain [1] start processing

02:12:02 - cmdstanpy - INFO - Chain [1] done processing

02:12:03 - cmdstanpy - INFO - Chain [1] start processing

02:12:04 - cmdstanpy - INFO - Chain [1] done processing

02:12:04 - cmdstanpy - INFO - Chain [1] start processing

02:12:05 - cmdstanpy - INFO - Chain [1] done processing

02:12:05 - cmdstanpy - INFO - Chain [1] start processing

02:12:06 - cmdstanpy - INFO - Chain [1] done processing

02:12:06 - cmdstanpy - INFO - Chain [1] start processing

02:12:07 - cmdstanpy - INFO - Chain [1] done processing

02:12:07 - cmdstanpy - INFO - Chain [1] start processing

02:12:08 - cmdstanpy - INFO - Chain [1] done processing

02:12:08 - cmdstanpy - INFO - Chain [1] start processing

02:12:09 - cmdstanpy - INFO - Chain [1] done processing

02:12:10 - cmdstanpy - INFO - Chain [1] start processing

02:12:10 - cmdstanpy - INFO - Chain [1] done processing

02:12:11 - cmdstanpy - INFO - Chain [1] start processing

02:12:11 - cmdstanpy - INFO - Chain [1] done processing

02:12:12 - cmdstanpy - INFO - Chain [1] start processing

02:12:12 - cmdstanpy - INFO - Chain [1] done processing

02:12:13 - cmdstanpy - INFO - Chain [1] start processing

02:12:13 - cmdstanpy - INFO - Chain [1] done processing

02:12:14 - cmdstanpy - INFO - Chain [1] start processing

02:12:14 - cmdstanpy - INFO - Chain [1] done processing

02:12:15 - cmdstanpy - INFO - Chain [1] start processing

02:12:16 - cmdstanpy - INFO - Chain [1] done processing

02:12:16 - cmdstanpy - INFO - Chain [1] start processing

02:12:17 - cmdstanpy - INFO - Chain [1] done processing

02:12:17 - cmdstanpy - INFO - Chain [1] start processing

02:12:18 - cmdstanpy - INFO - Chain [1] done processing

02:12:18 - cmdstanpy - INFO - Chain [1] start processing

02:12:19 - cmdstanpy - INFO - Chain [1] done processing

02:12:19 - cmdstanpy - INFO - Chain [1] start processing

02:12:20 - cmdstanpy - INFO - Chain [1] done processing

02:12:21 - cmdstanpy - INFO - Chain [1] start processing

02:12:21 - cmdstanpy - INFO - Chain [1] done processing

02:12:22 - cmdstanpy - INFO - Chain [1] start processing

02:12:22 - cmdstanpy - INFO - Chain [1] done processing

02:12:23 - cmdstanpy - INFO - Chain [1] start processing

02:12:23 - cmdstanpy - INFO - Chain [1] done processing

02:12:24 - cmdstanpy - INFO - Chain [1] start processing

02:12:24 - cmdstanpy - INFO - Chain [1] done processing

02:12:25 - cmdstanpy - INFO - Chain [1] start processing

02:12:25 - cmdstanpy - INFO - Chain [1] done processing

02:12:26 - cmdstanpy - INFO - Chain [1] start processing

02:12:26 - cmdstanpy - INFO - Chain [1] done processing

02:12:26 - cmdstanpy - INFO - Chain [1] start processing

02:12:27 - cmdstanpy - INFO - Chain [1] done processing

02:12:28 - cmdstanpy - INFO - Chain [1] start processing

02:12:28 - cmdstanpy - INFO - Chain [1] done processing

02:12:28 - cmdstanpy - INFO - Chain [1] start processing

02:12:29 - cmdstanpy - INFO - Chain [1] done processing

02:12:30 - cmdstanpy - INFO - Chain [1] start processing

02:12:30 - cmdstanpy - INFO - Chain [1] done processing

02:12:31 - cmdstanpy - INFO - Chain [1] start processing

02:12:31 - cmdstanpy - INFO - Chain [1] done processing

02:12:32 - cmdstanpy - INFO - Chain [1] start processing

02:12:32 - cmdstanpy - INFO - Chain [1] done processing

02:12:33 - cmdstanpy - INFO - Chain [1] start processing

02:12:33 - cmdstanpy - INFO - Chain [1] done processing

02:12:34 - cmdstanpy - INFO - Chain [1] start processing

02:12:35 - cmdstanpy - INFO - Chain [1] done processing

02:12:35 - cmdstanpy - INFO - Chain [1] start processing

02:12:36 - cmdstanpy - INFO - Chain [1] done processing

02:12:36 - cmdstanpy - INFO - Chain [1] start processing

02:12:37 - cmdstanpy - INFO - Chain [1] done processing

02:12:37 - cmdstanpy - INFO - Chain [1] start processing

02:12:38 - cmdstanpy - INFO - Chain [1] done processing

02:12:39 - cmdstanpy - INFO - Chain [1] start processing

02:12:39 - cmdstanpy - INFO - Chain [1] done processing

02:12:40 - cmdstanpy - INFO - Chain [1] start processing

02:12:41 - cmdstanpy - INFO - Chain [1] done processing

02:12:41 - cmdstanpy - INFO - Chain [1] start processing

02:12:41 - cmdstanpy - INFO - Chain [1] done processing

02:12:42 - cmdstanpy - INFO - Chain [1] start processing

02:12:43 - cmdstanpy - INFO - Chain [1] done processing

02:12:43 - cmdstanpy - INFO - Chain [1] start processing

02:12:44 - cmdstanpy - INFO - Chain [1] done processing

02:12:44 - cmdstanpy - INFO - Chain [1] start processing

02:12:45 - cmdstanpy - INFO - Chain [1] done processing

02:12:46 - cmdstanpy - INFO - Chain [1] start processing

02:12:46 - cmdstanpy - INFO - Chain [1] done processing

02:12:47 - cmdstanpy - INFO - Chain [1] start processing

02:12:47 - cmdstanpy - INFO - Chain [1] done processing

02:12:48 - cmdstanpy - INFO - Chain [1] start processing

02:12:48 - cmdstanpy - INFO - Chain [1] done processing

02:12:49 - cmdstanpy - INFO - Chain [1] start processing

02:12:49 - cmdstanpy - INFO - Chain [1] done processing

02:12:50 - cmdstanpy - INFO - Chain [1] start processing

02:12:51 - cmdstanpy - INFO - Chain [1] done processing

02:12:51 - cmdstanpy - INFO - Chain [1] start processing

02:12:52 - cmdstanpy - INFO - Chain [1] done processing

02:12:52 - cmdstanpy - INFO - Chain [1] start processing

02:12:53 - cmdstanpy - INFO - Chain [1] done processing

02:12:53 - cmdstanpy - INFO - Chain [1] start processing

02:12:54 - cmdstanpy - INFO - Chain [1] done processing

02:12:55 - cmdstanpy - INFO - Chain [1] start processing

02:12:56 - cmdstanpy - INFO - Chain [1] done processing

02:12:57 - cmdstanpy - INFO - Chain [1] start processing

02:12:58 - cmdstanpy - INFO - Chain [1] done processing

02:12:59 - cmdstanpy - INFO - Chain [1] start processing

02:13:00 - cmdstanpy - INFO - Chain [1] done processing

02:13:00 - cmdstanpy - INFO - Chain [1] start processing

02:13:01 - cmdstanpy - INFO - Chain [1] done processing

02:13:02 - cmdstanpy - INFO - Chain [1] start processing

02:13:03 - cmdstanpy - INFO - Chain [1] done processing

02:13:03 - cmdstanpy - INFO - Chain [1] start processing

02:13:04 - cmdstanpy - INFO - Chain [1] done processing

02:13:04 - cmdstanpy - INFO - Chain [1] start processing

02:13:06 - cmdstanpy - INFO - Chain [1] done processing

02:13:06 - cmdstanpy - INFO - Chain [1] start processing

02:13:07 - cmdstanpy - INFO - Chain [1] done processing

02:13:08 - cmdstanpy - INFO - Chain [1] start processing

02:13:09 - cmdstanpy - INFO - Chain [1] done processing

02:13:09 - cmdstanpy - INFO - Chain [1] start processing

02:13:10 - cmdstanpy - INFO - Chain [1] done processing

02:13:11 - cmdstanpy - INFO - Chain [1] start processing

02:13:11 - cmdstanpy - INFO - Chain [1] done processing

02:13:12 - cmdstanpy - INFO - Chain [1] start processing

02:13:13 - cmdstanpy - INFO - Chain [1] done processing

02:13:13 - cmdstanpy - INFO - Chain [1] start processing

02:13:15 - cmdstanpy - INFO - Chain [1] done processing

02:13:15 - cmdstanpy - INFO - Chain [1] start processing

02:13:17 - cmdstanpy - INFO - Chain [1] done processing

02:13:17 - cmdstanpy - INFO - Chain [1] start processing

02:13:18 - cmdstanpy - INFO - Chain [1] done processing

02:13:19 - cmdstanpy - INFO - Chain [1] start processing

02:13:19 - cmdstanpy - INFO - Chain [1] done processing

02:13:19 - cmdstanpy - INFO - Chain [1] start processing

02:13:20 - cmdstanpy - INFO - Chain [1] done processing

02:13:21 - cmdstanpy - INFO - Chain [1] start processing

02:13:22 - cmdstanpy - INFO - Chain [1] done processing

02:13:23 - cmdstanpy - INFO - Chain [1] start processing

02:13:24 - cmdstanpy - INFO - Chain [1] done processing

02:13:24 - cmdstanpy - INFO - Chain [1] start processing

02:13:25 - cmdstanpy - INFO - Chain [1] done processing

02:13:26 - cmdstanpy - INFO - Chain [1] start processing

02:13:27 - cmdstanpy - INFO - Chain [1] done processing

02:13:28 - cmdstanpy - INFO - Chain [1] start processing

02:13:28 - cmdstanpy - INFO - Chain [1] done processing

02:13:29 - cmdstanpy - INFO - Chain [1] start processing

02:13:29 - cmdstanpy - INFO - Chain [1] done processing

02:13:30 - cmdstanpy - INFO - Chain [1] start processing

02:13:31 - cmdstanpy - INFO - Chain [1] done processing

02:13:32 - cmdstanpy - INFO - Chain [1] start processing

02:13:34 - cmdstanpy - INFO - Chain [1] done processing

02:13:34 - cmdstanpy - INFO - Chain [1] start processing

02:13:35 - cmdstanpy - INFO - Chain [1] done processing

02:13:36 - cmdstanpy - INFO - Chain [1] start processing

02:13:37 - cmdstanpy - INFO - Chain [1] done processing

02:13:38 - cmdstanpy - INFO - Chain [1] start processing

02:13:38 - cmdstanpy - INFO - Chain [1] done processing

02:13:39 - cmdstanpy - INFO - Chain [1] start processing

02:13:40 - cmdstanpy - INFO - Chain [1] done processing

02:13:40 - cmdstanpy - INFO - Chain [1] start processing

02:13:42 - cmdstanpy - INFO - Chain [1] done processing

02:13:42 - cmdstanpy - INFO - Chain [1] start processing

02:13:44 - cmdstanpy - INFO - Chain [1] done processing

02:13:44 - cmdstanpy - INFO - Chain [1] start processing

02:13:45 - cmdstanpy - INFO - Chain [1] done processing

02:13:46 - cmdstanpy - INFO - Chain [1] start processing

02:13:48 - cmdstanpy - INFO - Chain [1] done processing

02:13:48 - cmdstanpy - INFO - Chain [1] start processing

02:13:49 - cmdstanpy - INFO - Chain [1] done processing

02:13:49 - cmdstanpy - INFO - Chain [1] start processing

02:13:50 - cmdstanpy - INFO - Chain [1] done processing

02:13:51 - cmdstanpy - INFO - Chain [1] start processing

02:13:52 - cmdstanpy - INFO - Chain [1] done processing

02:13:52 - cmdstanpy - INFO - Chain [1] start processing

02:13:54 - cmdstanpy - INFO - Chain [1] done processing

02:13:54 - cmdstanpy - INFO - Chain [1] start processing

02:13:55 - cmdstanpy - INFO - Chain [1] done processing

02:13:56 - cmdstanpy - INFO - Chain [1] start processing

02:13:57 - cmdstanpy - INFO - Chain [1] done processing

02:13:58 - cmdstanpy - INFO - Chain [1] start processing

02:13:58 - cmdstanpy - INFO - Chain [1] done processing

02:13:59 - cmdstanpy - INFO - Chain [1] start processing

02:14:00 - cmdstanpy - INFO - Chain [1] done processing

02:14:01 - cmdstanpy - INFO - Chain [1] start processing

02:14:01 - cmdstanpy - INFO - Chain [1] done processing

02:14:02 - cmdstanpy - INFO - Chain [1] start processing

02:14:03 - cmdstanpy - INFO - Chain [1] done processing

02:14:03 - cmdstanpy - INFO - Chain [1] start processing

02:14:05 - cmdstanpy - INFO - Chain [1] done processing

02:14:05 - cmdstanpy - INFO - Chain [1] start processing

02:14:06 - cmdstanpy - INFO - Chain [1] done processing

02:14:07 - cmdstanpy - INFO - Chain [1] start processing

02:14:07 - cmdstanpy - INFO - Chain [1] done processing

02:14:08 - cmdstanpy - INFO - Chain [1] start processing

02:14:08 - cmdstanpy - INFO - Chain [1] done processing

02:14:09 - cmdstanpy - INFO - Chain [1] start processing

02:14:10 - cmdstanpy - INFO - Chain [1] done processing

02:14:11 - cmdstanpy - INFO - Chain [1] start processing

02:14:12 - cmdstanpy - INFO - Chain [1] done processing

02:14:13 - cmdstanpy - INFO - Chain [1] start processing

02:14:14 - cmdstanpy - INFO - Chain [1] done processing

02:14:14 - cmdstanpy - INFO - Chain [1] start processing

02:14:16 - cmdstanpy - INFO - Chain [1] done processing

02:14:16 - cmdstanpy - INFO - Chain [1] start processing

02:14:17 - cmdstanpy - INFO - Chain [1] done processing

02:14:18 - cmdstanpy - INFO - Chain [1] start processing

02:14:19 - cmdstanpy - INFO - Chain [1] done processing

02:14:19 - cmdstanpy - INFO - Chain [1] start processing

02:14:21 - cmdstanpy - INFO - Chain [1] done processing

02:14:21 - cmdstanpy - INFO - Chain [1] start processing

02:14:23 - cmdstanpy - INFO - Chain [1] done processing

02:14:23 - cmdstanpy - INFO - Chain [1] start processing

02:14:24 - cmdstanpy - INFO - Chain [1] done processing

02:14:24 - cmdstanpy - INFO - Chain [1] start processing

02:14:26 - cmdstanpy - INFO - Chain [1] done processing

02:14:26 - cmdstanpy - INFO - Chain [1] start processing

02:14:27 - cmdstanpy - INFO - Chain [1] done processing

02:14:28 - cmdstanpy - INFO - Chain [1] start processing

02:14:29 - cmdstanpy - INFO - Chain [1] done processing

02:14:29 - cmdstanpy - INFO - Chain [1] start processing

02:14:31 - cmdstanpy - INFO - Chain [1] done processing

02:14:31 - cmdstanpy - INFO - Chain [1] start processing

02:14:33 - cmdstanpy - INFO - Chain [1] done processing

02:14:33 - cmdstanpy - INFO - Chain [1] start processing

02:14:35 - cmdstanpy - INFO - Chain [1] done processing

02:14:35 - cmdstanpy - INFO - Chain [1] start processing

02:14:37 - cmdstanpy - INFO - Chain [1] done processing

02:14:37 - cmdstanpy - INFO - Chain [1] start processing

02:14:38 - cmdstanpy - INFO - Chain [1] done processing

02:14:38 - cmdstanpy - INFO - Chain [1] start processing

02:14:39 - cmdstanpy - INFO - Chain [1] done processing

02:14:39 - cmdstanpy - INFO - Chain [1] start processing

02:14:41 - cmdstanpy - INFO - Chain [1] done processing

02:14:41 - cmdstanpy - INFO - Chain [1] start processing

02:14:43 - cmdstanpy - INFO - Chain [1] done processing

02:14:43 - cmdstanpy - INFO - Chain [1] start processing

02:14:45 - cmdstanpy - INFO - Chain [1] done processing

02:14:45 - cmdstanpy - INFO - Chain [1] start processing

02:14:47 - cmdstanpy - INFO - Chain [1] done processing

02:14:47 - cmdstanpy - INFO - Chain [1] start processing

02:14:49 - cmdstanpy - INFO - Chain [1] done processing

02:14:49 - cmdstanpy - INFO - Chain [1] start processing

02:14:50 - cmdstanpy - INFO - Chain [1] done processing

02:14:50 - cmdstanpy - INFO - Chain [1] start processing

02:14:51 - cmdstanpy - INFO - Chain [1] done processing

02:14:52 - cmdstanpy - INFO - Chain [1] start processing

02:14:54 - cmdstanpy - INFO - Chain [1] done processing

02:14:54 - cmdstanpy - INFO - Chain [1] start processing

02:14:56 - cmdstanpy - INFO - Chain [1] done processing

02:14:56 - cmdstanpy - INFO - Chain [1] start processing

02:14:58 - cmdstanpy - INFO - Chain [1] done processing

02:14:58 - cmdstanpy - INFO - Chain [1] start processing

02:15:01 - cmdstanpy - INFO - Chain [1] done processing

02:15:01 - cmdstanpy - INFO - Chain [1] start processing

02:15:02 - cmdstanpy - INFO - Chain [1] done processing

02:15:03 - cmdstanpy - INFO - Chain [1] start processing

02:15:04 - cmdstanpy - INFO - Chain [1] done processing

02:15:05 - cmdstanpy - INFO - Chain [1] start processing

02:15:07 - cmdstanpy - INFO - Chain [1] done processing

02:15:07 - cmdstanpy - INFO - Chain [1] start processing

02:15:09 - cmdstanpy - INFO - Chain [1] done processing

02:15:09 - cmdstanpy - INFO - Chain [1] start processing

02:15:11 - cmdstanpy - INFO - Chain [1] done processing

02:15:11 - cmdstanpy - INFO - Chain [1] start processing

02:15:14 - cmdstanpy - INFO - Chain [1] done processing

02:15:15 - cmdstanpy - INFO - Chain [1] start processing

02:15:16 - cmdstanpy - INFO - Chain [1] done processing

02:15:17 - cmdstanpy - INFO - Chain [1] start processing

02:15:18 - cmdstanpy - INFO - Chain [1] done processing

02:15:18 - cmdstanpy - INFO - Chain [1] start processing

02:15:20 - cmdstanpy - INFO - Chain [1] done processing

02:15:21 - cmdstanpy - INFO - Chain [1] start processing

02:15:23 - cmdstanpy - INFO - Chain [1] done processing

02:15:23 - cmdstanpy - INFO - Chain [1] start processing

02:15:25 - cmdstanpy - INFO - Chain [1] done processing

02:15:25 - cmdstanpy - INFO - Chain [1] start processing

02:15:27 - cmdstanpy - INFO - Chain [1] done processing

02:15:27 - cmdstanpy - INFO - Chain [1] start processing

02:15:29 - cmdstanpy - INFO - Chain [1] done processing

02:15:29 - cmdstanpy - INFO - Chain [1] start processing

02:15:31 - cmdstanpy - INFO - Chain [1] done processing

02:15:31 - cmdstanpy - INFO - Chain [1] start processing

02:15:33 - cmdstanpy - INFO - Chain [1] done processing

02:15:33 - cmdstanpy - INFO - Chain [1] start processing

02:15:36 - cmdstanpy - INFO - Chain [1] done processing

02:15:36 - cmdstanpy - INFO - Chain [1] start processing

02:15:39 - cmdstanpy - INFO - Chain [1] done processing

02:15:39 - cmdstanpy - INFO - Chain [1] start processing

02:15:41 - cmdstanpy - INFO - Chain [1] done processing

02:15:41 - cmdstanpy - INFO - Chain [1] start processing

02:15:43 - cmdstanpy - INFO - Chain [1] done processing

02:15:44 - cmdstanpy - INFO - Chain [1] start processing

02:15:45 - cmdstanpy - INFO - Chain [1] done processing

02:15:45 - cmdstanpy - INFO - Chain [1] start processing

02:15:47 - cmdstanpy - INFO - Chain [1] done processing

02:15:48 - cmdstanpy - INFO - Chain [1] start processing

02:15:50 - cmdstanpy - INFO - Chain [1] done processing

02:15:51 - cmdstanpy - INFO - Chain [1] start processing

02:15:53 - cmdstanpy - INFO - Chain [1] done processing

02:15:53 - cmdstanpy - INFO - Chain [1] start processing

02:15:55 - cmdstanpy - INFO - Chain [1] done processing

02:15:56 - cmdstanpy - INFO - Chain [1] start processing

02:15:57 - cmdstanpy - INFO - Chain [1] done processing

02:15:57 - cmdstanpy - INFO - Chain [1] start processing

02:15:59 - cmdstanpy - INFO - Chain [1] done processing

02:15:59 - cmdstanpy - INFO - Chain [1] start processing

02:16:02 - cmdstanpy - INFO - Chain [1] done processing

02:16:03 - cmdstanpy - INFO - Chain [1] start processing

02:16:04 - cmdstanpy - INFO - Chain [1] done processing

02:16:05 - cmdstanpy - INFO - Chain [1] start processing

02:16:07 - cmdstanpy - INFO - Chain [1] done processing

02:16:07 - cmdstanpy - INFO - Chain [1] start processing

02:16:09 - cmdstanpy - INFO - Chain [1] done processing

02:16:09 - cmdstanpy - INFO - Chain [1] start processing

02:16:11 - cmdstanpy - INFO - Chain [1] done processing

02:16:12 - cmdstanpy - INFO - Chain [1] start processing

02:16:13 - cmdstanpy - INFO - Chain [1] done processing

02:16:14 - cmdstanpy - INFO - Chain [1] start processing

02:16:16 - cmdstanpy - INFO - Chain [1] done processing

02:16:16 - cmdstanpy - INFO - Chain [1] start processing

02:16:17 - cmdstanpy - INFO - Chain [1] done processing

02:16:18 - cmdstanpy - INFO - Chain [1] start processing

02:16:20 - cmdstanpy - INFO - Chain [1] done processing

02:16:20 - cmdstanpy - INFO - Chain [1] start processing

02:16:23 - cmdstanpy - INFO - Chain [1] done processing

02:16:23 - cmdstanpy - INFO - Chain [1] start processing

02:16:25 - cmdstanpy - INFO - Chain [1] done processing

02:16:26 - cmdstanpy - INFO - Chain [1] start processing

02:16:27 - cmdstanpy - INFO - Chain [1] done processing

02:16:27 - cmdstanpy - INFO - Chain [1] start processing

02:16:30 - cmdstanpy - INFO - Chain [1] done processing

02:16:30 - cmdstanpy - INFO - Chain [1] start processing

02:16:32 - cmdstanpy - INFO - Chain [1] done processing

02:16:32 - cmdstanpy - INFO - Chain [1] start processing

02:16:35 - cmdstanpy - INFO - Chain [1] done processing

02:16:35 - cmdstanpy - INFO - Chain [1] start processing

02:16:37 - cmdstanpy - INFO - Chain [1] done processing

02:16:37 - cmdstanpy - INFO - Chain [1] start processing

02:16:39 - cmdstanpy - INFO - Chain [1] done processing

02:16:40 - cmdstanpy - INFO - Chain [1] start processing

02:16:42 - cmdstanpy - INFO - Chain [1] done processing

02:16:42 - cmdstanpy - INFO - Chain [1] start processing

02:16:45 - cmdstanpy - INFO - Chain [1] done processing

02:16:45 - cmdstanpy - INFO - Chain [1] start processing

02:16:47 - cmdstanpy - INFO - Chain [1] done processing

02:16:48 - cmdstanpy - INFO - Chain [1] start processing

02:16:50 - cmdstanpy - INFO - Chain [1] done processing

02:16:50 - cmdstanpy - INFO - Chain [1] start processing

02:16:53 - cmdstanpy - INFO - Chain [1] done processing

02:16:53 - cmdstanpy - INFO - Chain [1] start processing

02:16:55 - cmdstanpy - INFO - Chain [1] done processing

02:16:56 - cmdstanpy - INFO - Chain [1] start processing

02:16:58 - cmdstanpy - INFO - Chain [1] done processing

02:16:58 - cmdstanpy - INFO - Chain [1] start processing

02:17:01 - cmdstanpy - INFO - Chain [1] done processing

02:17:01 - cmdstanpy - INFO - Chain [1] start processing

02:17:03 - cmdstanpy - INFO - Chain [1] done processing

02:17:03 - cmdstanpy - INFO - Chain [1] start processing

02:17:06 - cmdstanpy - INFO - Chain [1] done processing

02:17:06 - cmdstanpy - INFO - Chain [1] start processing

02:17:08 - cmdstanpy - INFO - Chain [1] done processing

02:17:09 - cmdstanpy - INFO - Chain [1] start processing

02:17:11 - cmdstanpy - INFO - Chain [1] done processing

02:17:11 - cmdstanpy - INFO - Chain [1] start processing

02:17:14 - cmdstanpy - INFO - Chain [1] done processing

02:17:14 - cmdstanpy - INFO - Chain [1] start processing

02:17:16 - cmdstanpy - INFO - Chain [1] done processing

02:17:16 - cmdstanpy - INFO - Chain [1] start processing

02:17:18 - cmdstanpy - INFO - Chain [1] done processing

02:17:18 - cmdstanpy - INFO - Chain [1] start processing

02:17:20 - cmdstanpy - INFO - Chain [1] done processing

02:17:21 - cmdstanpy - INFO - Chain [1] start processing

02:17:23 - cmdstanpy - INFO - Chain [1] done processing

02:17:23 - cmdstanpy - INFO - Chain [1] start processing

02:17:25 - cmdstanpy - INFO - Chain [1] done processing

02:17:26 - cmdstanpy - INFO - Chain [1] start processing

02:17:28 - cmdstanpy - INFO - Chain [1] done processing

02:17:28 - cmdstanpy - INFO - Chain [1] start processing

02:17:30 - cmdstanpy - INFO - Chain [1] done processing

02:17:30 - cmdstanpy - INFO - Chain [1] start processing

02:17:32 - cmdstanpy - INFO - Chain [1] done processing

02:17:33 - cmdstanpy - INFO - Chain [1] start processing

02:17:34 - cmdstanpy - INFO - Chain [1] done processing

02:17:35 - cmdstanpy - INFO - Chain [1] start processing

02:17:37 - cmdstanpy - INFO - Chain [1] done processing

02:17:37 - cmdstanpy - INFO - Chain [1] start processing

02:17:39 - cmdstanpy - INFO - Chain [1] done processing

02:17:39 - cmdstanpy - INFO - Chain [1] start processing

02:17:41 - cmdstanpy - INFO - Chain [1] done processing

02:17:41 - cmdstanpy - INFO - Chain [1] start processing

02:17:43 - cmdstanpy - INFO - Chain [1] done processing

02:17:43 - cmdstanpy - INFO - Chain [1] start processing

02:17:45 - cmdstanpy - INFO - Chain [1] done processing

02:17:46 - cmdstanpy - INFO - Chain [1] start processing

02:17:48 - cmdstanpy - INFO - Chain [1] done processing

02:17:48 - cmdstanpy - INFO - Chain [1] start processing

02:17:51 - cmdstanpy - INFO - Chain [1] done processing

02:17:51 - cmdstanpy - INFO - Chain [1] start processing

02:17:53 - cmdstanpy - INFO - Chain [1] done processing

02:17:54 - cmdstanpy - INFO - Chain [1] start processing

02:17:56 - cmdstanpy - INFO - Chain [1] done processing

02:17:57 - cmdstanpy - INFO - Chain [1] start processing

02:17:58 - cmdstanpy - INFO - Chain [1] done processing

02:17:59 - cmdstanpy - INFO - Chain [1] start processing

02:18:01 - cmdstanpy - INFO - Chain [1] done processing

02:18:01 - cmdstanpy - INFO - Chain [1] start processing

02:18:03 - cmdstanpy - INFO - Chain [1] done processing

02:18:03 - cmdstanpy - INFO - Chain [1] start processing

02:18:06 - cmdstanpy - INFO - Chain [1] done processing

02:18:06 - cmdstanpy - INFO - Chain [1] start processing

02:18:08 - cmdstanpy - INFO - Chain [1] done processing

02:18:09 - cmdstanpy - INFO - Chain [1] start processing

02:18:10 - cmdstanpy - INFO - Chain [1] done processing

02:18:10 - cmdstanpy - INFO - Chain [1] start processing

02:18:12 - cmdstanpy - INFO - Chain [1] done processing

02:18:12 - cmdstanpy - INFO - Chain [1] start processing

02:18:14 - cmdstanpy - INFO - Chain [1] done processing

02:18:15 - cmdstanpy - INFO - Chain [1] start processing

02:18:16 - cmdstanpy - INFO - Chain [1] done processing

02:18:17 - cmdstanpy - INFO - Chain [1] start processing

02:18:19 - cmdstanpy - INFO - Chain [1] done processing

02:18:19 - cmdstanpy - INFO - Chain [1] start processing

02:18:21 - cmdstanpy - INFO - Chain [1] done processing

02:18:21 - cmdstanpy - INFO - Chain [1] start processing

02:18:23 - cmdstanpy - INFO - Chain [1] done processing

02:18:24 - cmdstanpy - INFO - Chain [1] start processing

02:18:26 - cmdstanpy - INFO - Chain [1] done processing

02:18:26 - cmdstanpy - INFO - Chain [1] start processing

02:18:28 - cmdstanpy - INFO - Chain [1] done processing

02:18:28 - cmdstanpy - INFO - Chain [1] start processing

02:18:30 - cmdstanpy - INFO - Chain [1] done processing

02:18:31 - cmdstanpy - INFO - Chain [1] start processing

02:18:34 - cmdstanpy - INFO - Chain [1] done processing

02:18:34 - cmdstanpy - INFO - Chain [1] start processing

02:18:37 - cmdstanpy - INFO - Chain [1] done processing

02:18:37 - cmdstanpy - INFO - Chain [1] start processing

02:18:39 - cmdstanpy - INFO - Chain [1] done processing

02:18:39 - cmdstanpy - INFO - Chain [1] start processing

02:18:41 - cmdstanpy - INFO - Chain [1] done processing

02:18:41 - cmdstanpy - INFO - Chain [1] start processing

02:18:43 - cmdstanpy - INFO - Chain [1] done processing

02:18:44 - cmdstanpy - INFO - Chain [1] start processing

02:18:46 - cmdstanpy - INFO - Chain [1] done processing

02:18:46 - cmdstanpy - INFO - Chain [1] start processing

02:18:48 - cmdstanpy - INFO - Chain [1] done processing

02:18:49 - cmdstanpy - INFO - Chain [1] start processing

02:18:51 - cmdstanpy - INFO - Chain [1] done processing

02:18:51 - cmdstanpy - INFO - Chain [1] start processing

02:18:54 - cmdstanpy - INFO - Chain [1] done processing

02:18:54 - cmdstanpy - INFO - Chain [1] start processing

02:18:56 - cmdstanpy - INFO - Chain [1] done processing

02:18:56 - cmdstanpy - INFO - Chain [1] start processing

02:18:58 - cmdstanpy - INFO - Chain [1] done processing

02:18:59 - cmdstanpy - INFO - Chain [1] start processing

02:19:00 - cmdstanpy - INFO - Chain [1] done processing

02:19:01 - cmdstanpy - INFO - Chain [1] start processing

02:19:03 - cmdstanpy - INFO - Chain [1] done processing

02:19:04 - cmdstanpy - INFO - Chain [1] start processing

02:19:07 - cmdstanpy - INFO - Chain [1] done processing

02:19:07 - cmdstanpy - INFO - Chain [1] start processing

02:19:09 - cmdstanpy - INFO - Chain [1] done processing

02:19:09 - cmdstanpy - INFO - Chain [1] start processing

02:19:11 - cmdstanpy - INFO - Chain [1] done processing

02:19:11 - cmdstanpy - INFO - Chain [1] start processing

02:19:13 - cmdstanpy - INFO - Chain [1] done processing

02:19:14 - cmdstanpy - INFO - Chain [1] start processing

02:19:16 - cmdstanpy - INFO - Chain [1] done processing

02:19:16 - cmdstanpy - INFO - Chain [1] start processing

02:19:18 - cmdstanpy - INFO - Chain [1] done processing

02:19:19 - cmdstanpy - INFO - Chain [1] start processing

02:19:21 - cmdstanpy - INFO - Chain [1] done processing

02:19:22 - cmdstanpy - INFO - Chain [1] start processing

02:19:23 - cmdstanpy - INFO - Chain [1] done processing

02:19:24 - cmdstanpy - INFO - Chain [1] start processing

02:19:26 - cmdstanpy - INFO - Chain [1] done processing

02:19:26 - cmdstanpy - INFO - Chain [1] start processing

02:19:28 - cmdstanpy - INFO - Chain [1] done processing

02:19:28 - cmdstanpy - INFO - Chain [1] start processing

02:19:31 - cmdstanpy - INFO - Chain [1] done processing

02:19:31 - cmdstanpy - INFO - Chain [1] start processing

02:19:33 - cmdstanpy - INFO - Chain [1] done processing

02:19:33 - cmdstanpy - INFO - Chain [1] start processing

02:19:36 - cmdstanpy - INFO - Chain [1] done processing

02:19:36 - cmdstanpy - INFO - Chain [1] start processing

02:19:39 - cmdstanpy - INFO - Chain [1] done processing

02:19:39 - cmdstanpy - INFO - Chain [1] start processing

02:19:42 - cmdstanpy - INFO - Chain [1] done processing

02:19:42 - cmdstanpy - INFO - Chain [1] start processing

02:19:44 - cmdstanpy - INFO - Chain [1] done processing

02:19:44 - cmdstanpy - INFO - Chain [1] start processing

02:19:46 - cmdstanpy - INFO - Chain [1] done processing

02:19:47 - cmdstanpy - INFO - Chain [1] start processing

02:19:49 - cmdstanpy - INFO - Chain [1] done processing

02:19:49 - cmdstanpy - INFO - Chain [1] start processing

02:19:52 - cmdstanpy - INFO - Chain [1] done processing

02:19:52 - cmdstanpy - INFO - Chain [1] start processing

02:19:55 - cmdstanpy - INFO - Chain [1] done processing

02:19:56 - cmdstanpy - INFO - Chain [1] start processing

02:19:58 - cmdstanpy - INFO - Chain [1] done processing

02:19:59 - cmdstanpy - INFO - Chain [1] start processing

02:20:01 - cmdstanpy - INFO - Chain [1] done processing

02:20:01 - cmdstanpy - INFO - Chain [1] start processing

02:20:03 - cmdstanpy - INFO - Chain [1] done processing

02:20:03 - cmdstanpy - INFO - Chain [1] start processing

02:20:06 - cmdstanpy - INFO - Chain [1] done processing

02:20:06 - cmdstanpy - INFO - Chain [1] start processing

02:20:09 - cmdstanpy - INFO - Chain [1] done processing

02:20:10 - cmdstanpy - INFO - Chain [1] start processing

02:20:12 - cmdstanpy - INFO - Chain [1] done processing

02:20:12 - cmdstanpy - INFO - Chain [1] start processing

02:20:14 - cmdstanpy - INFO - Chain [1] done processing

02:20:15 - cmdstanpy - INFO - Chain [1] start processing

02:20:17 - cmdstanpy - INFO - Chain [1] done processing

02:20:17 - cmdstanpy - INFO - Chain [1] start processing

02:20:19 - cmdstanpy - INFO - Chain [1] done processing

02:20:19 - cmdstanpy - INFO - Chain [1] start processing

02:20:21 - cmdstanpy - INFO - Chain [1] done processing

02:20:22 - cmdstanpy - INFO - Chain [1] start processing

02:20:23 - cmdstanpy - INFO - Chain [1] done processing

02:20:24 - cmdstanpy - INFO - Chain [1] start processing

02:20:27 - cmdstanpy - INFO - Chain [1] done processing

02:20:27 - cmdstanpy - INFO - Chain [1] start processing

02:20:29 - cmdstanpy - INFO - Chain [1] done processing

02:20:30 - cmdstanpy - INFO - Chain [1] start processing

02:20:31 - cmdstanpy - INFO - Chain [1] done processing

02:20:32 - cmdstanpy - INFO - Chain [1] start processing

02:20:34 - cmdstanpy - INFO - Chain [1] done processing

02:20:34 - cmdstanpy - INFO - Chain [1] start processing

02:20:37 - cmdstanpy - INFO - Chain [1] done processing

02:20:38 - cmdstanpy - INFO - Chain [1] start processing

02:20:41 - cmdstanpy - INFO - Chain [1] done processing

h=3: Prophet cps elegido 0.5
h= 3 Paseo aleatorio  [cpu]    0.0 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

h= 3 ARIMA            [cpu]   62.0 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

h= 3 VAR              [cpu]    0.9 s

02:21:44 - cmdstanpy - INFO - Chain [1] start processing

02:21:46 - cmdstanpy - INFO - Chain [1] done processing

02:21:46 - cmdstanpy - INFO - Chain [1] start processing

02:21:48 - cmdstanpy - INFO - Chain [1] done processing

02:21:49 - cmdstanpy - INFO - Chain [1] start processing

02:21:51 - cmdstanpy - INFO - Chain [1] done processing

02:21:51 - cmdstanpy - INFO - Chain [1] start processing

02:21:54 - cmdstanpy - INFO - Chain [1] done processing

02:21:54 - cmdstanpy - INFO - Chain [1] start processing

02:21:56 - cmdstanpy - INFO - Chain [1] done processing

02:21:56 - cmdstanpy - INFO - Chain [1] start processing

02:21:59 - cmdstanpy - INFO - Chain [1] done processing

02:21:59 - cmdstanpy - INFO - Chain [1] start processing

02:22:02 - cmdstanpy - INFO - Chain [1] done processing

02:22:03 - cmdstanpy - INFO - Chain [1] start processing

02:22:04 - cmdstanpy - INFO - Chain [1] done processing

02:22:04 - cmdstanpy - INFO - Chain [1] start processing

02:22:06 - cmdstanpy - INFO - Chain [1] done processing

02:22:07 - cmdstanpy - INFO - Chain [1] start processing

02:22:08 - cmdstanpy - INFO - Chain [1] done processing

02:22:09 - cmdstanpy - INFO - Chain [1] start processing

02:22:10 - cmdstanpy - INFO - Chain [1] done processing

02:22:11 - cmdstanpy - INFO - Chain [1] start processing

02:22:12 - cmdstanpy - INFO - Chain [1] done processing

02:22:13 - cmdstanpy - INFO - Chain [1] start processing

02:22:14 - cmdstanpy - INFO - Chain [1] done processing

02:22:14 - cmdstanpy - INFO - Chain [1] start processing

02:22:16 - cmdstanpy - INFO - Chain [1] done processing

02:22:16 - cmdstanpy - INFO - Chain [1] start processing

02:22:18 - cmdstanpy - INFO - Chain [1] done processing

02:22:18 - cmdstanpy - INFO - Chain [1] start processing

02:22:20 - cmdstanpy - INFO - Chain [1] done processing

02:22:21 - cmdstanpy - INFO - Chain [1] start processing

02:22:23 - cmdstanpy - INFO - Chain [1] done processing

02:22:24 - cmdstanpy - INFO - Chain [1] start processing

02:22:25 - cmdstanpy - INFO - Chain [1] done processing

02:22:26 - cmdstanpy - INFO - Chain [1] start processing

02:22:28 - cmdstanpy - INFO - Chain [1] done processing

02:22:28 - cmdstanpy - INFO - Chain [1] start processing

02:22:30 - cmdstanpy - INFO - Chain [1] done processing

02:22:30 - cmdstanpy - INFO - Chain [1] start processing

02:22:32 - cmdstanpy - INFO - Chain [1] done processing

02:22:33 - cmdstanpy - INFO - Chain [1] start processing

02:22:34 - cmdstanpy - INFO - Chain [1] done processing

02:22:35 - cmdstanpy - INFO - Chain [1] start processing

02:22:37 - cmdstanpy - INFO - Chain [1] done processing

02:22:38 - cmdstanpy - INFO - Chain [1] start processing

02:22:40 - cmdstanpy - INFO - Chain [1] done processing

02:22:41 - cmdstanpy - INFO - Chain [1] start processing

02:22:44 - cmdstanpy - INFO - Chain [1] done processing

02:22:44 - cmdstanpy - INFO - Chain [1] start processing

02:22:46 - cmdstanpy - INFO - Chain [1] done processing

02:22:46 - cmdstanpy - INFO - Chain [1] start processing

02:22:48 - cmdstanpy - INFO - Chain [1] done processing

02:22:48 - cmdstanpy - INFO - Chain [1] start processing

02:22:51 - cmdstanpy - INFO - Chain [1] done processing

02:22:51 - cmdstanpy - INFO - Chain [1] start processing

02:22:54 - cmdstanpy - INFO - Chain [1] done processing

02:22:54 - cmdstanpy - INFO - Chain [1] start processing

02:22:56 - cmdstanpy - INFO - Chain [1] done processing

02:22:57 - cmdstanpy - INFO - Chain [1] start processing

02:22:58 - cmdstanpy - INFO - Chain [1] done processing

02:22:59 - cmdstanpy - INFO - Chain [1] start processing

02:23:01 - cmdstanpy - INFO - Chain [1] done processing

02:23:01 - cmdstanpy - INFO - Chain [1] start processing

02:23:03 - cmdstanpy - INFO - Chain [1] done processing

02:23:04 - cmdstanpy - INFO - Chain [1] start processing

02:23:06 - cmdstanpy - INFO - Chain [1] done processing

02:23:07 - cmdstanpy - INFO - Chain [1] start processing

02:23:09 - cmdstanpy - INFO - Chain [1] done processing

02:23:10 - cmdstanpy - INFO - Chain [1] start processing

02:23:13 - cmdstanpy - INFO - Chain [1] done processing

02:23:13 - cmdstanpy - INFO - Chain [1] start processing

02:23:16 - cmdstanpy - INFO - Chain [1] done processing

02:23:16 - cmdstanpy - INFO - Chain [1] start processing

02:23:19 - cmdstanpy - INFO - Chain [1] done processing

02:23:20 - cmdstanpy - INFO - Chain [1] start processing

02:23:22 - cmdstanpy - INFO - Chain [1] done processing

02:23:22 - cmdstanpy - INFO - Chain [1] start processing

02:23:24 - cmdstanpy - INFO - Chain [1] done processing

02:23:25 - cmdstanpy - INFO - Chain [1] start processing

02:23:27 - cmdstanpy - INFO - Chain [1] done processing

02:23:28 - cmdstanpy - INFO - Chain [1] start processing

02:23:30 - cmdstanpy - INFO - Chain [1] done processing

02:23:30 - cmdstanpy - INFO - Chain [1] start processing

02:23:33 - cmdstanpy - INFO - Chain [1] done processing

02:23:33 - cmdstanpy - INFO - Chain [1] start processing

02:23:36 - cmdstanpy - INFO - Chain [1] done processing

02:23:36 - cmdstanpy - INFO - Chain [1] start processing

02:23:39 - cmdstanpy - INFO - Chain [1] done processing

02:23:39 - cmdstanpy - INFO - Chain [1] start processing

02:23:41 - cmdstanpy - INFO - Chain [1] done processing

02:23:42 - cmdstanpy - INFO - Chain [1] start processing

02:23:44 - cmdstanpy - INFO - Chain [1] done processing

02:23:45 - cmdstanpy - INFO - Chain [1] start processing

02:23:47 - cmdstanpy - INFO - Chain [1] done processing

02:23:47 - cmdstanpy - INFO - Chain [1] start processing

02:23:49 - cmdstanpy - INFO - Chain [1] done processing

02:23:49 - cmdstanpy - INFO - Chain [1] start processing

02:23:52 - cmdstanpy - INFO - Chain [1] done processing

02:23:52 - cmdstanpy - INFO - Chain [1] start processing

02:23:54 - cmdstanpy - INFO - Chain [1] done processing

02:23:55 - cmdstanpy - INFO - Chain [1] start processing

02:23:58 - cmdstanpy - INFO - Chain [1] done processing

02:23:58 - cmdstanpy - INFO - Chain [1] start processing

02:24:00 - cmdstanpy - INFO - Chain [1] done processing

02:24:01 - cmdstanpy - INFO - Chain [1] start processing

02:24:04 - cmdstanpy - INFO - Chain [1] done processing

02:24:04 - cmdstanpy - INFO - Chain [1] start processing

02:24:07 - cmdstanpy - INFO - Chain [1] done processing

02:24:07 - cmdstanpy - INFO - Chain [1] start processing

02:24:10 - cmdstanpy - INFO - Chain [1] done processing

02:24:11 - cmdstanpy - INFO - Chain [1] start processing

02:24:13 - cmdstanpy - INFO - Chain [1] done processing

02:24:13 - cmdstanpy - INFO - Chain [1] start processing

02:24:16 - cmdstanpy - INFO - Chain [1] done processing

02:24:16 - cmdstanpy - INFO - Chain [1] start processing

02:24:18 - cmdstanpy - INFO - Chain [1] done processing

02:24:19 - cmdstanpy - INFO - Chain [1] start processing

02:24:21 - cmdstanpy - INFO - Chain [1] done processing

02:24:22 - cmdstanpy - INFO - Chain [1] start processing

02:24:24 - cmdstanpy - INFO - Chain [1] done processing

02:24:24 - cmdstanpy - INFO - Chain [1] start processing

02:24:26 - cmdstanpy - INFO - Chain [1] done processing

02:24:27 - cmdstanpy - INFO - Chain [1] start processing

02:24:29 - cmdstanpy - INFO - Chain [1] done processing

02:24:29 - cmdstanpy - INFO - Chain [1] start processing

02:24:32 - cmdstanpy - INFO - Chain [1] done processing

02:24:32 - cmdstanpy - INFO - Chain [1] start processing

02:24:35 - cmdstanpy - INFO - Chain [1] done processing

02:24:36 - cmdstanpy - INFO - Chain [1] start processing

02:24:38 - cmdstanpy - INFO - Chain [1] done processing

02:24:38 - cmdstanpy - INFO - Chain [1] start processing

02:24:39 - cmdstanpy - INFO - Chain [1] done processing

02:24:39 - cmdstanpy - INFO - Chain [1] start processing

02:24:39 - cmdstanpy - INFO - Chain [1] done processing

02:24:40 - cmdstanpy - INFO - Chain [1] start processing

02:24:40 - cmdstanpy - INFO - Chain [1] done processing

02:24:40 - cmdstanpy - INFO - Chain [1] start processing

02:24:41 - cmdstanpy - INFO - Chain [1] done processing

02:24:41 - cmdstanpy - INFO - Chain [1] start processing

02:24:41 - cmdstanpy - INFO - Chain [1] done processing

02:24:41 - cmdstanpy - INFO - Chain [1] start processing

02:24:42 - cmdstanpy - INFO - Chain [1] done processing

02:24:42 - cmdstanpy - INFO - Chain [1] start processing

02:24:42 - cmdstanpy - INFO - Chain [1] done processing

02:24:43 - cmdstanpy - INFO - Chain [1] start processing

02:24:43 - cmdstanpy - INFO - Chain [1] done processing

02:24:43 - cmdstanpy - INFO - Chain [1] start processing

02:24:43 - cmdstanpy - INFO - Chain [1] done processing

02:24:44 - cmdstanpy - INFO - Chain [1] start processing

02:24:44 - cmdstanpy - INFO - Chain [1] done processing

02:24:44 - cmdstanpy - INFO - Chain [1] start processing

02:24:45 - cmdstanpy - INFO - Chain [1] done processing

02:24:45 - cmdstanpy - INFO - Chain [1] start processing

02:24:45 - cmdstanpy - INFO - Chain [1] done processing

02:24:46 - cmdstanpy - INFO - Chain [1] start processing

02:24:46 - cmdstanpy - INFO - Chain [1] done processing

02:24:46 - cmdstanpy - INFO - Chain [1] start processing

02:24:46 - cmdstanpy - INFO - Chain [1] done processing

02:24:47 - cmdstanpy - INFO - Chain [1] start processing

02:24:47 - cmdstanpy - INFO - Chain [1] done processing

02:24:47 - cmdstanpy - INFO - Chain [1] start processing

02:24:48 - cmdstanpy - INFO - Chain [1] done processing

02:24:48 - cmdstanpy - INFO - Chain [1] start processing

02:24:48 - cmdstanpy - INFO - Chain [1] done processing

02:24:48 - cmdstanpy - INFO - Chain [1] start processing

02:24:49 - cmdstanpy - INFO - Chain [1] done processing

02:24:49 - cmdstanpy - INFO - Chain [1] start processing

02:24:49 - cmdstanpy - INFO - Chain [1] done processing

02:24:50 - cmdstanpy - INFO - Chain [1] start processing

02:24:50 - cmdstanpy - INFO - Chain [1] done processing

02:24:50 - cmdstanpy - INFO - Chain [1] start processing

02:24:51 - cmdstanpy - INFO - Chain [1] done processing

02:24:51 - cmdstanpy - INFO - Chain [1] start processing

02:24:51 - cmdstanpy - INFO - Chain [1] done processing

02:24:52 - cmdstanpy - INFO - Chain [1] start processing

02:24:52 - cmdstanpy - INFO - Chain [1] done processing

02:24:52 - cmdstanpy - INFO - Chain [1] start processing

02:24:52 - cmdstanpy - INFO - Chain [1] done processing

02:24:53 - cmdstanpy - INFO - Chain [1] start processing

02:24:53 - cmdstanpy - INFO - Chain [1] done processing

02:24:53 - cmdstanpy - INFO - Chain [1] start processing

02:24:54 - cmdstanpy - INFO - Chain [1] done processing

02:24:54 - cmdstanpy - INFO - Chain [1] start processing

02:24:54 - cmdstanpy - INFO - Chain [1] done processing

02:24:55 - cmdstanpy - INFO - Chain [1] start processing

02:24:55 - cmdstanpy - INFO - Chain [1] done processing

02:24:55 - cmdstanpy - INFO - Chain [1] start processing

02:24:55 - cmdstanpy - INFO - Chain [1] done processing

02:24:56 - cmdstanpy - INFO - Chain [1] start processing

02:24:56 - cmdstanpy - INFO - Chain [1] done processing

02:24:57 - cmdstanpy - INFO - Chain [1] start processing

02:24:57 - cmdstanpy - INFO - Chain [1] done processing

02:24:57 - cmdstanpy - INFO - Chain [1] start processing

02:24:57 - cmdstanpy - INFO - Chain [1] done processing

02:24:58 - cmdstanpy - INFO - Chain [1] start processing

02:24:58 - cmdstanpy - INFO - Chain [1] done processing

02:24:58 - cmdstanpy - INFO - Chain [1] start processing

02:24:59 - cmdstanpy - INFO - Chain [1] done processing

02:24:59 - cmdstanpy - INFO - Chain [1] start processing

02:24:59 - cmdstanpy - INFO - Chain [1] done processing

02:25:00 - cmdstanpy - INFO - Chain [1] start processing

02:25:00 - cmdstanpy - INFO - Chain [1] done processing

02:25:00 - cmdstanpy - INFO - Chain [1] start processing

02:25:00 - cmdstanpy - INFO - Chain [1] done processing

02:25:01 - cmdstanpy - INFO - Chain [1] start processing

02:25:01 - cmdstanpy - INFO - Chain [1] done processing

02:25:01 - cmdstanpy - INFO - Chain [1] start processing

02:25:01 - cmdstanpy - INFO - Chain [1] done processing

02:25:02 - cmdstanpy - INFO - Chain [1] start processing

02:25:02 - cmdstanpy - INFO - Chain [1] done processing

02:25:02 - cmdstanpy - INFO - Chain [1] start processing

02:25:03 - cmdstanpy - INFO - Chain [1] done processing

02:25:03 - cmdstanpy - INFO - Chain [1] start processing

02:25:03 - cmdstanpy - INFO - Chain [1] done processing

02:25:04 - cmdstanpy - INFO - Chain [1] start processing

02:25:04 - cmdstanpy - INFO - Chain [1] done processing

02:25:04 - cmdstanpy - INFO - Chain [1] start processing

02:25:05 - cmdstanpy - INFO - Chain [1] done processing

02:25:05 - cmdstanpy - INFO - Chain [1] start processing

02:25:05 - cmdstanpy - INFO - Chain [1] done processing

02:25:06 - cmdstanpy - INFO - Chain [1] start processing

02:25:06 - cmdstanpy - INFO - Chain [1] done processing

02:25:06 - cmdstanpy - INFO - Chain [1] start processing

02:25:06 - cmdstanpy - INFO - Chain [1] done processing

02:25:07 - cmdstanpy - INFO - Chain [1] start processing

02:25:07 - cmdstanpy - INFO - Chain [1] done processing

02:25:08 - cmdstanpy - INFO - Chain [1] start processing

02:25:08 - cmdstanpy - INFO - Chain [1] done processing

02:25:08 - cmdstanpy - INFO - Chain [1] start processing

02:25:08 - cmdstanpy - INFO - Chain [1] done processing

02:25:09 - cmdstanpy - INFO - Chain [1] start processing

02:25:09 - cmdstanpy - INFO - Chain [1] done processing

02:25:09 - cmdstanpy - INFO - Chain [1] start processing

02:25:09 - cmdstanpy - INFO - Chain [1] done processing

02:25:10 - cmdstanpy - INFO - Chain [1] start processing

02:25:10 - cmdstanpy - INFO - Chain [1] done processing

02:25:11 - cmdstanpy - INFO - Chain [1] start processing

02:25:11 - cmdstanpy - INFO - Chain [1] done processing

02:25:11 - cmdstanpy - INFO - Chain [1] start processing

02:25:11 - cmdstanpy - INFO - Chain [1] done processing

02:25:12 - cmdstanpy - INFO - Chain [1] start processing

02:25:12 - cmdstanpy - INFO - Chain [1] done processing

02:25:12 - cmdstanpy - INFO - Chain [1] start processing

02:25:13 - cmdstanpy - INFO - Chain [1] done processing

02:25:13 - cmdstanpy - INFO - Chain [1] start processing

02:25:13 - cmdstanpy - INFO - Chain [1] done processing

02:25:14 - cmdstanpy - INFO - Chain [1] start processing

02:25:14 - cmdstanpy - INFO - Chain [1] done processing

02:25:14 - cmdstanpy - INFO - Chain [1] start processing

02:25:14 - cmdstanpy - INFO - Chain [1] done processing

02:25:15 - cmdstanpy - INFO - Chain [1] start processing

02:25:15 - cmdstanpy - INFO - Chain [1] done processing

02:25:15 - cmdstanpy - INFO - Chain [1] start processing

02:25:16 - cmdstanpy - INFO - Chain [1] done processing

02:25:16 - cmdstanpy - INFO - Chain [1] start processing

02:25:16 - cmdstanpy - INFO - Chain [1] done processing

02:25:17 - cmdstanpy - INFO - Chain [1] start processing

02:25:17 - cmdstanpy - INFO - Chain [1] done processing

02:25:17 - cmdstanpy - INFO - Chain [1] start processing

02:25:18 - cmdstanpy - INFO - Chain [1] done processing

02:25:18 - cmdstanpy - INFO - Chain [1] start processing

02:25:18 - cmdstanpy - INFO - Chain [1] done processing

02:25:19 - cmdstanpy - INFO - Chain [1] start processing

02:25:19 - cmdstanpy - INFO - Chain [1] done processing

02:25:19 - cmdstanpy - INFO - Chain [1] start processing

02:25:19 - cmdstanpy - INFO - Chain [1] done processing

02:25:20 - cmdstanpy - INFO - Chain [1] start processing

02:25:20 - cmdstanpy - INFO - Chain [1] done processing

02:25:20 - cmdstanpy - INFO - Chain [1] start processing

02:25:20 - cmdstanpy - INFO - Chain [1] done processing

02:25:21 - cmdstanpy - INFO - Chain [1] start processing

02:25:21 - cmdstanpy - INFO - Chain [1] done processing

02:25:22 - cmdstanpy - INFO - Chain [1] start processing

02:25:22 - cmdstanpy - INFO - Chain [1] done processing

02:25:22 - cmdstanpy - INFO - Chain [1] start processing

02:25:22 - cmdstanpy - INFO - Chain [1] done processing

02:25:23 - cmdstanpy - INFO - Chain [1] start processing

02:25:23 - cmdstanpy - INFO - Chain [1] done processing

02:25:23 - cmdstanpy - INFO - Chain [1] start processing

02:25:24 - cmdstanpy - INFO - Chain [1] done processing

02:25:24 - cmdstanpy - INFO - Chain [1] start processing

02:25:24 - cmdstanpy - INFO - Chain [1] done processing

02:25:25 - cmdstanpy - INFO - Chain [1] start processing

02:25:25 - cmdstanpy - INFO - Chain [1] done processing

02:25:25 - cmdstanpy - INFO - Chain [1] start processing

02:25:25 - cmdstanpy - INFO - Chain [1] done processing

02:25:26 - cmdstanpy - INFO - Chain [1] start processing

02:25:26 - cmdstanpy - INFO - Chain [1] done processing

02:25:26 - cmdstanpy - INFO - Chain [1] start processing

02:25:27 - cmdstanpy - INFO - Chain [1] done processing

02:25:27 - cmdstanpy - INFO - Chain [1] start processing

02:25:27 - cmdstanpy - INFO - Chain [1] done processing

02:25:28 - cmdstanpy - INFO - Chain [1] start processing

02:25:28 - cmdstanpy - INFO - Chain [1] done processing

02:25:28 - cmdstanpy - INFO - Chain [1] start processing

02:25:29 - cmdstanpy - INFO - Chain [1] done processing

02:25:29 - cmdstanpy - INFO - Chain [1] start processing

02:25:29 - cmdstanpy - INFO - Chain [1] done processing

02:25:30 - cmdstanpy - INFO - Chain [1] start processing

02:25:30 - cmdstanpy - INFO - Chain [1] done processing

02:25:30 - cmdstanpy - INFO - Chain [1] start processing

02:25:31 - cmdstanpy - INFO - Chain [1] done processing

02:25:31 - cmdstanpy - INFO - Chain [1] start processing

02:25:31 - cmdstanpy - INFO - Chain [1] done processing

02:25:31 - cmdstanpy - INFO - Chain [1] start processing

02:25:32 - cmdstanpy - INFO - Chain [1] done processing

02:25:32 - cmdstanpy - INFO - Chain [1] start processing

02:25:32 - cmdstanpy - INFO - Chain [1] done processing

02:25:33 - cmdstanpy - INFO - Chain [1] start processing

02:25:33 - cmdstanpy - INFO - Chain [1] done processing

02:25:33 - cmdstanpy - INFO - Chain [1] start processing

02:25:33 - cmdstanpy - INFO - Chain [1] done processing

02:25:34 - cmdstanpy - INFO - Chain [1] start processing

02:25:34 - cmdstanpy - INFO - Chain [1] done processing

02:25:35 - cmdstanpy - INFO - Chain [1] start processing

02:25:35 - cmdstanpy - INFO - Chain [1] done processing

02:25:35 - cmdstanpy - INFO - Chain [1] start processing

02:25:35 - cmdstanpy - INFO - Chain [1] done processing

02:25:36 - cmdstanpy - INFO - Chain [1] start processing

02:25:36 - cmdstanpy - INFO - Chain [1] done processing

02:25:36 - cmdstanpy - INFO - Chain [1] start processing

02:25:36 - cmdstanpy - INFO - Chain [1] done processing

02:25:37 - cmdstanpy - INFO - Chain [1] start processing

02:25:37 - cmdstanpy - INFO - Chain [1] done processing

02:25:38 - cmdstanpy - INFO - Chain [1] start processing

02:25:38 - cmdstanpy - INFO - Chain [1] done processing

02:25:38 - cmdstanpy - INFO - Chain [1] start processing

02:25:39 - cmdstanpy - INFO - Chain [1] done processing

02:25:39 - cmdstanpy - INFO - Chain [1] start processing

02:25:39 - cmdstanpy - INFO - Chain [1] done processing

02:25:40 - cmdstanpy - INFO - Chain [1] start processing

02:25:40 - cmdstanpy - INFO - Chain [1] done processing

02:25:40 - cmdstanpy - INFO - Chain [1] start processing

02:25:40 - cmdstanpy - INFO - Chain [1] done processing

02:25:41 - cmdstanpy - INFO - Chain [1] start processing

02:25:41 - cmdstanpy - INFO - Chain [1] done processing

02:25:41 - cmdstanpy - INFO - Chain [1] start processing

02:25:42 - cmdstanpy - INFO - Chain [1] done processing

02:25:42 - cmdstanpy - INFO - Chain [1] start processing

02:25:42 - cmdstanpy - INFO - Chain [1] done processing

02:25:43 - cmdstanpy - INFO - Chain [1] start processing

02:25:43 - cmdstanpy - INFO - Chain [1] done processing

02:25:43 - cmdstanpy - INFO - Chain [1] start processing

02:25:44 - cmdstanpy - INFO - Chain [1] done processing

02:25:44 - cmdstanpy - INFO - Chain [1] start processing

02:25:44 - cmdstanpy - INFO - Chain [1] done processing

02:25:45 - cmdstanpy - INFO - Chain [1] start processing

02:25:45 - cmdstanpy - INFO - Chain [1] done processing

02:25:46 - cmdstanpy - INFO - Chain [1] start processing

02:25:46 - cmdstanpy - INFO - Chain [1] done processing

02:25:46 - cmdstanpy - INFO - Chain [1] start processing

02:25:46 - cmdstanpy - INFO - Chain [1] done processing

02:25:47 - cmdstanpy - INFO - Chain [1] start processing

02:25:47 - cmdstanpy - INFO - Chain [1] done processing

02:25:47 - cmdstanpy - INFO - Chain [1] start processing

02:25:48 - cmdstanpy - INFO - Chain [1] done processing

02:25:48 - cmdstanpy - INFO - Chain [1] start processing

02:25:48 - cmdstanpy - INFO - Chain [1] done processing

02:25:49 - cmdstanpy - INFO - Chain [1] start processing

02:25:49 - cmdstanpy - INFO - Chain [1] done processing

02:25:49 - cmdstanpy - INFO - Chain [1] start processing

02:25:50 - cmdstanpy - INFO - Chain [1] done processing

02:25:50 - cmdstanpy - INFO - Chain [1] start processing

02:25:50 - cmdstanpy - INFO - Chain [1] done processing

02:25:51 - cmdstanpy - INFO - Chain [1] start processing

02:25:51 - cmdstanpy - INFO - Chain [1] done processing

02:25:51 - cmdstanpy - INFO - Chain [1] start processing

02:25:52 - cmdstanpy - INFO - Chain [1] done processing

02:25:52 - cmdstanpy - INFO - Chain [1] start processing

02:25:52 - cmdstanpy - INFO - Chain [1] done processing

02:25:53 - cmdstanpy - INFO - Chain [1] start processing

02:25:53 - cmdstanpy - INFO - Chain [1] done processing

02:25:53 - cmdstanpy - INFO - Chain [1] start processing

02:25:54 - cmdstanpy - INFO - Chain [1] done processing

02:25:54 - cmdstanpy - INFO - Chain [1] start processing

02:25:54 - cmdstanpy - INFO - Chain [1] done processing

02:25:55 - cmdstanpy - INFO - Chain [1] start processing

02:25:55 - cmdstanpy - INFO - Chain [1] done processing

02:25:55 - cmdstanpy - INFO - Chain [1] start processing

02:25:56 - cmdstanpy - INFO - Chain [1] done processing

02:25:56 - cmdstanpy - INFO - Chain [1] start processing

02:25:56 - cmdstanpy - INFO - Chain [1] done processing

02:25:57 - cmdstanpy - INFO - Chain [1] start processing

02:25:57 - cmdstanpy - INFO - Chain [1] done processing

02:25:57 - cmdstanpy - INFO - Chain [1] start processing

02:25:57 - cmdstanpy - INFO - Chain [1] done processing

02:25:58 - cmdstanpy - INFO - Chain [1] start processing

02:25:58 - cmdstanpy - INFO - Chain [1] done processing

02:25:58 - cmdstanpy - INFO - Chain [1] start processing

02:25:59 - cmdstanpy - INFO - Chain [1] done processing

02:25:59 - cmdstanpy - INFO - Chain [1] start processing

02:25:59 - cmdstanpy - INFO - Chain [1] done processing

02:26:00 - cmdstanpy - INFO - Chain [1] start processing

02:26:00 - cmdstanpy - INFO - Chain [1] done processing

02:26:00 - cmdstanpy - INFO - Chain [1] start processing

02:26:01 - cmdstanpy - INFO - Chain [1] done processing

02:26:01 - cmdstanpy - INFO - Chain [1] start processing

02:26:01 - cmdstanpy - INFO - Chain [1] done processing

02:26:02 - cmdstanpy - INFO - Chain [1] start processing

02:26:02 - cmdstanpy - INFO - Chain [1] done processing

02:26:02 - cmdstanpy - INFO - Chain [1] start processing

02:26:03 - cmdstanpy - INFO - Chain [1] done processing

02:26:03 - cmdstanpy - INFO - Chain [1] start processing

02:26:03 - cmdstanpy - INFO - Chain [1] done processing

02:26:04 - cmdstanpy - INFO - Chain [1] start processing

02:26:04 - cmdstanpy - INFO - Chain [1] done processing

02:26:04 - cmdstanpy - INFO - Chain [1] start processing

02:26:04 - cmdstanpy - INFO - Chain [1] done processing

02:26:05 - cmdstanpy - INFO - Chain [1] start processing

02:26:05 - cmdstanpy - INFO - Chain [1] done processing

02:26:05 - cmdstanpy - INFO - Chain [1] start processing

02:26:06 - cmdstanpy - INFO - Chain [1] done processing

02:26:06 - cmdstanpy - INFO - Chain [1] start processing

02:26:06 - cmdstanpy - INFO - Chain [1] done processing

02:26:07 - cmdstanpy - INFO - Chain [1] start processing

02:26:07 - cmdstanpy - INFO - Chain [1] done processing

02:26:07 - cmdstanpy - INFO - Chain [1] start processing

02:26:07 - cmdstanpy - INFO - Chain [1] done processing

02:26:08 - cmdstanpy - INFO - Chain [1] start processing

02:26:08 - cmdstanpy - INFO - Chain [1] done processing

02:26:08 - cmdstanpy - INFO - Chain [1] start processing

02:26:08 - cmdstanpy - INFO - Chain [1] done processing

02:26:09 - cmdstanpy - INFO - Chain [1] start processing

02:26:09 - cmdstanpy - INFO - Chain [1] done processing

02:26:10 - cmdstanpy - INFO - Chain [1] start processing

02:26:10 - cmdstanpy - INFO - Chain [1] done processing

02:26:10 - cmdstanpy - INFO - Chain [1] start processing

02:26:10 - cmdstanpy - INFO - Chain [1] done processing

02:26:11 - cmdstanpy - INFO - Chain [1] start processing

02:26:11 - cmdstanpy - INFO - Chain [1] done processing

h= 3 Prophet          [cpu]  267.4 s

h= 3 Ridge            [cuda]   17.9 s

h= 3 Random Forest    [cuda]  737.6 s

h= 3 XGBoost          [cuda]  637.7 s

02:49:25 - cmdstanpy - INFO - Chain [1] start processing

02:49:25 - cmdstanpy - INFO - Chain [1] done processing

02:49:26 - cmdstanpy - INFO - Chain [1] start processing

02:49:27 - cmdstanpy - INFO - Chain [1] done processing

02:49:27 - cmdstanpy - INFO - Chain [1] start processing

02:49:27 - cmdstanpy - INFO - Chain [1] done processing

02:49:28 - cmdstanpy - INFO - Chain [1] start processing

02:49:29 - cmdstanpy - INFO - Chain [1] done processing

02:49:29 - cmdstanpy - INFO - Chain [1] start processing

02:49:29 - cmdstanpy - INFO - Chain [1] done processing

02:49:30 - cmdstanpy - INFO - Chain [1] start processing

02:49:31 - cmdstanpy - INFO - Chain [1] done processing

02:49:31 - cmdstanpy - INFO - Chain [1] start processing

02:49:32 - cmdstanpy - INFO - Chain [1] done processing

02:49:32 - cmdstanpy - INFO - Chain [1] start processing

02:49:33 - cmdstanpy - INFO - Chain [1] done processing

02:49:33 - cmdstanpy - INFO - Chain [1] start processing

02:49:34 - cmdstanpy - INFO - Chain [1] done processing

02:49:34 - cmdstanpy - INFO - Chain [1] start processing

02:49:35 - cmdstanpy - INFO - Chain [1] done processing

02:49:36 - cmdstanpy - INFO - Chain [1] start processing

02:49:36 - cmdstanpy - INFO - Chain [1] done processing

02:49:37 - cmdstanpy - INFO - Chain [1] start processing

02:49:37 - cmdstanpy - INFO - Chain [1] done processing

02:49:38 - cmdstanpy - INFO - Chain [1] start processing

02:49:38 - cmdstanpy - INFO - Chain [1] done processing

02:49:39 - cmdstanpy - INFO - Chain [1] start processing

02:49:39 - cmdstanpy - INFO - Chain [1] done processing

02:49:40 - cmdstanpy - INFO - Chain [1] start processing

02:49:40 - cmdstanpy - INFO - Chain [1] done processing

02:49:41 - cmdstanpy - INFO - Chain [1] start processing

02:49:42 - cmdstanpy - INFO - Chain [1] done processing

02:49:42 - cmdstanpy - INFO - Chain [1] start processing

02:49:43 - cmdstanpy - INFO - Chain [1] done processing

02:49:43 - cmdstanpy - INFO - Chain [1] start processing

02:49:44 - cmdstanpy - INFO - Chain [1] done processing

02:49:45 - cmdstanpy - INFO - Chain [1] start processing

02:49:45 - cmdstanpy - INFO - Chain [1] done processing

02:49:45 - cmdstanpy - INFO - Chain [1] start processing

02:49:46 - cmdstanpy - INFO - Chain [1] done processing

02:49:47 - cmdstanpy - INFO - Chain [1] start processing

02:49:47 - cmdstanpy - INFO - Chain [1] done processing

02:49:48 - cmdstanpy - INFO - Chain [1] start processing

02:49:48 - cmdstanpy - INFO - Chain [1] done processing

02:49:49 - cmdstanpy - INFO - Chain [1] start processing

02:49:49 - cmdstanpy - INFO - Chain [1] done processing

02:49:50 - cmdstanpy - INFO - Chain [1] start processing

02:49:50 - cmdstanpy - INFO - Chain [1] done processing

02:49:51 - cmdstanpy - INFO - Chain [1] start processing

02:49:51 - cmdstanpy - INFO - Chain [1] done processing

02:49:52 - cmdstanpy - INFO - Chain [1] start processing

02:49:53 - cmdstanpy - INFO - Chain [1] done processing

02:49:53 - cmdstanpy - INFO - Chain [1] start processing

02:49:54 - cmdstanpy - INFO - Chain [1] done processing

02:49:54 - cmdstanpy - INFO - Chain [1] start processing

02:49:55 - cmdstanpy - INFO - Chain [1] done processing

02:49:55 - cmdstanpy - INFO - Chain [1] start processing

02:49:56 - cmdstanpy - INFO - Chain [1] done processing

02:49:56 - cmdstanpy - INFO - Chain [1] start processing

02:49:57 - cmdstanpy - INFO - Chain [1] done processing

02:49:57 - cmdstanpy - INFO - Chain [1] start processing

02:49:58 - cmdstanpy - INFO - Chain [1] done processing

02:49:58 - cmdstanpy - INFO - Chain [1] start processing

02:49:59 - cmdstanpy - INFO - Chain [1] done processing

02:49:59 - cmdstanpy - INFO - Chain [1] start processing

02:50:00 - cmdstanpy - INFO - Chain [1] done processing

02:50:00 - cmdstanpy - INFO - Chain [1] start processing

02:50:01 - cmdstanpy - INFO - Chain [1] done processing

02:50:02 - cmdstanpy - INFO - Chain [1] start processing

02:50:02 - cmdstanpy - INFO - Chain [1] done processing

02:50:03 - cmdstanpy - INFO - Chain [1] start processing

02:50:03 - cmdstanpy - INFO - Chain [1] done processing

02:50:04 - cmdstanpy - INFO - Chain [1] start processing

02:50:04 - cmdstanpy - INFO - Chain [1] done processing

02:50:05 - cmdstanpy - INFO - Chain [1] start processing

02:50:05 - cmdstanpy - INFO - Chain [1] done processing

02:50:06 - cmdstanpy - INFO - Chain [1] start processing

02:50:07 - cmdstanpy - INFO - Chain [1] done processing

02:50:07 - cmdstanpy - INFO - Chain [1] start processing

02:50:08 - cmdstanpy - INFO - Chain [1] done processing

02:50:08 - cmdstanpy - INFO - Chain [1] start processing

02:50:09 - cmdstanpy - INFO - Chain [1] done processing

02:50:09 - cmdstanpy - INFO - Chain [1] start processing

02:50:10 - cmdstanpy - INFO - Chain [1] done processing

02:50:10 - cmdstanpy - INFO - Chain [1] start processing

02:50:11 - cmdstanpy - INFO - Chain [1] done processing

02:50:11 - cmdstanpy - INFO - Chain [1] start processing

02:50:12 - cmdstanpy - INFO - Chain [1] done processing

02:50:12 - cmdstanpy - INFO - Chain [1] start processing

02:50:13 - cmdstanpy - INFO - Chain [1] done processing

02:50:13 - cmdstanpy - INFO - Chain [1] start processing

02:50:14 - cmdstanpy - INFO - Chain [1] done processing

02:50:15 - cmdstanpy - INFO - Chain [1] start processing

02:50:15 - cmdstanpy - INFO - Chain [1] done processing

02:50:16 - cmdstanpy - INFO - Chain [1] start processing

02:50:16 - cmdstanpy - INFO - Chain [1] done processing

02:50:16 - cmdstanpy - INFO - Chain [1] start processing

02:50:17 - cmdstanpy - INFO - Chain [1] done processing

02:50:18 - cmdstanpy - INFO - Chain [1] start processing

02:50:19 - cmdstanpy - INFO - Chain [1] done processing

02:50:19 - cmdstanpy - INFO - Chain [1] start processing

02:50:20 - cmdstanpy - INFO - Chain [1] done processing

02:50:20 - cmdstanpy - INFO - Chain [1] start processing

02:50:21 - cmdstanpy - INFO - Chain [1] done processing

02:50:21 - cmdstanpy - INFO - Chain [1] start processing

02:50:22 - cmdstanpy - INFO - Chain [1] done processing

02:50:22 - cmdstanpy - INFO - Chain [1] start processing

02:50:23 - cmdstanpy - INFO - Chain [1] done processing

02:50:23 - cmdstanpy - INFO - Chain [1] start processing

02:50:24 - cmdstanpy - INFO - Chain [1] done processing

02:50:24 - cmdstanpy - INFO - Chain [1] start processing

02:50:25 - cmdstanpy - INFO - Chain [1] done processing

02:50:26 - cmdstanpy - INFO - Chain [1] start processing

02:50:27 - cmdstanpy - INFO - Chain [1] done processing

02:50:27 - cmdstanpy - INFO - Chain [1] start processing

02:50:28 - cmdstanpy - INFO - Chain [1] done processing

02:50:28 - cmdstanpy - INFO - Chain [1] start processing

02:50:29 - cmdstanpy - INFO - Chain [1] done processing

02:50:29 - cmdstanpy - INFO - Chain [1] start processing

02:50:30 - cmdstanpy - INFO - Chain [1] done processing

02:50:30 - cmdstanpy - INFO - Chain [1] start processing

02:50:31 - cmdstanpy - INFO - Chain [1] done processing

02:50:32 - cmdstanpy - INFO - Chain [1] start processing

02:50:32 - cmdstanpy - INFO - Chain [1] done processing

02:50:33 - cmdstanpy - INFO - Chain [1] start processing

02:50:33 - cmdstanpy - INFO - Chain [1] done processing

02:50:34 - cmdstanpy - INFO - Chain [1] start processing

02:50:35 - cmdstanpy - INFO - Chain [1] done processing

02:50:35 - cmdstanpy - INFO - Chain [1] start processing

02:50:35 - cmdstanpy - INFO - Chain [1] done processing

02:50:36 - cmdstanpy - INFO - Chain [1] start processing

02:50:36 - cmdstanpy - INFO - Chain [1] done processing

02:50:37 - cmdstanpy - INFO - Chain [1] start processing

02:50:38 - cmdstanpy - INFO - Chain [1] done processing

02:50:38 - cmdstanpy - INFO - Chain [1] start processing

02:50:39 - cmdstanpy - INFO - Chain [1] done processing

02:50:39 - cmdstanpy - INFO - Chain [1] start processing

02:50:40 - cmdstanpy - INFO - Chain [1] done processing

02:50:40 - cmdstanpy - INFO - Chain [1] start processing

02:50:41 - cmdstanpy - INFO - Chain [1] done processing

02:50:41 - cmdstanpy - INFO - Chain [1] start processing

02:50:42 - cmdstanpy - INFO - Chain [1] done processing

02:50:42 - cmdstanpy - INFO - Chain [1] start processing

02:50:43 - cmdstanpy - INFO - Chain [1] done processing

02:50:43 - cmdstanpy - INFO - Chain [1] start processing

02:50:44 - cmdstanpy - INFO - Chain [1] done processing

02:50:44 - cmdstanpy - INFO - Chain [1] start processing

02:50:45 - cmdstanpy - INFO - Chain [1] done processing

02:50:46 - cmdstanpy - INFO - Chain [1] start processing

02:50:47 - cmdstanpy - INFO - Chain [1] done processing

02:50:47 - cmdstanpy - INFO - Chain [1] start processing

02:50:49 - cmdstanpy - INFO - Chain [1] done processing

02:50:49 - cmdstanpy - INFO - Chain [1] start processing

02:50:50 - cmdstanpy - INFO - Chain [1] done processing

02:50:50 - cmdstanpy - INFO - Chain [1] start processing

02:50:52 - cmdstanpy - INFO - Chain [1] done processing

02:50:52 - cmdstanpy - INFO - Chain [1] start processing

02:50:53 - cmdstanpy - INFO - Chain [1] done processing

02:50:53 - cmdstanpy - INFO - Chain [1] start processing

02:50:55 - cmdstanpy - INFO - Chain [1] done processing

02:50:55 - cmdstanpy - INFO - Chain [1] start processing

02:50:56 - cmdstanpy - INFO - Chain [1] done processing

02:50:56 - cmdstanpy - INFO - Chain [1] start processing

02:50:58 - cmdstanpy - INFO - Chain [1] done processing

02:50:58 - cmdstanpy - INFO - Chain [1] start processing

02:50:59 - cmdstanpy - INFO - Chain [1] done processing

02:50:59 - cmdstanpy - INFO - Chain [1] start processing

02:51:00 - cmdstanpy - INFO - Chain [1] done processing

02:51:00 - cmdstanpy - INFO - Chain [1] start processing

02:51:01 - cmdstanpy - INFO - Chain [1] done processing

02:51:01 - cmdstanpy - INFO - Chain [1] start processing

02:51:03 - cmdstanpy - INFO - Chain [1] done processing

02:51:03 - cmdstanpy - INFO - Chain [1] start processing

02:51:04 - cmdstanpy - INFO - Chain [1] done processing

02:51:05 - cmdstanpy - INFO - Chain [1] start processing

02:51:06 - cmdstanpy - INFO - Chain [1] done processing

02:51:06 - cmdstanpy - INFO - Chain [1] start processing

02:51:07 - cmdstanpy - INFO - Chain [1] done processing

02:51:08 - cmdstanpy - INFO - Chain [1] start processing

02:51:09 - cmdstanpy - INFO - Chain [1] done processing

02:51:09 - cmdstanpy - INFO - Chain [1] start processing

02:51:10 - cmdstanpy - INFO - Chain [1] done processing

02:51:10 - cmdstanpy - INFO - Chain [1] start processing

02:51:12 - cmdstanpy - INFO - Chain [1] done processing

02:51:12 - cmdstanpy - INFO - Chain [1] start processing

02:51:13 - cmdstanpy - INFO - Chain [1] done processing

02:51:14 - cmdstanpy - INFO - Chain [1] start processing

02:51:15 - cmdstanpy - INFO - Chain [1] done processing

02:51:15 - cmdstanpy - INFO - Chain [1] start processing

02:51:17 - cmdstanpy - INFO - Chain [1] done processing

02:51:17 - cmdstanpy - INFO - Chain [1] start processing

02:51:18 - cmdstanpy - INFO - Chain [1] done processing

02:51:18 - cmdstanpy - INFO - Chain [1] start processing

02:51:19 - cmdstanpy - INFO - Chain [1] done processing

02:51:20 - cmdstanpy - INFO - Chain [1] start processing

02:51:21 - cmdstanpy - INFO - Chain [1] done processing

02:51:22 - cmdstanpy - INFO - Chain [1] start processing

02:51:23 - cmdstanpy - INFO - Chain [1] done processing

02:51:23 - cmdstanpy - INFO - Chain [1] start processing

02:51:24 - cmdstanpy - INFO - Chain [1] done processing

02:51:25 - cmdstanpy - INFO - Chain [1] start processing

02:51:26 - cmdstanpy - INFO - Chain [1] done processing

02:51:26 - cmdstanpy - INFO - Chain [1] start processing

02:51:27 - cmdstanpy - INFO - Chain [1] done processing

02:51:27 - cmdstanpy - INFO - Chain [1] start processing

02:51:29 - cmdstanpy - INFO - Chain [1] done processing

02:51:29 - cmdstanpy - INFO - Chain [1] start processing

02:51:31 - cmdstanpy - INFO - Chain [1] done processing

02:51:31 - cmdstanpy - INFO - Chain [1] start processing

02:51:32 - cmdstanpy - INFO - Chain [1] done processing

02:51:33 - cmdstanpy - INFO - Chain [1] start processing

02:51:34 - cmdstanpy - INFO - Chain [1] done processing

02:51:34 - cmdstanpy - INFO - Chain [1] start processing

02:51:35 - cmdstanpy - INFO - Chain [1] done processing

02:51:35 - cmdstanpy - INFO - Chain [1] start processing

02:51:36 - cmdstanpy - INFO - Chain [1] done processing

02:51:37 - cmdstanpy - INFO - Chain [1] start processing

02:51:38 - cmdstanpy - INFO - Chain [1] done processing

02:51:38 - cmdstanpy - INFO - Chain [1] start processing

02:51:40 - cmdstanpy - INFO - Chain [1] done processing

02:51:40 - cmdstanpy - INFO - Chain [1] start processing

02:51:41 - cmdstanpy - INFO - Chain [1] done processing

02:51:41 - cmdstanpy - INFO - Chain [1] start processing

02:51:43 - cmdstanpy - INFO - Chain [1] done processing

02:51:43 - cmdstanpy - INFO - Chain [1] start processing

02:51:44 - cmdstanpy - INFO - Chain [1] done processing

02:51:44 - cmdstanpy - INFO - Chain [1] start processing

02:51:45 - cmdstanpy - INFO - Chain [1] done processing

02:51:46 - cmdstanpy - INFO - Chain [1] start processing

02:51:47 - cmdstanpy - INFO - Chain [1] done processing

02:51:48 - cmdstanpy - INFO - Chain [1] start processing

02:51:50 - cmdstanpy - INFO - Chain [1] done processing

02:51:50 - cmdstanpy - INFO - Chain [1] start processing

02:51:51 - cmdstanpy - INFO - Chain [1] done processing

02:51:52 - cmdstanpy - INFO - Chain [1] start processing

02:51:53 - cmdstanpy - INFO - Chain [1] done processing

02:51:54 - cmdstanpy - INFO - Chain [1] start processing

02:51:54 - cmdstanpy - INFO - Chain [1] done processing

02:51:54 - cmdstanpy - INFO - Chain [1] start processing

02:51:56 - cmdstanpy - INFO - Chain [1] done processing

02:51:56 - cmdstanpy - INFO - Chain [1] start processing

02:51:57 - cmdstanpy - INFO - Chain [1] done processing

02:51:58 - cmdstanpy - INFO - Chain [1] start processing

02:51:59 - cmdstanpy - INFO - Chain [1] done processing

02:52:00 - cmdstanpy - INFO - Chain [1] start processing

02:52:01 - cmdstanpy - INFO - Chain [1] done processing

02:52:01 - cmdstanpy - INFO - Chain [1] start processing

02:52:03 - cmdstanpy - INFO - Chain [1] done processing

02:52:03 - cmdstanpy - INFO - Chain [1] start processing

02:52:04 - cmdstanpy - INFO - Chain [1] done processing

02:52:05 - cmdstanpy - INFO - Chain [1] start processing

02:52:06 - cmdstanpy - INFO - Chain [1] done processing

02:52:06 - cmdstanpy - INFO - Chain [1] start processing

02:52:07 - cmdstanpy - INFO - Chain [1] done processing

02:52:08 - cmdstanpy - INFO - Chain [1] start processing

02:52:09 - cmdstanpy - INFO - Chain [1] done processing

02:52:10 - cmdstanpy - INFO - Chain [1] start processing

02:52:11 - cmdstanpy - INFO - Chain [1] done processing

02:52:12 - cmdstanpy - INFO - Chain [1] start processing

02:52:13 - cmdstanpy - INFO - Chain [1] done processing

02:52:13 - cmdstanpy - INFO - Chain [1] start processing

02:52:14 - cmdstanpy - INFO - Chain [1] done processing

02:52:14 - cmdstanpy - INFO - Chain [1] start processing

02:52:16 - cmdstanpy - INFO - Chain [1] done processing

02:52:16 - cmdstanpy - INFO - Chain [1] start processing

02:52:17 - cmdstanpy - INFO - Chain [1] done processing

02:52:18 - cmdstanpy - INFO - Chain [1] start processing

02:52:18 - cmdstanpy - INFO - Chain [1] done processing

02:52:19 - cmdstanpy - INFO - Chain [1] start processing

02:52:20 - cmdstanpy - INFO - Chain [1] done processing

02:52:20 - cmdstanpy - INFO - Chain [1] start processing

02:52:22 - cmdstanpy - INFO - Chain [1] done processing

02:52:22 - cmdstanpy - INFO - Chain [1] start processing

02:52:22 - cmdstanpy - INFO - Chain [1] done processing

02:52:23 - cmdstanpy - INFO - Chain [1] start processing

02:52:23 - cmdstanpy - INFO - Chain [1] done processing

02:52:24 - cmdstanpy - INFO - Chain [1] start processing

02:52:25 - cmdstanpy - INFO - Chain [1] done processing

02:52:26 - cmdstanpy - INFO - Chain [1] start processing

02:52:28 - cmdstanpy - INFO - Chain [1] done processing

02:52:28 - cmdstanpy - INFO - Chain [1] start processing

02:52:29 - cmdstanpy - INFO - Chain [1] done processing

02:52:30 - cmdstanpy - INFO - Chain [1] start processing

02:52:31 - cmdstanpy - INFO - Chain [1] done processing

02:52:31 - cmdstanpy - INFO - Chain [1] start processing

02:52:32 - cmdstanpy - INFO - Chain [1] done processing

02:52:33 - cmdstanpy - INFO - Chain [1] start processing

02:52:34 - cmdstanpy - INFO - Chain [1] done processing

02:52:34 - cmdstanpy - INFO - Chain [1] start processing

02:52:36 - cmdstanpy - INFO - Chain [1] done processing

02:52:36 - cmdstanpy - INFO - Chain [1] start processing

02:52:38 - cmdstanpy - INFO - Chain [1] done processing

02:52:38 - cmdstanpy - INFO - Chain [1] start processing

02:52:40 - cmdstanpy - INFO - Chain [1] done processing

02:52:41 - cmdstanpy - INFO - Chain [1] start processing

02:52:43 - cmdstanpy - INFO - Chain [1] done processing

02:52:44 - cmdstanpy - INFO - Chain [1] start processing

02:52:45 - cmdstanpy - INFO - Chain [1] done processing

02:52:46 - cmdstanpy - INFO - Chain [1] start processing

02:52:48 - cmdstanpy - INFO - Chain [1] done processing

02:52:49 - cmdstanpy - INFO - Chain [1] start processing

02:52:50 - cmdstanpy - INFO - Chain [1] done processing

02:52:50 - cmdstanpy - INFO - Chain [1] start processing

02:52:52 - cmdstanpy - INFO - Chain [1] done processing

02:52:53 - cmdstanpy - INFO - Chain [1] start processing

02:52:54 - cmdstanpy - INFO - Chain [1] done processing

02:52:54 - cmdstanpy - INFO - Chain [1] start processing

02:52:56 - cmdstanpy - INFO - Chain [1] done processing

02:52:56 - cmdstanpy - INFO - Chain [1] start processing

02:52:58 - cmdstanpy - INFO - Chain [1] done processing

02:52:58 - cmdstanpy - INFO - Chain [1] start processing

02:53:00 - cmdstanpy - INFO - Chain [1] done processing

02:53:00 - cmdstanpy - INFO - Chain [1] start processing

02:53:02 - cmdstanpy - INFO - Chain [1] done processing

02:53:02 - cmdstanpy - INFO - Chain [1] start processing

02:53:04 - cmdstanpy - INFO - Chain [1] done processing

02:53:04 - cmdstanpy - INFO - Chain [1] start processing

02:53:06 - cmdstanpy - INFO - Chain [1] done processing

02:53:06 - cmdstanpy - INFO - Chain [1] start processing

02:53:08 - cmdstanpy - INFO - Chain [1] done processing

02:53:08 - cmdstanpy - INFO - Chain [1] start processing

02:53:11 - cmdstanpy - INFO - Chain [1] done processing

02:53:11 - cmdstanpy - INFO - Chain [1] start processing

02:53:13 - cmdstanpy - INFO - Chain [1] done processing

02:53:13 - cmdstanpy - INFO - Chain [1] start processing

02:53:14 - cmdstanpy - INFO - Chain [1] done processing

02:53:15 - cmdstanpy - INFO - Chain [1] start processing

02:53:17 - cmdstanpy - INFO - Chain [1] done processing

02:53:17 - cmdstanpy - INFO - Chain [1] start processing

02:53:19 - cmdstanpy - INFO - Chain [1] done processing

02:53:19 - cmdstanpy - INFO - Chain [1] start processing

02:53:21 - cmdstanpy - INFO - Chain [1] done processing

02:53:21 - cmdstanpy - INFO - Chain [1] start processing

02:53:24 - cmdstanpy - INFO - Chain [1] done processing

02:53:24 - cmdstanpy - INFO - Chain [1] start processing

02:53:25 - cmdstanpy - INFO - Chain [1] done processing

02:53:26 - cmdstanpy - INFO - Chain [1] start processing

02:53:28 - cmdstanpy - INFO - Chain [1] done processing

02:53:28 - cmdstanpy - INFO - Chain [1] start processing

02:53:30 - cmdstanpy - INFO - Chain [1] done processing

02:53:31 - cmdstanpy - INFO - Chain [1] start processing

02:53:32 - cmdstanpy - INFO - Chain [1] done processing

02:53:32 - cmdstanpy - INFO - Chain [1] start processing

02:53:34 - cmdstanpy - INFO - Chain [1] done processing

02:53:35 - cmdstanpy - INFO - Chain [1] start processing

02:53:37 - cmdstanpy - INFO - Chain [1] done processing

02:53:38 - cmdstanpy - INFO - Chain [1] start processing

02:53:39 - cmdstanpy - INFO - Chain [1] done processing

02:53:40 - cmdstanpy - INFO - Chain [1] start processing

02:53:41 - cmdstanpy - INFO - Chain [1] done processing

02:53:42 - cmdstanpy - INFO - Chain [1] start processing

02:53:44 - cmdstanpy - INFO - Chain [1] done processing

02:53:44 - cmdstanpy - INFO - Chain [1] start processing

02:53:46 - cmdstanpy - INFO - Chain [1] done processing

02:53:47 - cmdstanpy - INFO - Chain [1] start processing

02:53:48 - cmdstanpy - INFO - Chain [1] done processing

02:53:48 - cmdstanpy - INFO - Chain [1] start processing

02:53:50 - cmdstanpy - INFO - Chain [1] done processing

02:53:50 - cmdstanpy - INFO - Chain [1] start processing

02:53:52 - cmdstanpy - INFO - Chain [1] done processing

02:53:52 - cmdstanpy - INFO - Chain [1] start processing

02:53:54 - cmdstanpy - INFO - Chain [1] done processing

02:53:54 - cmdstanpy - INFO - Chain [1] start processing

02:53:56 - cmdstanpy - INFO - Chain [1] done processing

02:53:57 - cmdstanpy - INFO - Chain [1] start processing

02:53:59 - cmdstanpy - INFO - Chain [1] done processing

02:53:59 - cmdstanpy - INFO - Chain [1] start processing

02:54:02 - cmdstanpy - INFO - Chain [1] done processing

02:54:02 - cmdstanpy - INFO - Chain [1] start processing

02:54:04 - cmdstanpy - INFO - Chain [1] done processing

02:54:04 - cmdstanpy - INFO - Chain [1] start processing

02:54:07 - cmdstanpy - INFO - Chain [1] done processing

02:54:07 - cmdstanpy - INFO - Chain [1] start processing

02:54:08 - cmdstanpy - INFO - Chain [1] done processing

02:54:09 - cmdstanpy - INFO - Chain [1] start processing

02:54:11 - cmdstanpy - INFO - Chain [1] done processing

02:54:11 - cmdstanpy - INFO - Chain [1] start processing

02:54:14 - cmdstanpy - INFO - Chain [1] done processing

02:54:14 - cmdstanpy - INFO - Chain [1] start processing

02:54:16 - cmdstanpy - INFO - Chain [1] done processing

02:54:16 - cmdstanpy - INFO - Chain [1] start processing

02:54:18 - cmdstanpy - INFO - Chain [1] done processing

02:54:19 - cmdstanpy - INFO - Chain [1] start processing

02:54:20 - cmdstanpy - INFO - Chain [1] done processing

02:54:20 - cmdstanpy - INFO - Chain [1] start processing

02:54:22 - cmdstanpy - INFO - Chain [1] done processing

02:54:22 - cmdstanpy - INFO - Chain [1] start processing

02:54:25 - cmdstanpy - INFO - Chain [1] done processing

02:54:26 - cmdstanpy - INFO - Chain [1] start processing

02:54:27 - cmdstanpy - INFO - Chain [1] done processing

02:54:28 - cmdstanpy - INFO - Chain [1] start processing

02:54:30 - cmdstanpy - INFO - Chain [1] done processing

02:54:30 - cmdstanpy - INFO - Chain [1] start processing

02:54:32 - cmdstanpy - INFO - Chain [1] done processing

02:54:33 - cmdstanpy - INFO - Chain [1] start processing

02:54:34 - cmdstanpy - INFO - Chain [1] done processing

02:54:35 - cmdstanpy - INFO - Chain [1] start processing

02:54:37 - cmdstanpy - INFO - Chain [1] done processing

02:54:37 - cmdstanpy - INFO - Chain [1] start processing

02:54:38 - cmdstanpy - INFO - Chain [1] done processing

02:54:39 - cmdstanpy - INFO - Chain [1] start processing

02:54:40 - cmdstanpy - INFO - Chain [1] done processing

02:54:41 - cmdstanpy - INFO - Chain [1] start processing

02:54:43 - cmdstanpy - INFO - Chain [1] done processing

02:54:43 - cmdstanpy - INFO - Chain [1] start processing

02:54:45 - cmdstanpy - INFO - Chain [1] done processing

02:54:46 - cmdstanpy - INFO - Chain [1] start processing

02:54:48 - cmdstanpy - INFO - Chain [1] done processing

02:54:48 - cmdstanpy - INFO - Chain [1] start processing

02:54:50 - cmdstanpy - INFO - Chain [1] done processing

02:54:50 - cmdstanpy - INFO - Chain [1] start processing

02:54:52 - cmdstanpy - INFO - Chain [1] done processing

02:54:53 - cmdstanpy - INFO - Chain [1] start processing

02:54:55 - cmdstanpy - INFO - Chain [1] done processing

02:54:55 - cmdstanpy - INFO - Chain [1] start processing

02:54:57 - cmdstanpy - INFO - Chain [1] done processing

02:54:58 - cmdstanpy - INFO - Chain [1] start processing

02:54:59 - cmdstanpy - INFO - Chain [1] done processing

02:55:00 - cmdstanpy - INFO - Chain [1] start processing

02:55:02 - cmdstanpy - INFO - Chain [1] done processing

02:55:02 - cmdstanpy - INFO - Chain [1] start processing

02:55:04 - cmdstanpy - INFO - Chain [1] done processing

02:55:04 - cmdstanpy - INFO - Chain [1] start processing

02:55:07 - cmdstanpy - INFO - Chain [1] done processing

02:55:07 - cmdstanpy - INFO - Chain [1] start processing

02:55:09 - cmdstanpy - INFO - Chain [1] done processing

02:55:10 - cmdstanpy - INFO - Chain [1] start processing

02:55:12 - cmdstanpy - INFO - Chain [1] done processing

02:55:12 - cmdstanpy - INFO - Chain [1] start processing

02:55:15 - cmdstanpy - INFO - Chain [1] done processing

02:55:15 - cmdstanpy - INFO - Chain [1] start processing

02:55:17 - cmdstanpy - INFO - Chain [1] done processing

02:55:18 - cmdstanpy - INFO - Chain [1] start processing

02:55:20 - cmdstanpy - INFO - Chain [1] done processing

02:55:20 - cmdstanpy - INFO - Chain [1] start processing

02:55:22 - cmdstanpy - INFO - Chain [1] done processing

02:55:22 - cmdstanpy - INFO - Chain [1] start processing

02:55:24 - cmdstanpy - INFO - Chain [1] done processing

02:55:24 - cmdstanpy - INFO - Chain [1] start processing

02:55:27 - cmdstanpy - INFO - Chain [1] done processing

02:55:28 - cmdstanpy - INFO - Chain [1] start processing

02:55:29 - cmdstanpy - INFO - Chain [1] done processing

02:55:30 - cmdstanpy - INFO - Chain [1] start processing

02:55:32 - cmdstanpy - INFO - Chain [1] done processing

02:55:32 - cmdstanpy - INFO - Chain [1] start processing

02:55:34 - cmdstanpy - INFO - Chain [1] done processing

02:55:35 - cmdstanpy - INFO - Chain [1] start processing

02:55:37 - cmdstanpy - INFO - Chain [1] done processing

02:55:37 - cmdstanpy - INFO - Chain [1] start processing

02:55:39 - cmdstanpy - INFO - Chain [1] done processing

02:55:39 - cmdstanpy - INFO - Chain [1] start processing

02:55:41 - cmdstanpy - INFO - Chain [1] done processing

02:55:41 - cmdstanpy - INFO - Chain [1] start processing

02:55:44 - cmdstanpy - INFO - Chain [1] done processing

02:55:44 - cmdstanpy - INFO - Chain [1] start processing

02:55:47 - cmdstanpy - INFO - Chain [1] done processing

02:55:47 - cmdstanpy - INFO - Chain [1] start processing

02:55:50 - cmdstanpy - INFO - Chain [1] done processing

02:55:50 - cmdstanpy - INFO - Chain [1] start processing

02:55:52 - cmdstanpy - INFO - Chain [1] done processing

02:55:53 - cmdstanpy - INFO - Chain [1] start processing

02:55:55 - cmdstanpy - INFO - Chain [1] done processing

02:55:55 - cmdstanpy - INFO - Chain [1] start processing

02:55:58 - cmdstanpy - INFO - Chain [1] done processing

02:55:58 - cmdstanpy - INFO - Chain [1] start processing

02:56:00 - cmdstanpy - INFO - Chain [1] done processing

02:56:00 - cmdstanpy - INFO - Chain [1] start processing

02:56:02 - cmdstanpy - INFO - Chain [1] done processing

02:56:03 - cmdstanpy - INFO - Chain [1] start processing

02:56:04 - cmdstanpy - INFO - Chain [1] done processing

02:56:05 - cmdstanpy - INFO - Chain [1] start processing

02:56:07 - cmdstanpy - INFO - Chain [1] done processing

02:56:07 - cmdstanpy - INFO - Chain [1] start processing

02:56:09 - cmdstanpy - INFO - Chain [1] done processing

02:56:09 - cmdstanpy - INFO - Chain [1] start processing

02:56:11 - cmdstanpy - INFO - Chain [1] done processing

02:56:12 - cmdstanpy - INFO - Chain [1] start processing

02:56:14 - cmdstanpy - INFO - Chain [1] done processing

02:56:15 - cmdstanpy - INFO - Chain [1] start processing

02:56:17 - cmdstanpy - INFO - Chain [1] done processing

02:56:17 - cmdstanpy - INFO - Chain [1] start processing

02:56:19 - cmdstanpy - INFO - Chain [1] done processing

02:56:20 - cmdstanpy - INFO - Chain [1] start processing

02:56:22 - cmdstanpy - INFO - Chain [1] done processing

02:56:22 - cmdstanpy - INFO - Chain [1] start processing

02:56:24 - cmdstanpy - INFO - Chain [1] done processing

02:56:24 - cmdstanpy - INFO - Chain [1] start processing

02:56:27 - cmdstanpy - INFO - Chain [1] done processing

02:56:27 - cmdstanpy - INFO - Chain [1] start processing

02:56:30 - cmdstanpy - INFO - Chain [1] done processing

02:56:30 - cmdstanpy - INFO - Chain [1] start processing

02:56:32 - cmdstanpy - INFO - Chain [1] done processing

02:56:32 - cmdstanpy - INFO - Chain [1] start processing

02:56:34 - cmdstanpy - INFO - Chain [1] done processing

02:56:34 - cmdstanpy - INFO - Chain [1] start processing

02:56:35 - cmdstanpy - INFO - Chain [1] done processing

02:56:36 - cmdstanpy - INFO - Chain [1] start processing

02:56:38 - cmdstanpy - INFO - Chain [1] done processing

02:56:38 - cmdstanpy - INFO - Chain [1] start processing

02:56:40 - cmdstanpy - INFO - Chain [1] done processing

02:56:40 - cmdstanpy - INFO - Chain [1] start processing

02:56:42 - cmdstanpy - INFO - Chain [1] done processing

02:56:43 - cmdstanpy - INFO - Chain [1] start processing

02:56:44 - cmdstanpy - INFO - Chain [1] done processing

02:56:44 - cmdstanpy - INFO - Chain [1] start processing

02:56:46 - cmdstanpy - INFO - Chain [1] done processing

02:56:46 - cmdstanpy - INFO - Chain [1] start processing

02:56:48 - cmdstanpy - INFO - Chain [1] done processing

02:56:49 - cmdstanpy - INFO - Chain [1] start processing

02:56:50 - cmdstanpy - INFO - Chain [1] done processing

02:56:51 - cmdstanpy - INFO - Chain [1] start processing

02:56:53 - cmdstanpy - INFO - Chain [1] done processing

02:56:53 - cmdstanpy - INFO - Chain [1] start processing

02:56:56 - cmdstanpy - INFO - Chain [1] done processing

02:56:56 - cmdstanpy - INFO - Chain [1] start processing

02:56:59 - cmdstanpy - INFO - Chain [1] done processing

02:57:00 - cmdstanpy - INFO - Chain [1] start processing

02:57:01 - cmdstanpy - INFO - Chain [1] done processing

02:57:01 - cmdstanpy - INFO - Chain [1] start processing

02:57:03 - cmdstanpy - INFO - Chain [1] done processing

02:57:04 - cmdstanpy - INFO - Chain [1] start processing

02:57:06 - cmdstanpy - INFO - Chain [1] done processing

02:57:06 - cmdstanpy - INFO - Chain [1] start processing

02:57:08 - cmdstanpy - INFO - Chain [1] done processing

02:57:09 - cmdstanpy - INFO - Chain [1] start processing

02:57:11 - cmdstanpy - INFO - Chain [1] done processing

02:57:11 - cmdstanpy - INFO - Chain [1] start processing

02:57:13 - cmdstanpy - INFO - Chain [1] done processing

02:57:13 - cmdstanpy - INFO - Chain [1] start processing

02:57:16 - cmdstanpy - INFO - Chain [1] done processing

02:57:16 - cmdstanpy - INFO - Chain [1] start processing

02:57:18 - cmdstanpy - INFO - Chain [1] done processing

02:57:18 - cmdstanpy - INFO - Chain [1] start processing

02:57:21 - cmdstanpy - INFO - Chain [1] done processing

02:57:21 - cmdstanpy - INFO - Chain [1] start processing

02:57:23 - cmdstanpy - INFO - Chain [1] done processing

02:57:23 - cmdstanpy - INFO - Chain [1] start processing

02:57:25 - cmdstanpy - INFO - Chain [1] done processing

02:57:26 - cmdstanpy - INFO - Chain [1] start processing

02:57:29 - cmdstanpy - INFO - Chain [1] done processing

02:57:29 - cmdstanpy - INFO - Chain [1] start processing

02:57:31 - cmdstanpy - INFO - Chain [1] done processing

02:57:32 - cmdstanpy - INFO - Chain [1] start processing

02:57:33 - cmdstanpy - INFO - Chain [1] done processing

02:57:34 - cmdstanpy - INFO - Chain [1] start processing

02:57:36 - cmdstanpy - INFO - Chain [1] done processing

02:57:36 - cmdstanpy - INFO - Chain [1] start processing

02:57:38 - cmdstanpy - INFO - Chain [1] done processing

02:57:38 - cmdstanpy - INFO - Chain [1] start processing

02:57:41 - cmdstanpy - INFO - Chain [1] done processing

02:57:41 - cmdstanpy - INFO - Chain [1] start processing

02:57:44 - cmdstanpy - INFO - Chain [1] done processing

02:57:45 - cmdstanpy - INFO - Chain [1] start processing

02:57:47 - cmdstanpy - INFO - Chain [1] done processing

02:57:47 - cmdstanpy - INFO - Chain [1] start processing

02:57:49 - cmdstanpy - INFO - Chain [1] done processing

02:57:49 - cmdstanpy - INFO - Chain [1] start processing

02:57:51 - cmdstanpy - INFO - Chain [1] done processing

02:57:52 - cmdstanpy - INFO - Chain [1] start processing

02:57:54 - cmdstanpy - INFO - Chain [1] done processing

02:57:55 - cmdstanpy - INFO - Chain [1] start processing

02:57:57 - cmdstanpy - INFO - Chain [1] done processing

02:57:57 - cmdstanpy - INFO - Chain [1] start processing

02:58:00 - cmdstanpy - INFO - Chain [1] done processing

02:58:00 - cmdstanpy - INFO - Chain [1] start processing

02:58:03 - cmdstanpy - INFO - Chain [1] done processing

02:58:03 - cmdstanpy - INFO - Chain [1] start processing

02:58:05 - cmdstanpy - INFO - Chain [1] done processing

02:58:06 - cmdstanpy - INFO - Chain [1] start processing

02:58:08 - cmdstanpy - INFO - Chain [1] done processing

02:58:08 - cmdstanpy - INFO - Chain [1] start processing

02:58:10 - cmdstanpy - INFO - Chain [1] done processing

02:58:10 - cmdstanpy - INFO - Chain [1] start processing

02:58:12 - cmdstanpy - INFO - Chain [1] done processing

02:58:13 - cmdstanpy - INFO - Chain [1] start processing

02:58:16 - cmdstanpy - INFO - Chain [1] done processing

h=6: Prophet cps elegido 0.5
h= 6 Paseo aleatorio  [cpu]    0.0 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

h= 6 ARIMA            [cpu]   56.3 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

h= 6 VAR              [cpu]    0.7 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

02:59:13 - cmdstanpy - INFO - Chain [1] start processing

02:59:16 - cmdstanpy - INFO - Chain [1] done processing

02:59:17 - cmdstanpy - INFO - Chain [1] start processing

02:59:20 - cmdstanpy - INFO - Chain [1] done processing

02:59:20 - cmdstanpy - INFO - Chain [1] start processing

02:59:21 - cmdstanpy - INFO - Chain [1] done processing

02:59:22 - cmdstanpy - INFO - Chain [1] start processing

02:59:24 - cmdstanpy - INFO - Chain [1] done processing

02:59:24 - cmdstanpy - INFO - Chain [1] start processing

02:59:27 - cmdstanpy - INFO - Chain [1] done processing

02:59:28 - cmdstanpy - INFO - Chain [1] start processing

02:59:30 - cmdstanpy - INFO - Chain [1] done processing

02:59:31 - cmdstanpy - INFO - Chain [1] start processing

02:59:33 - cmdstanpy - INFO - Chain [1] done processing

02:59:33 - cmdstanpy - INFO - Chain [1] start processing

02:59:36 - cmdstanpy - INFO - Chain [1] done processing

02:59:36 - cmdstanpy - INFO - Chain [1] start processing

02:59:38 - cmdstanpy - INFO - Chain [1] done processing

02:59:39 - cmdstanpy - INFO - Chain [1] start processing

02:59:40 - cmdstanpy - INFO - Chain [1] done processing

02:59:41 - cmdstanpy - INFO - Chain [1] start processing

02:59:43 - cmdstanpy - INFO - Chain [1] done processing

02:59:43 - cmdstanpy - INFO - Chain [1] start processing

02:59:45 - cmdstanpy - INFO - Chain [1] done processing

02:59:45 - cmdstanpy - INFO - Chain [1] start processing

02:59:49 - cmdstanpy - INFO - Chain [1] done processing

02:59:49 - cmdstanpy - INFO - Chain [1] start processing

02:59:51 - cmdstanpy - INFO - Chain [1] done processing

02:59:51 - cmdstanpy - INFO - Chain [1] start processing

02:59:53 - cmdstanpy - INFO - Chain [1] done processing

02:59:53 - cmdstanpy - INFO - Chain [1] start processing

02:59:55 - cmdstanpy - INFO - Chain [1] done processing

02:59:56 - cmdstanpy - INFO - Chain [1] start processing

02:59:59 - cmdstanpy - INFO - Chain [1] done processing

02:59:59 - cmdstanpy - INFO - Chain [1] start processing

03:00:02 - cmdstanpy - INFO - Chain [1] done processing

03:00:02 - cmdstanpy - INFO - Chain [1] start processing

03:00:04 - cmdstanpy - INFO - Chain [1] done processing

03:00:05 - cmdstanpy - INFO - Chain [1] start processing

03:00:07 - cmdstanpy - INFO - Chain [1] done processing

03:00:07 - cmdstanpy - INFO - Chain [1] start processing

03:00:09 - cmdstanpy - INFO - Chain [1] done processing

03:00:10 - cmdstanpy - INFO - Chain [1] start processing

03:00:12 - cmdstanpy - INFO - Chain [1] done processing

03:00:12 - cmdstanpy - INFO - Chain [1] start processing

03:00:14 - cmdstanpy - INFO - Chain [1] done processing

03:00:15 - cmdstanpy - INFO - Chain [1] start processing

03:00:17 - cmdstanpy - INFO - Chain [1] done processing

03:00:18 - cmdstanpy - INFO - Chain [1] start processing

03:00:20 - cmdstanpy - INFO - Chain [1] done processing

03:00:21 - cmdstanpy - INFO - Chain [1] start processing

03:00:23 - cmdstanpy - INFO - Chain [1] done processing

03:00:23 - cmdstanpy - INFO - Chain [1] start processing

03:00:25 - cmdstanpy - INFO - Chain [1] done processing

03:00:26 - cmdstanpy - INFO - Chain [1] start processing

03:00:28 - cmdstanpy - INFO - Chain [1] done processing

03:00:28 - cmdstanpy - INFO - Chain [1] start processing

03:00:30 - cmdstanpy - INFO - Chain [1] done processing

03:00:31 - cmdstanpy - INFO - Chain [1] start processing

03:00:33 - cmdstanpy - INFO - Chain [1] done processing

03:00:34 - cmdstanpy - INFO - Chain [1] start processing

03:00:36 - cmdstanpy - INFO - Chain [1] done processing

03:00:37 - cmdstanpy - INFO - Chain [1] start processing

03:00:39 - cmdstanpy - INFO - Chain [1] done processing

03:00:39 - cmdstanpy - INFO - Chain [1] start processing

03:00:41 - cmdstanpy - INFO - Chain [1] done processing

03:00:42 - cmdstanpy - INFO - Chain [1] start processing

03:00:44 - cmdstanpy - INFO - Chain [1] done processing

03:00:44 - cmdstanpy - INFO - Chain [1] start processing

03:00:47 - cmdstanpy - INFO - Chain [1] done processing

03:00:47 - cmdstanpy - INFO - Chain [1] start processing

03:00:50 - cmdstanpy - INFO - Chain [1] done processing

03:00:50 - cmdstanpy - INFO - Chain [1] start processing

03:00:53 - cmdstanpy - INFO - Chain [1] done processing

03:00:53 - cmdstanpy - INFO - Chain [1] start processing

03:00:55 - cmdstanpy - INFO - Chain [1] done processing

03:00:55 - cmdstanpy - INFO - Chain [1] start processing

03:00:58 - cmdstanpy - INFO - Chain [1] done processing

03:00:58 - cmdstanpy - INFO - Chain [1] start processing

03:01:00 - cmdstanpy - INFO - Chain [1] done processing

03:01:01 - cmdstanpy - INFO - Chain [1] start processing

03:01:03 - cmdstanpy - INFO - Chain [1] done processing

03:01:04 - cmdstanpy - INFO - Chain [1] start processing

03:01:06 - cmdstanpy - INFO - Chain [1] done processing

03:01:07 - cmdstanpy - INFO - Chain [1] start processing

03:01:10 - cmdstanpy - INFO - Chain [1] done processing

03:01:10 - cmdstanpy - INFO - Chain [1] start processing

03:01:12 - cmdstanpy - INFO - Chain [1] done processing

03:01:13 - cmdstanpy - INFO - Chain [1] start processing

03:01:14 - cmdstanpy - INFO - Chain [1] done processing

03:01:14 - cmdstanpy - INFO - Chain [1] start processing

03:01:17 - cmdstanpy - INFO - Chain [1] done processing

03:01:17 - cmdstanpy - INFO - Chain [1] start processing

03:01:20 - cmdstanpy - INFO - Chain [1] done processing

03:01:21 - cmdstanpy - INFO - Chain [1] start processing

03:01:23 - cmdstanpy - INFO - Chain [1] done processing

03:01:23 - cmdstanpy - INFO - Chain [1] start processing

03:01:24 - cmdstanpy - INFO - Chain [1] done processing

03:01:25 - cmdstanpy - INFO - Chain [1] start processing

03:01:27 - cmdstanpy - INFO - Chain [1] done processing

03:01:27 - cmdstanpy - INFO - Chain [1] start processing

03:01:29 - cmdstanpy - INFO - Chain [1] done processing

03:01:30 - cmdstanpy - INFO - Chain [1] start processing

03:01:32 - cmdstanpy - INFO - Chain [1] done processing

03:01:33 - cmdstanpy - INFO - Chain [1] start processing

03:01:36 - cmdstanpy - INFO - Chain [1] done processing

03:01:36 - cmdstanpy - INFO - Chain [1] start processing

03:01:39 - cmdstanpy - INFO - Chain [1] done processing

03:01:39 - cmdstanpy - INFO - Chain [1] start processing

03:01:42 - cmdstanpy - INFO - Chain [1] done processing

03:01:42 - cmdstanpy - INFO - Chain [1] start processing

03:01:45 - cmdstanpy - INFO - Chain [1] done processing

03:01:46 - cmdstanpy - INFO - Chain [1] start processing

03:01:48 - cmdstanpy - INFO - Chain [1] done processing

03:01:48 - cmdstanpy - INFO - Chain [1] start processing

03:01:50 - cmdstanpy - INFO - Chain [1] done processing

03:01:50 - cmdstanpy - INFO - Chain [1] start processing

03:01:53 - cmdstanpy - INFO - Chain [1] done processing

03:01:53 - cmdstanpy - INFO - Chain [1] start processing

03:01:55 - cmdstanpy - INFO - Chain [1] done processing

03:01:56 - cmdstanpy - INFO - Chain [1] start processing

03:01:58 - cmdstanpy - INFO - Chain [1] done processing

03:01:58 - cmdstanpy - INFO - Chain [1] start processing

03:02:01 - cmdstanpy - INFO - Chain [1] done processing

03:02:01 - cmdstanpy - INFO - Chain [1] start processing

03:02:04 - cmdstanpy - INFO - Chain [1] done processing

03:02:04 - cmdstanpy - INFO - Chain [1] start processing

03:02:06 - cmdstanpy - INFO - Chain [1] done processing

03:02:07 - cmdstanpy - INFO - Chain [1] start processing

03:02:09 - cmdstanpy - INFO - Chain [1] done processing

03:02:10 - cmdstanpy - INFO - Chain [1] start processing

03:02:12 - cmdstanpy - INFO - Chain [1] done processing

03:02:12 - cmdstanpy - INFO - Chain [1] start processing

03:02:14 - cmdstanpy - INFO - Chain [1] done processing

03:02:15 - cmdstanpy - INFO - Chain [1] start processing

03:02:17 - cmdstanpy - INFO - Chain [1] done processing

03:02:17 - cmdstanpy - INFO - Chain [1] start processing

03:02:19 - cmdstanpy - INFO - Chain [1] done processing

03:02:20 - cmdstanpy - INFO - Chain [1] start processing

03:02:22 - cmdstanpy - INFO - Chain [1] done processing

03:02:23 - cmdstanpy - INFO - Chain [1] start processing

03:02:25 - cmdstanpy - INFO - Chain [1] done processing

03:02:26 - cmdstanpy - INFO - Chain [1] start processing

03:02:29 - cmdstanpy - INFO - Chain [1] done processing

03:02:29 - cmdstanpy - INFO - Chain [1] start processing

03:02:32 - cmdstanpy - INFO - Chain [1] done processing

03:02:32 - cmdstanpy - INFO - Chain [1] start processing

03:02:35 - cmdstanpy - INFO - Chain [1] done processing

03:02:36 - cmdstanpy - INFO - Chain [1] start processing

03:02:38 - cmdstanpy - INFO - Chain [1] done processing

03:02:38 - cmdstanpy - INFO - Chain [1] start processing

03:02:41 - cmdstanpy - INFO - Chain [1] done processing

03:02:41 - cmdstanpy - INFO - Chain [1] start processing

03:02:43 - cmdstanpy - INFO - Chain [1] done processing

03:02:44 - cmdstanpy - INFO - Chain [1] start processing

03:02:47 - cmdstanpy - INFO - Chain [1] done processing

03:02:47 - cmdstanpy - INFO - Chain [1] start processing

03:02:49 - cmdstanpy - INFO - Chain [1] done processing

03:02:49 - cmdstanpy - INFO - Chain [1] start processing

03:02:52 - cmdstanpy - INFO - Chain [1] done processing

03:02:52 - cmdstanpy - INFO - Chain [1] start processing

03:02:54 - cmdstanpy - INFO - Chain [1] done processing

03:02:55 - cmdstanpy - INFO - Chain [1] start processing

03:02:58 - cmdstanpy - INFO - Chain [1] done processing

03:02:58 - cmdstanpy - INFO - Chain [1] start processing

03:03:01 - cmdstanpy - INFO - Chain [1] done processing

03:03:02 - cmdstanpy - INFO - Chain [1] start processing

03:03:04 - cmdstanpy - INFO - Chain [1] done processing

03:03:05 - cmdstanpy - INFO - Chain [1] start processing

03:03:05 - cmdstanpy - INFO - Chain [1] done processing

03:03:05 - cmdstanpy - INFO - Chain [1] start processing

03:03:05 - cmdstanpy - INFO - Chain [1] done processing

03:03:06 - cmdstanpy - INFO - Chain [1] start processing

03:03:06 - cmdstanpy - INFO - Chain [1] done processing

03:03:06 - cmdstanpy - INFO - Chain [1] start processing

03:03:06 - cmdstanpy - INFO - Chain [1] done processing

03:03:07 - cmdstanpy - INFO - Chain [1] start processing

03:03:07 - cmdstanpy - INFO - Chain [1] done processing

03:03:07 - cmdstanpy - INFO - Chain [1] start processing

03:03:08 - cmdstanpy - INFO - Chain [1] done processing

03:03:08 - cmdstanpy - INFO - Chain [1] start processing

03:03:08 - cmdstanpy - INFO - Chain [1] done processing

03:03:09 - cmdstanpy - INFO - Chain [1] start processing

03:03:09 - cmdstanpy - INFO - Chain [1] done processing

03:03:09 - cmdstanpy - INFO - Chain [1] start processing

03:03:09 - cmdstanpy - INFO - Chain [1] done processing

03:03:10 - cmdstanpy - INFO - Chain [1] start processing

03:03:10 - cmdstanpy - INFO - Chain [1] done processing

03:03:10 - cmdstanpy - INFO - Chain [1] start processing

03:03:10 - cmdstanpy - INFO - Chain [1] done processing

03:03:11 - cmdstanpy - INFO - Chain [1] start processing

03:03:11 - cmdstanpy - INFO - Chain [1] done processing

03:03:12 - cmdstanpy - INFO - Chain [1] start processing

03:03:12 - cmdstanpy - INFO - Chain [1] done processing

03:03:12 - cmdstanpy - INFO - Chain [1] start processing

03:03:12 - cmdstanpy - INFO - Chain [1] done processing

03:03:13 - cmdstanpy - INFO - Chain [1] start processing

03:03:13 - cmdstanpy - INFO - Chain [1] done processing

03:03:13 - cmdstanpy - INFO - Chain [1] start processing

03:03:13 - cmdstanpy - INFO - Chain [1] done processing

03:03:14 - cmdstanpy - INFO - Chain [1] start processing

03:03:14 - cmdstanpy - INFO - Chain [1] done processing

03:03:15 - cmdstanpy - INFO - Chain [1] start processing

03:03:15 - cmdstanpy - INFO - Chain [1] done processing

03:03:15 - cmdstanpy - INFO - Chain [1] start processing

03:03:15 - cmdstanpy - INFO - Chain [1] done processing

03:03:16 - cmdstanpy - INFO - Chain [1] start processing

03:03:16 - cmdstanpy - INFO - Chain [1] done processing

03:03:16 - cmdstanpy - INFO - Chain [1] start processing

03:03:17 - cmdstanpy - INFO - Chain [1] done processing

03:03:17 - cmdstanpy - INFO - Chain [1] start processing

03:03:17 - cmdstanpy - INFO - Chain [1] done processing

03:03:18 - cmdstanpy - INFO - Chain [1] start processing

03:03:18 - cmdstanpy - INFO - Chain [1] done processing

03:03:18 - cmdstanpy - INFO - Chain [1] start processing

03:03:18 - cmdstanpy - INFO - Chain [1] done processing

03:03:19 - cmdstanpy - INFO - Chain [1] start processing

03:03:19 - cmdstanpy - INFO - Chain [1] done processing

03:03:19 - cmdstanpy - INFO - Chain [1] start processing

03:03:20 - cmdstanpy - INFO - Chain [1] done processing

03:03:20 - cmdstanpy - INFO - Chain [1] start processing

03:03:20 - cmdstanpy - INFO - Chain [1] done processing

03:03:21 - cmdstanpy - INFO - Chain [1] start processing

03:03:21 - cmdstanpy - INFO - Chain [1] done processing

03:03:21 - cmdstanpy - INFO - Chain [1] start processing

03:03:22 - cmdstanpy - INFO - Chain [1] done processing

03:03:22 - cmdstanpy - INFO - Chain [1] start processing

03:03:22 - cmdstanpy - INFO - Chain [1] done processing

03:03:23 - cmdstanpy - INFO - Chain [1] start processing

03:03:23 - cmdstanpy - INFO - Chain [1] done processing

03:03:23 - cmdstanpy - INFO - Chain [1] start processing

03:03:23 - cmdstanpy - INFO - Chain [1] done processing

03:03:24 - cmdstanpy - INFO - Chain [1] start processing

03:03:24 - cmdstanpy - INFO - Chain [1] done processing

03:03:24 - cmdstanpy - INFO - Chain [1] start processing

03:03:25 - cmdstanpy - INFO - Chain [1] done processing

03:03:25 - cmdstanpy - INFO - Chain [1] start processing

03:03:25 - cmdstanpy - INFO - Chain [1] done processing

03:03:26 - cmdstanpy - INFO - Chain [1] start processing

03:03:26 - cmdstanpy - INFO - Chain [1] done processing

03:03:26 - cmdstanpy - INFO - Chain [1] start processing

03:03:26 - cmdstanpy - INFO - Chain [1] done processing

03:03:27 - cmdstanpy - INFO - Chain [1] start processing

03:03:27 - cmdstanpy - INFO - Chain [1] done processing

03:03:27 - cmdstanpy - INFO - Chain [1] start processing

03:03:27 - cmdstanpy - INFO - Chain [1] done processing

03:03:28 - cmdstanpy - INFO - Chain [1] start processing

03:03:28 - cmdstanpy - INFO - Chain [1] done processing

03:03:28 - cmdstanpy - INFO - Chain [1] start processing

03:03:29 - cmdstanpy - INFO - Chain [1] done processing

03:03:29 - cmdstanpy - INFO - Chain [1] start processing

03:03:29 - cmdstanpy - INFO - Chain [1] done processing

03:03:30 - cmdstanpy - INFO - Chain [1] start processing

03:03:30 - cmdstanpy - INFO - Chain [1] done processing

03:03:30 - cmdstanpy - INFO - Chain [1] start processing

03:03:30 - cmdstanpy - INFO - Chain [1] done processing

03:03:31 - cmdstanpy - INFO - Chain [1] start processing

03:03:31 - cmdstanpy - INFO - Chain [1] done processing

03:03:31 - cmdstanpy - INFO - Chain [1] start processing

03:03:32 - cmdstanpy - INFO - Chain [1] done processing

03:03:32 - cmdstanpy - INFO - Chain [1] start processing

03:03:32 - cmdstanpy - INFO - Chain [1] done processing

03:03:33 - cmdstanpy - INFO - Chain [1] start processing

03:03:33 - cmdstanpy - INFO - Chain [1] done processing

03:03:33 - cmdstanpy - INFO - Chain [1] start processing

03:03:33 - cmdstanpy - INFO - Chain [1] done processing

03:03:34 - cmdstanpy - INFO - Chain [1] start processing

03:03:34 - cmdstanpy - INFO - Chain [1] done processing

03:03:34 - cmdstanpy - INFO - Chain [1] start processing

03:03:35 - cmdstanpy - INFO - Chain [1] done processing

03:03:35 - cmdstanpy - INFO - Chain [1] start processing

03:03:35 - cmdstanpy - INFO - Chain [1] done processing

03:03:36 - cmdstanpy - INFO - Chain [1] start processing

03:03:36 - cmdstanpy - INFO - Chain [1] done processing

03:03:36 - cmdstanpy - INFO - Chain [1] start processing

03:03:36 - cmdstanpy - INFO - Chain [1] done processing

03:03:37 - cmdstanpy - INFO - Chain [1] start processing

03:03:37 - cmdstanpy - INFO - Chain [1] done processing

03:03:37 - cmdstanpy - INFO - Chain [1] start processing

03:03:37 - cmdstanpy - INFO - Chain [1] done processing

03:03:38 - cmdstanpy - INFO - Chain [1] start processing

03:03:38 - cmdstanpy - INFO - Chain [1] done processing

03:03:39 - cmdstanpy - INFO - Chain [1] start processing

03:03:39 - cmdstanpy - INFO - Chain [1] done processing

03:03:39 - cmdstanpy - INFO - Chain [1] start processing

03:03:39 - cmdstanpy - INFO - Chain [1] done processing

03:03:40 - cmdstanpy - INFO - Chain [1] start processing

03:03:40 - cmdstanpy - INFO - Chain [1] done processing

03:03:40 - cmdstanpy - INFO - Chain [1] start processing

03:03:41 - cmdstanpy - INFO - Chain [1] done processing

03:03:41 - cmdstanpy - INFO - Chain [1] start processing

03:03:41 - cmdstanpy - INFO - Chain [1] done processing

03:03:42 - cmdstanpy - INFO - Chain [1] start processing

03:03:42 - cmdstanpy - INFO - Chain [1] done processing

03:03:42 - cmdstanpy - INFO - Chain [1] start processing

03:03:42 - cmdstanpy - INFO - Chain [1] done processing

03:03:43 - cmdstanpy - INFO - Chain [1] start processing

03:03:43 - cmdstanpy - INFO - Chain [1] done processing

03:03:43 - cmdstanpy - INFO - Chain [1] start processing

03:03:44 - cmdstanpy - INFO - Chain [1] done processing

03:03:44 - cmdstanpy - INFO - Chain [1] start processing

03:03:44 - cmdstanpy - INFO - Chain [1] done processing

03:03:45 - cmdstanpy - INFO - Chain [1] start processing

03:03:45 - cmdstanpy - INFO - Chain [1] done processing

03:03:45 - cmdstanpy - INFO - Chain [1] start processing

03:03:46 - cmdstanpy - INFO - Chain [1] done processing

03:03:46 - cmdstanpy - INFO - Chain [1] start processing

03:03:46 - cmdstanpy - INFO - Chain [1] done processing

03:03:46 - cmdstanpy - INFO - Chain [1] start processing

03:03:47 - cmdstanpy - INFO - Chain [1] done processing

03:03:47 - cmdstanpy - INFO - Chain [1] start processing

03:03:47 - cmdstanpy - INFO - Chain [1] done processing

03:03:48 - cmdstanpy - INFO - Chain [1] start processing

03:03:48 - cmdstanpy - INFO - Chain [1] done processing

03:03:48 - cmdstanpy - INFO - Chain [1] start processing

03:03:49 - cmdstanpy - INFO - Chain [1] done processing

03:03:49 - cmdstanpy - INFO - Chain [1] start processing

03:03:49 - cmdstanpy - INFO - Chain [1] done processing

03:03:50 - cmdstanpy - INFO - Chain [1] start processing

03:03:50 - cmdstanpy - INFO - Chain [1] done processing

03:03:50 - cmdstanpy - INFO - Chain [1] start processing

03:03:50 - cmdstanpy - INFO - Chain [1] done processing

03:03:51 - cmdstanpy - INFO - Chain [1] start processing

03:03:51 - cmdstanpy - INFO - Chain [1] done processing

03:03:51 - cmdstanpy - INFO - Chain [1] start processing

03:03:52 - cmdstanpy - INFO - Chain [1] done processing

03:03:52 - cmdstanpy - INFO - Chain [1] start processing

03:03:52 - cmdstanpy - INFO - Chain [1] done processing

03:03:53 - cmdstanpy - INFO - Chain [1] start processing

03:03:53 - cmdstanpy - INFO - Chain [1] done processing

03:03:53 - cmdstanpy - INFO - Chain [1] start processing

03:03:54 - cmdstanpy - INFO - Chain [1] done processing

03:03:54 - cmdstanpy - INFO - Chain [1] start processing

03:03:54 - cmdstanpy - INFO - Chain [1] done processing

03:03:55 - cmdstanpy - INFO - Chain [1] start processing

03:03:55 - cmdstanpy - INFO - Chain [1] done processing

03:03:55 - cmdstanpy - INFO - Chain [1] start processing

03:03:55 - cmdstanpy - INFO - Chain [1] done processing

03:03:56 - cmdstanpy - INFO - Chain [1] start processing

03:03:56 - cmdstanpy - INFO - Chain [1] done processing

03:03:56 - cmdstanpy - INFO - Chain [1] start processing

03:03:57 - cmdstanpy - INFO - Chain [1] done processing

03:03:57 - cmdstanpy - INFO - Chain [1] start processing

03:03:57 - cmdstanpy - INFO - Chain [1] done processing

03:03:58 - cmdstanpy - INFO - Chain [1] start processing

03:03:58 - cmdstanpy - INFO - Chain [1] done processing

03:03:58 - cmdstanpy - INFO - Chain [1] start processing

03:03:58 - cmdstanpy - INFO - Chain [1] done processing

03:03:59 - cmdstanpy - INFO - Chain [1] start processing

03:03:59 - cmdstanpy - INFO - Chain [1] done processing

03:03:59 - cmdstanpy - INFO - Chain [1] start processing

03:04:00 - cmdstanpy - INFO - Chain [1] done processing

03:04:00 - cmdstanpy - INFO - Chain [1] start processing

03:04:00 - cmdstanpy - INFO - Chain [1] done processing

03:04:01 - cmdstanpy - INFO - Chain [1] start processing

03:04:01 - cmdstanpy - INFO - Chain [1] done processing

03:04:01 - cmdstanpy - INFO - Chain [1] start processing

03:04:02 - cmdstanpy - INFO - Chain [1] done processing

03:04:02 - cmdstanpy - INFO - Chain [1] start processing

03:04:02 - cmdstanpy - INFO - Chain [1] done processing

03:04:03 - cmdstanpy - INFO - Chain [1] start processing

03:04:03 - cmdstanpy - INFO - Chain [1] done processing

03:04:03 - cmdstanpy - INFO - Chain [1] start processing

03:04:03 - cmdstanpy - INFO - Chain [1] done processing

03:04:04 - cmdstanpy - INFO - Chain [1] start processing

03:04:04 - cmdstanpy - INFO - Chain [1] done processing

03:04:04 - cmdstanpy - INFO - Chain [1] start processing

03:04:05 - cmdstanpy - INFO - Chain [1] done processing

03:04:05 - cmdstanpy - INFO - Chain [1] start processing

03:04:05 - cmdstanpy - INFO - Chain [1] done processing

03:04:05 - cmdstanpy - INFO - Chain [1] start processing

03:04:06 - cmdstanpy - INFO - Chain [1] done processing

03:04:06 - cmdstanpy - INFO - Chain [1] start processing

03:04:06 - cmdstanpy - INFO - Chain [1] done processing

03:04:07 - cmdstanpy - INFO - Chain [1] start processing

03:04:07 - cmdstanpy - INFO - Chain [1] done processing

03:04:07 - cmdstanpy - INFO - Chain [1] start processing

03:04:08 - cmdstanpy - INFO - Chain [1] done processing

03:04:08 - cmdstanpy - INFO - Chain [1] start processing

03:04:08 - cmdstanpy - INFO - Chain [1] done processing

03:04:09 - cmdstanpy - INFO - Chain [1] start processing

03:04:09 - cmdstanpy - INFO - Chain [1] done processing

03:04:09 - cmdstanpy - INFO - Chain [1] start processing

03:04:10 - cmdstanpy - INFO - Chain [1] done processing

03:04:10 - cmdstanpy - INFO - Chain [1] start processing

03:04:10 - cmdstanpy - INFO - Chain [1] done processing

03:04:10 - cmdstanpy - INFO - Chain [1] start processing

03:04:11 - cmdstanpy - INFO - Chain [1] done processing

03:04:11 - cmdstanpy - INFO - Chain [1] start processing

03:04:11 - cmdstanpy - INFO - Chain [1] done processing

03:04:12 - cmdstanpy - INFO - Chain [1] start processing

03:04:12 - cmdstanpy - INFO - Chain [1] done processing

03:04:12 - cmdstanpy - INFO - Chain [1] start processing

03:04:13 - cmdstanpy - INFO - Chain [1] done processing

03:04:13 - cmdstanpy - INFO - Chain [1] start processing

03:04:13 - cmdstanpy - INFO - Chain [1] done processing

03:04:14 - cmdstanpy - INFO - Chain [1] start processing

03:04:14 - cmdstanpy - INFO - Chain [1] done processing

03:04:14 - cmdstanpy - INFO - Chain [1] start processing

03:04:14 - cmdstanpy - INFO - Chain [1] done processing

03:04:15 - cmdstanpy - INFO - Chain [1] start processing

03:04:15 - cmdstanpy - INFO - Chain [1] done processing

03:04:15 - cmdstanpy - INFO - Chain [1] start processing

03:04:16 - cmdstanpy - INFO - Chain [1] done processing

03:04:16 - cmdstanpy - INFO - Chain [1] start processing

03:04:16 - cmdstanpy - INFO - Chain [1] done processing

03:04:17 - cmdstanpy - INFO - Chain [1] start processing

03:04:17 - cmdstanpy - INFO - Chain [1] done processing

03:04:17 - cmdstanpy - INFO - Chain [1] start processing

03:04:17 - cmdstanpy - INFO - Chain [1] done processing

03:04:18 - cmdstanpy - INFO - Chain [1] start processing

03:04:18 - cmdstanpy - INFO - Chain [1] done processing

03:04:19 - cmdstanpy - INFO - Chain [1] start processing

03:04:19 - cmdstanpy - INFO - Chain [1] done processing

03:04:19 - cmdstanpy - INFO - Chain [1] start processing

03:04:19 - cmdstanpy - INFO - Chain [1] done processing

03:04:20 - cmdstanpy - INFO - Chain [1] start processing

03:04:20 - cmdstanpy - INFO - Chain [1] done processing

03:04:21 - cmdstanpy - INFO - Chain [1] start processing

03:04:21 - cmdstanpy - INFO - Chain [1] done processing

03:04:21 - cmdstanpy - INFO - Chain [1] start processing

03:04:21 - cmdstanpy - INFO - Chain [1] done processing

03:04:22 - cmdstanpy - INFO - Chain [1] start processing

03:04:22 - cmdstanpy - INFO - Chain [1] done processing

03:04:22 - cmdstanpy - INFO - Chain [1] start processing

03:04:23 - cmdstanpy - INFO - Chain [1] done processing

03:04:23 - cmdstanpy - INFO - Chain [1] start processing

03:04:23 - cmdstanpy - INFO - Chain [1] done processing

03:04:24 - cmdstanpy - INFO - Chain [1] start processing

03:04:24 - cmdstanpy - INFO - Chain [1] done processing

03:04:24 - cmdstanpy - INFO - Chain [1] start processing

03:04:24 - cmdstanpy - INFO - Chain [1] done processing

h= 6 Prophet          [cpu]  311.6 s

h= 6 Ridge            [cuda]   17.7 s

h= 6 Random Forest    [cuda]  736.6 s

h= 6 XGBoost          [cuda]  661.2 s

03:28:01 - cmdstanpy - INFO - Chain [1] start processing

03:28:02 - cmdstanpy - INFO - Chain [1] done processing

03:28:02 - cmdstanpy - INFO - Chain [1] start processing

03:28:03 - cmdstanpy - INFO - Chain [1] done processing

03:28:03 - cmdstanpy - INFO - Chain [1] start processing

03:28:04 - cmdstanpy - INFO - Chain [1] done processing

03:28:04 - cmdstanpy - INFO - Chain [1] start processing

03:28:05 - cmdstanpy - INFO - Chain [1] done processing

03:28:06 - cmdstanpy - INFO - Chain [1] start processing

03:28:06 - cmdstanpy - INFO - Chain [1] done processing

03:28:06 - cmdstanpy - INFO - Chain [1] start processing

03:28:07 - cmdstanpy - INFO - Chain [1] done processing

03:28:07 - cmdstanpy - INFO - Chain [1] start processing

03:28:08 - cmdstanpy - INFO - Chain [1] done processing

03:28:08 - cmdstanpy - INFO - Chain [1] start processing

03:28:09 - cmdstanpy - INFO - Chain [1] done processing

03:28:10 - cmdstanpy - INFO - Chain [1] start processing

03:28:10 - cmdstanpy - INFO - Chain [1] done processing

03:28:11 - cmdstanpy - INFO - Chain [1] start processing

03:28:11 - cmdstanpy - INFO - Chain [1] done processing

03:28:12 - cmdstanpy - INFO - Chain [1] start processing

03:28:12 - cmdstanpy - INFO - Chain [1] done processing

03:28:13 - cmdstanpy - INFO - Chain [1] start processing

03:28:13 - cmdstanpy - INFO - Chain [1] done processing

03:28:14 - cmdstanpy - INFO - Chain [1] start processing

03:28:14 - cmdstanpy - INFO - Chain [1] done processing

03:28:15 - cmdstanpy - INFO - Chain [1] start processing

03:28:15 - cmdstanpy - INFO - Chain [1] done processing

03:28:16 - cmdstanpy - INFO - Chain [1] start processing

03:28:16 - cmdstanpy - INFO - Chain [1] done processing

03:28:17 - cmdstanpy - INFO - Chain [1] start processing

03:28:17 - cmdstanpy - INFO - Chain [1] done processing

03:28:18 - cmdstanpy - INFO - Chain [1] start processing

03:28:18 - cmdstanpy - INFO - Chain [1] done processing

03:28:19 - cmdstanpy - INFO - Chain [1] start processing

03:28:19 - cmdstanpy - INFO - Chain [1] done processing

03:28:20 - cmdstanpy - INFO - Chain [1] start processing

03:28:20 - cmdstanpy - INFO - Chain [1] done processing

03:28:21 - cmdstanpy - INFO - Chain [1] start processing

03:28:21 - cmdstanpy - INFO - Chain [1] done processing

03:28:22 - cmdstanpy - INFO - Chain [1] start processing

03:28:22 - cmdstanpy - INFO - Chain [1] done processing

03:28:23 - cmdstanpy - INFO - Chain [1] start processing

03:28:23 - cmdstanpy - INFO - Chain [1] done processing

03:28:24 - cmdstanpy - INFO - Chain [1] start processing

03:28:24 - cmdstanpy - INFO - Chain [1] done processing

03:28:25 - cmdstanpy - INFO - Chain [1] start processing

03:28:25 - cmdstanpy - INFO - Chain [1] done processing

03:28:26 - cmdstanpy - INFO - Chain [1] start processing

03:28:27 - cmdstanpy - INFO - Chain [1] done processing

03:28:27 - cmdstanpy - INFO - Chain [1] start processing

03:28:28 - cmdstanpy - INFO - Chain [1] done processing

03:28:28 - cmdstanpy - INFO - Chain [1] start processing

03:28:29 - cmdstanpy - INFO - Chain [1] done processing

03:28:29 - cmdstanpy - INFO - Chain [1] start processing

03:28:30 - cmdstanpy - INFO - Chain [1] done processing

03:28:30 - cmdstanpy - INFO - Chain [1] start processing

03:28:31 - cmdstanpy - INFO - Chain [1] done processing

03:28:31 - cmdstanpy - INFO - Chain [1] start processing

03:28:32 - cmdstanpy - INFO - Chain [1] done processing

03:28:32 - cmdstanpy - INFO - Chain [1] start processing

03:28:33 - cmdstanpy - INFO - Chain [1] done processing

03:28:34 - cmdstanpy - INFO - Chain [1] start processing

03:28:34 - cmdstanpy - INFO - Chain [1] done processing

03:28:35 - cmdstanpy - INFO - Chain [1] start processing

03:28:35 - cmdstanpy - INFO - Chain [1] done processing

03:28:36 - cmdstanpy - INFO - Chain [1] start processing

03:28:36 - cmdstanpy - INFO - Chain [1] done processing

03:28:37 - cmdstanpy - INFO - Chain [1] start processing

03:28:37 - cmdstanpy - INFO - Chain [1] done processing

03:28:38 - cmdstanpy - INFO - Chain [1] start processing

03:28:39 - cmdstanpy - INFO - Chain [1] done processing

03:28:39 - cmdstanpy - INFO - Chain [1] start processing

03:28:40 - cmdstanpy - INFO - Chain [1] done processing

03:28:40 - cmdstanpy - INFO - Chain [1] start processing

03:28:41 - cmdstanpy - INFO - Chain [1] done processing

03:28:41 - cmdstanpy - INFO - Chain [1] start processing

03:28:42 - cmdstanpy - INFO - Chain [1] done processing

03:28:42 - cmdstanpy - INFO - Chain [1] start processing

03:28:43 - cmdstanpy - INFO - Chain [1] done processing

03:28:44 - cmdstanpy - INFO - Chain [1] start processing

03:28:44 - cmdstanpy - INFO - Chain [1] done processing

03:28:45 - cmdstanpy - INFO - Chain [1] start processing

03:28:45 - cmdstanpy - INFO - Chain [1] done processing

03:28:46 - cmdstanpy - INFO - Chain [1] start processing

03:28:46 - cmdstanpy - INFO - Chain [1] done processing

03:28:47 - cmdstanpy - INFO - Chain [1] start processing

03:28:48 - cmdstanpy - INFO - Chain [1] done processing

03:28:48 - cmdstanpy - INFO - Chain [1] start processing

03:28:49 - cmdstanpy - INFO - Chain [1] done processing

03:28:49 - cmdstanpy - INFO - Chain [1] start processing

03:28:50 - cmdstanpy - INFO - Chain [1] done processing

03:28:50 - cmdstanpy - INFO - Chain [1] start processing

03:28:51 - cmdstanpy - INFO - Chain [1] done processing

03:28:51 - cmdstanpy - INFO - Chain [1] start processing

03:28:52 - cmdstanpy - INFO - Chain [1] done processing

03:28:52 - cmdstanpy - INFO - Chain [1] start processing

03:28:53 - cmdstanpy - INFO - Chain [1] done processing

03:28:53 - cmdstanpy - INFO - Chain [1] start processing

03:28:54 - cmdstanpy - INFO - Chain [1] done processing

03:28:54 - cmdstanpy - INFO - Chain [1] start processing

03:28:55 - cmdstanpy - INFO - Chain [1] done processing

03:28:55 - cmdstanpy - INFO - Chain [1] start processing

03:28:56 - cmdstanpy - INFO - Chain [1] done processing

03:28:57 - cmdstanpy - INFO - Chain [1] start processing

03:28:57 - cmdstanpy - INFO - Chain [1] done processing

03:28:58 - cmdstanpy - INFO - Chain [1] start processing

03:28:59 - cmdstanpy - INFO - Chain [1] done processing

03:28:59 - cmdstanpy - INFO - Chain [1] start processing

03:29:00 - cmdstanpy - INFO - Chain [1] done processing

03:29:00 - cmdstanpy - INFO - Chain [1] start processing

03:29:01 - cmdstanpy - INFO - Chain [1] done processing

03:29:01 - cmdstanpy - INFO - Chain [1] start processing

03:29:02 - cmdstanpy - INFO - Chain [1] done processing

03:29:03 - cmdstanpy - INFO - Chain [1] start processing

03:29:03 - cmdstanpy - INFO - Chain [1] done processing

03:29:04 - cmdstanpy - INFO - Chain [1] start processing

03:29:04 - cmdstanpy - INFO - Chain [1] done processing

03:29:05 - cmdstanpy - INFO - Chain [1] start processing

03:29:05 - cmdstanpy - INFO - Chain [1] done processing

03:29:05 - cmdstanpy - INFO - Chain [1] start processing

03:29:06 - cmdstanpy - INFO - Chain [1] done processing

03:29:07 - cmdstanpy - INFO - Chain [1] start processing

03:29:07 - cmdstanpy - INFO - Chain [1] done processing

03:29:08 - cmdstanpy - INFO - Chain [1] start processing

03:29:09 - cmdstanpy - INFO - Chain [1] done processing

03:29:09 - cmdstanpy - INFO - Chain [1] start processing

03:29:10 - cmdstanpy - INFO - Chain [1] done processing

03:29:10 - cmdstanpy - INFO - Chain [1] start processing

03:29:11 - cmdstanpy - INFO - Chain [1] done processing

03:29:11 - cmdstanpy - INFO - Chain [1] start processing

03:29:11 - cmdstanpy - INFO - Chain [1] done processing

03:29:12 - cmdstanpy - INFO - Chain [1] start processing

03:29:13 - cmdstanpy - INFO - Chain [1] done processing

03:29:13 - cmdstanpy - INFO - Chain [1] start processing

03:29:14 - cmdstanpy - INFO - Chain [1] done processing

03:29:14 - cmdstanpy - INFO - Chain [1] start processing

03:29:15 - cmdstanpy - INFO - Chain [1] done processing

03:29:15 - cmdstanpy - INFO - Chain [1] start processing

03:29:16 - cmdstanpy - INFO - Chain [1] done processing

03:29:16 - cmdstanpy - INFO - Chain [1] start processing

03:29:17 - cmdstanpy - INFO - Chain [1] done processing

03:29:17 - cmdstanpy - INFO - Chain [1] start processing

03:29:18 - cmdstanpy - INFO - Chain [1] done processing

03:29:18 - cmdstanpy - INFO - Chain [1] start processing

03:29:19 - cmdstanpy - INFO - Chain [1] done processing

03:29:19 - cmdstanpy - INFO - Chain [1] start processing

03:29:20 - cmdstanpy - INFO - Chain [1] done processing

03:29:21 - cmdstanpy - INFO - Chain [1] start processing

03:29:22 - cmdstanpy - INFO - Chain [1] done processing

03:29:22 - cmdstanpy - INFO - Chain [1] start processing

03:29:23 - cmdstanpy - INFO - Chain [1] done processing

03:29:23 - cmdstanpy - INFO - Chain [1] start processing

03:29:24 - cmdstanpy - INFO - Chain [1] done processing

03:29:24 - cmdstanpy - INFO - Chain [1] start processing

03:29:26 - cmdstanpy - INFO - Chain [1] done processing

03:29:26 - cmdstanpy - INFO - Chain [1] start processing

03:29:27 - cmdstanpy - INFO - Chain [1] done processing

03:29:27 - cmdstanpy - INFO - Chain [1] start processing

03:29:28 - cmdstanpy - INFO - Chain [1] done processing

03:29:29 - cmdstanpy - INFO - Chain [1] start processing

03:29:30 - cmdstanpy - INFO - Chain [1] done processing

03:29:30 - cmdstanpy - INFO - Chain [1] start processing

03:29:31 - cmdstanpy - INFO - Chain [1] done processing

03:29:31 - cmdstanpy - INFO - Chain [1] start processing

03:29:32 - cmdstanpy - INFO - Chain [1] done processing

03:29:32 - cmdstanpy - INFO - Chain [1] start processing

03:29:33 - cmdstanpy - INFO - Chain [1] done processing

03:29:34 - cmdstanpy - INFO - Chain [1] start processing

03:29:34 - cmdstanpy - INFO - Chain [1] done processing

03:29:35 - cmdstanpy - INFO - Chain [1] start processing

03:29:36 - cmdstanpy - INFO - Chain [1] done processing

03:29:36 - cmdstanpy - INFO - Chain [1] start processing

03:29:37 - cmdstanpy - INFO - Chain [1] done processing

03:29:37 - cmdstanpy - INFO - Chain [1] start processing

03:29:39 - cmdstanpy - INFO - Chain [1] done processing

03:29:39 - cmdstanpy - INFO - Chain [1] start processing

03:29:40 - cmdstanpy - INFO - Chain [1] done processing

03:29:40 - cmdstanpy - INFO - Chain [1] start processing

03:29:41 - cmdstanpy - INFO - Chain [1] done processing

03:29:42 - cmdstanpy - INFO - Chain [1] start processing

03:29:43 - cmdstanpy - INFO - Chain [1] done processing

03:29:43 - cmdstanpy - INFO - Chain [1] start processing

03:29:44 - cmdstanpy - INFO - Chain [1] done processing

03:29:45 - cmdstanpy - INFO - Chain [1] start processing

03:29:46 - cmdstanpy - INFO - Chain [1] done processing

03:29:46 - cmdstanpy - INFO - Chain [1] start processing

03:29:47 - cmdstanpy - INFO - Chain [1] done processing

03:29:48 - cmdstanpy - INFO - Chain [1] start processing

03:29:49 - cmdstanpy - INFO - Chain [1] done processing

03:29:49 - cmdstanpy - INFO - Chain [1] start processing

03:29:50 - cmdstanpy - INFO - Chain [1] done processing

03:29:50 - cmdstanpy - INFO - Chain [1] start processing

03:29:51 - cmdstanpy - INFO - Chain [1] done processing

03:29:51 - cmdstanpy - INFO - Chain [1] start processing

03:29:53 - cmdstanpy - INFO - Chain [1] done processing

03:29:53 - cmdstanpy - INFO - Chain [1] start processing

03:29:54 - cmdstanpy - INFO - Chain [1] done processing

03:29:54 - cmdstanpy - INFO - Chain [1] start processing

03:29:56 - cmdstanpy - INFO - Chain [1] done processing

03:29:56 - cmdstanpy - INFO - Chain [1] start processing

03:29:57 - cmdstanpy - INFO - Chain [1] done processing

03:29:58 - cmdstanpy - INFO - Chain [1] start processing

03:29:59 - cmdstanpy - INFO - Chain [1] done processing

03:29:59 - cmdstanpy - INFO - Chain [1] start processing

03:30:00 - cmdstanpy - INFO - Chain [1] done processing

03:30:01 - cmdstanpy - INFO - Chain [1] start processing

03:30:02 - cmdstanpy - INFO - Chain [1] done processing

03:30:02 - cmdstanpy - INFO - Chain [1] start processing

03:30:03 - cmdstanpy - INFO - Chain [1] done processing

03:30:04 - cmdstanpy - INFO - Chain [1] start processing

03:30:05 - cmdstanpy - INFO - Chain [1] done processing

03:30:05 - cmdstanpy - INFO - Chain [1] start processing

03:30:06 - cmdstanpy - INFO - Chain [1] done processing

03:30:07 - cmdstanpy - INFO - Chain [1] start processing

03:30:08 - cmdstanpy - INFO - Chain [1] done processing

03:30:08 - cmdstanpy - INFO - Chain [1] start processing

03:30:09 - cmdstanpy - INFO - Chain [1] done processing

03:30:09 - cmdstanpy - INFO - Chain [1] start processing

03:30:11 - cmdstanpy - INFO - Chain [1] done processing

03:30:11 - cmdstanpy - INFO - Chain [1] start processing

03:30:12 - cmdstanpy - INFO - Chain [1] done processing

03:30:12 - cmdstanpy - INFO - Chain [1] start processing

03:30:14 - cmdstanpy - INFO - Chain [1] done processing

03:30:14 - cmdstanpy - INFO - Chain [1] start processing

03:30:15 - cmdstanpy - INFO - Chain [1] done processing

03:30:16 - cmdstanpy - INFO - Chain [1] start processing

03:30:17 - cmdstanpy - INFO - Chain [1] done processing

03:30:17 - cmdstanpy - INFO - Chain [1] start processing

03:30:18 - cmdstanpy - INFO - Chain [1] done processing

03:30:19 - cmdstanpy - INFO - Chain [1] start processing

03:30:20 - cmdstanpy - INFO - Chain [1] done processing

03:30:20 - cmdstanpy - INFO - Chain [1] start processing

03:30:21 - cmdstanpy - INFO - Chain [1] done processing

03:30:22 - cmdstanpy - INFO - Chain [1] start processing

03:30:23 - cmdstanpy - INFO - Chain [1] done processing

03:30:23 - cmdstanpy - INFO - Chain [1] start processing

03:30:24 - cmdstanpy - INFO - Chain [1] done processing

03:30:25 - cmdstanpy - INFO - Chain [1] start processing

03:30:26 - cmdstanpy - INFO - Chain [1] done processing

03:30:26 - cmdstanpy - INFO - Chain [1] start processing

03:30:27 - cmdstanpy - INFO - Chain [1] done processing

03:30:27 - cmdstanpy - INFO - Chain [1] start processing

03:30:28 - cmdstanpy - INFO - Chain [1] done processing

03:30:29 - cmdstanpy - INFO - Chain [1] start processing

03:30:30 - cmdstanpy - INFO - Chain [1] done processing

03:30:30 - cmdstanpy - INFO - Chain [1] start processing

03:30:31 - cmdstanpy - INFO - Chain [1] done processing

03:30:32 - cmdstanpy - INFO - Chain [1] start processing

03:30:33 - cmdstanpy - INFO - Chain [1] done processing

03:30:33 - cmdstanpy - INFO - Chain [1] start processing

03:30:34 - cmdstanpy - INFO - Chain [1] done processing

03:30:35 - cmdstanpy - INFO - Chain [1] start processing

03:30:35 - cmdstanpy - INFO - Chain [1] done processing

03:30:36 - cmdstanpy - INFO - Chain [1] start processing

03:30:37 - cmdstanpy - INFO - Chain [1] done processing

03:30:38 - cmdstanpy - INFO - Chain [1] start processing

03:30:39 - cmdstanpy - INFO - Chain [1] done processing

03:30:39 - cmdstanpy - INFO - Chain [1] start processing

03:30:40 - cmdstanpy - INFO - Chain [1] done processing

03:30:41 - cmdstanpy - INFO - Chain [1] start processing

03:30:42 - cmdstanpy - INFO - Chain [1] done processing

03:30:42 - cmdstanpy - INFO - Chain [1] start processing

03:30:43 - cmdstanpy - INFO - Chain [1] done processing

03:30:43 - cmdstanpy - INFO - Chain [1] start processing

03:30:45 - cmdstanpy - INFO - Chain [1] done processing

03:30:45 - cmdstanpy - INFO - Chain [1] start processing

03:30:46 - cmdstanpy - INFO - Chain [1] done processing

03:30:47 - cmdstanpy - INFO - Chain [1] start processing

03:30:48 - cmdstanpy - INFO - Chain [1] done processing

03:30:48 - cmdstanpy - INFO - Chain [1] start processing

03:30:49 - cmdstanpy - INFO - Chain [1] done processing

03:30:50 - cmdstanpy - INFO - Chain [1] start processing

03:30:51 - cmdstanpy - INFO - Chain [1] done processing

03:30:51 - cmdstanpy - INFO - Chain [1] start processing

03:30:52 - cmdstanpy - INFO - Chain [1] done processing

03:30:52 - cmdstanpy - INFO - Chain [1] start processing

03:30:53 - cmdstanpy - INFO - Chain [1] done processing

03:30:54 - cmdstanpy - INFO - Chain [1] start processing

03:30:55 - cmdstanpy - INFO - Chain [1] done processing

03:30:56 - cmdstanpy - INFO - Chain [1] start processing

03:30:57 - cmdstanpy - INFO - Chain [1] done processing

03:30:57 - cmdstanpy - INFO - Chain [1] start processing

03:30:58 - cmdstanpy - INFO - Chain [1] done processing

03:30:59 - cmdstanpy - INFO - Chain [1] start processing

03:31:00 - cmdstanpy - INFO - Chain [1] done processing

03:31:00 - cmdstanpy - INFO - Chain [1] start processing

03:31:01 - cmdstanpy - INFO - Chain [1] done processing

03:31:01 - cmdstanpy - INFO - Chain [1] start processing

03:31:02 - cmdstanpy - INFO - Chain [1] done processing

03:31:03 - cmdstanpy - INFO - Chain [1] start processing

03:31:05 - cmdstanpy - INFO - Chain [1] done processing

03:31:05 - cmdstanpy - INFO - Chain [1] start processing

03:31:06 - cmdstanpy - INFO - Chain [1] done processing

03:31:07 - cmdstanpy - INFO - Chain [1] start processing

03:31:09 - cmdstanpy - INFO - Chain [1] done processing

03:31:09 - cmdstanpy - INFO - Chain [1] start processing

03:31:11 - cmdstanpy - INFO - Chain [1] done processing

03:31:11 - cmdstanpy - INFO - Chain [1] start processing

03:31:13 - cmdstanpy - INFO - Chain [1] done processing

03:31:14 - cmdstanpy - INFO - Chain [1] start processing

03:31:15 - cmdstanpy - INFO - Chain [1] done processing

03:31:16 - cmdstanpy - INFO - Chain [1] start processing

03:31:17 - cmdstanpy - INFO - Chain [1] done processing

03:31:18 - cmdstanpy - INFO - Chain [1] start processing

03:31:19 - cmdstanpy - INFO - Chain [1] done processing

03:31:19 - cmdstanpy - INFO - Chain [1] start processing

03:31:21 - cmdstanpy - INFO - Chain [1] done processing

03:31:21 - cmdstanpy - INFO - Chain [1] start processing

03:31:23 - cmdstanpy - INFO - Chain [1] done processing

03:31:23 - cmdstanpy - INFO - Chain [1] start processing

03:31:25 - cmdstanpy - INFO - Chain [1] done processing

03:31:25 - cmdstanpy - INFO - Chain [1] start processing

03:31:26 - cmdstanpy - INFO - Chain [1] done processing

03:31:27 - cmdstanpy - INFO - Chain [1] start processing

03:31:28 - cmdstanpy - INFO - Chain [1] done processing

03:31:29 - cmdstanpy - INFO - Chain [1] start processing

03:31:30 - cmdstanpy - INFO - Chain [1] done processing

03:31:30 - cmdstanpy - INFO - Chain [1] start processing

03:31:32 - cmdstanpy - INFO - Chain [1] done processing

03:31:32 - cmdstanpy - INFO - Chain [1] start processing

03:31:34 - cmdstanpy - INFO - Chain [1] done processing

03:31:35 - cmdstanpy - INFO - Chain [1] start processing

03:31:37 - cmdstanpy - INFO - Chain [1] done processing

03:31:37 - cmdstanpy - INFO - Chain [1] start processing

03:31:38 - cmdstanpy - INFO - Chain [1] done processing

03:31:39 - cmdstanpy - INFO - Chain [1] start processing

03:31:40 - cmdstanpy - INFO - Chain [1] done processing

03:31:41 - cmdstanpy - INFO - Chain [1] start processing

03:31:42 - cmdstanpy - INFO - Chain [1] done processing

03:31:43 - cmdstanpy - INFO - Chain [1] start processing

03:31:46 - cmdstanpy - INFO - Chain [1] done processing

03:31:46 - cmdstanpy - INFO - Chain [1] start processing

03:31:48 - cmdstanpy - INFO - Chain [1] done processing

03:31:48 - cmdstanpy - INFO - Chain [1] start processing

03:31:50 - cmdstanpy - INFO - Chain [1] done processing

03:31:51 - cmdstanpy - INFO - Chain [1] start processing

03:31:52 - cmdstanpy - INFO - Chain [1] done processing

03:31:52 - cmdstanpy - INFO - Chain [1] start processing

03:31:53 - cmdstanpy - INFO - Chain [1] done processing

03:31:54 - cmdstanpy - INFO - Chain [1] start processing

03:31:55 - cmdstanpy - INFO - Chain [1] done processing

03:31:55 - cmdstanpy - INFO - Chain [1] start processing

03:31:57 - cmdstanpy - INFO - Chain [1] done processing

03:31:58 - cmdstanpy - INFO - Chain [1] start processing

03:31:59 - cmdstanpy - INFO - Chain [1] done processing

03:32:00 - cmdstanpy - INFO - Chain [1] start processing

03:32:02 - cmdstanpy - INFO - Chain [1] done processing

03:32:02 - cmdstanpy - INFO - Chain [1] start processing

03:32:03 - cmdstanpy - INFO - Chain [1] done processing

03:32:03 - cmdstanpy - INFO - Chain [1] start processing

03:32:05 - cmdstanpy - INFO - Chain [1] done processing

03:32:05 - cmdstanpy - INFO - Chain [1] start processing

03:32:07 - cmdstanpy - INFO - Chain [1] done processing

03:32:07 - cmdstanpy - INFO - Chain [1] start processing

03:32:08 - cmdstanpy - INFO - Chain [1] done processing

03:32:09 - cmdstanpy - INFO - Chain [1] start processing

03:32:10 - cmdstanpy - INFO - Chain [1] done processing

03:32:11 - cmdstanpy - INFO - Chain [1] start processing

03:32:12 - cmdstanpy - INFO - Chain [1] done processing

03:32:13 - cmdstanpy - INFO - Chain [1] start processing

03:32:14 - cmdstanpy - INFO - Chain [1] done processing

03:32:15 - cmdstanpy - INFO - Chain [1] start processing

03:32:16 - cmdstanpy - INFO - Chain [1] done processing

03:32:17 - cmdstanpy - INFO - Chain [1] start processing

03:32:19 - cmdstanpy - INFO - Chain [1] done processing

03:32:19 - cmdstanpy - INFO - Chain [1] start processing

03:32:22 - cmdstanpy - INFO - Chain [1] done processing

03:32:22 - cmdstanpy - INFO - Chain [1] start processing

03:32:24 - cmdstanpy - INFO - Chain [1] done processing

03:32:24 - cmdstanpy - INFO - Chain [1] start processing

03:32:27 - cmdstanpy - INFO - Chain [1] done processing

03:32:27 - cmdstanpy - INFO - Chain [1] start processing

03:32:28 - cmdstanpy - INFO - Chain [1] done processing

03:32:28 - cmdstanpy - INFO - Chain [1] start processing

03:32:30 - cmdstanpy - INFO - Chain [1] done processing

03:32:31 - cmdstanpy - INFO - Chain [1] start processing

03:32:32 - cmdstanpy - INFO - Chain [1] done processing

03:32:32 - cmdstanpy - INFO - Chain [1] start processing

03:32:34 - cmdstanpy - INFO - Chain [1] done processing

03:32:34 - cmdstanpy - INFO - Chain [1] start processing

03:32:36 - cmdstanpy - INFO - Chain [1] done processing

03:32:37 - cmdstanpy - INFO - Chain [1] start processing

03:32:38 - cmdstanpy - INFO - Chain [1] done processing

03:32:39 - cmdstanpy - INFO - Chain [1] start processing

03:32:40 - cmdstanpy - INFO - Chain [1] done processing

03:32:41 - cmdstanpy - INFO - Chain [1] start processing

03:32:42 - cmdstanpy - INFO - Chain [1] done processing

03:32:43 - cmdstanpy - INFO - Chain [1] start processing

03:32:44 - cmdstanpy - INFO - Chain [1] done processing

03:32:45 - cmdstanpy - INFO - Chain [1] start processing

03:32:46 - cmdstanpy - INFO - Chain [1] done processing

03:32:47 - cmdstanpy - INFO - Chain [1] start processing

03:32:49 - cmdstanpy - INFO - Chain [1] done processing

03:32:49 - cmdstanpy - INFO - Chain [1] start processing

03:32:52 - cmdstanpy - INFO - Chain [1] done processing

03:32:52 - cmdstanpy - INFO - Chain [1] start processing

03:32:53 - cmdstanpy - INFO - Chain [1] done processing

03:32:53 - cmdstanpy - INFO - Chain [1] start processing

03:32:55 - cmdstanpy - INFO - Chain [1] done processing

03:32:56 - cmdstanpy - INFO - Chain [1] start processing

03:32:57 - cmdstanpy - INFO - Chain [1] done processing

03:32:58 - cmdstanpy - INFO - Chain [1] start processing

03:32:59 - cmdstanpy - INFO - Chain [1] done processing

03:33:00 - cmdstanpy - INFO - Chain [1] start processing

03:33:02 - cmdstanpy - INFO - Chain [1] done processing

03:33:03 - cmdstanpy - INFO - Chain [1] start processing

03:33:04 - cmdstanpy - INFO - Chain [1] done processing

03:33:05 - cmdstanpy - INFO - Chain [1] start processing

03:33:06 - cmdstanpy - INFO - Chain [1] done processing

03:33:07 - cmdstanpy - INFO - Chain [1] start processing

03:33:09 - cmdstanpy - INFO - Chain [1] done processing

03:33:09 - cmdstanpy - INFO - Chain [1] start processing

03:33:11 - cmdstanpy - INFO - Chain [1] done processing

03:33:11 - cmdstanpy - INFO - Chain [1] start processing

03:33:13 - cmdstanpy - INFO - Chain [1] done processing

03:33:13 - cmdstanpy - INFO - Chain [1] start processing

03:33:16 - cmdstanpy - INFO - Chain [1] done processing

03:33:16 - cmdstanpy - INFO - Chain [1] start processing

03:33:18 - cmdstanpy - INFO - Chain [1] done processing

03:33:18 - cmdstanpy - INFO - Chain [1] start processing

03:33:20 - cmdstanpy - INFO - Chain [1] done processing

03:33:20 - cmdstanpy - INFO - Chain [1] start processing

03:33:22 - cmdstanpy - INFO - Chain [1] done processing

03:33:23 - cmdstanpy - INFO - Chain [1] start processing

03:33:24 - cmdstanpy - INFO - Chain [1] done processing

03:33:25 - cmdstanpy - INFO - Chain [1] start processing

03:33:26 - cmdstanpy - INFO - Chain [1] done processing

03:33:27 - cmdstanpy - INFO - Chain [1] start processing

03:33:28 - cmdstanpy - INFO - Chain [1] done processing

03:33:29 - cmdstanpy - INFO - Chain [1] start processing

03:33:30 - cmdstanpy - INFO - Chain [1] done processing

03:33:31 - cmdstanpy - INFO - Chain [1] start processing

03:33:33 - cmdstanpy - INFO - Chain [1] done processing

03:33:33 - cmdstanpy - INFO - Chain [1] start processing

03:33:35 - cmdstanpy - INFO - Chain [1] done processing

03:33:35 - cmdstanpy - INFO - Chain [1] start processing

03:33:36 - cmdstanpy - INFO - Chain [1] done processing

03:33:37 - cmdstanpy - INFO - Chain [1] start processing

03:33:39 - cmdstanpy - INFO - Chain [1] done processing

03:33:39 - cmdstanpy - INFO - Chain [1] start processing

03:33:40 - cmdstanpy - INFO - Chain [1] done processing

03:33:41 - cmdstanpy - INFO - Chain [1] start processing

03:33:43 - cmdstanpy - INFO - Chain [1] done processing

03:33:44 - cmdstanpy - INFO - Chain [1] start processing

03:33:45 - cmdstanpy - INFO - Chain [1] done processing

03:33:46 - cmdstanpy - INFO - Chain [1] start processing

03:33:48 - cmdstanpy - INFO - Chain [1] done processing

03:33:48 - cmdstanpy - INFO - Chain [1] start processing

03:33:50 - cmdstanpy - INFO - Chain [1] done processing

03:33:50 - cmdstanpy - INFO - Chain [1] start processing

03:33:52 - cmdstanpy - INFO - Chain [1] done processing

03:33:52 - cmdstanpy - INFO - Chain [1] start processing

03:33:54 - cmdstanpy - INFO - Chain [1] done processing

03:33:55 - cmdstanpy - INFO - Chain [1] start processing

03:33:57 - cmdstanpy - INFO - Chain [1] done processing

03:33:57 - cmdstanpy - INFO - Chain [1] start processing

03:33:59 - cmdstanpy - INFO - Chain [1] done processing

03:33:59 - cmdstanpy - INFO - Chain [1] start processing

03:34:01 - cmdstanpy - INFO - Chain [1] done processing

03:34:02 - cmdstanpy - INFO - Chain [1] start processing

03:34:04 - cmdstanpy - INFO - Chain [1] done processing

03:34:04 - cmdstanpy - INFO - Chain [1] start processing

03:34:06 - cmdstanpy - INFO - Chain [1] done processing

03:34:06 - cmdstanpy - INFO - Chain [1] start processing

03:34:08 - cmdstanpy - INFO - Chain [1] done processing

03:34:08 - cmdstanpy - INFO - Chain [1] start processing

03:34:10 - cmdstanpy - INFO - Chain [1] done processing

03:34:10 - cmdstanpy - INFO - Chain [1] start processing

03:34:12 - cmdstanpy - INFO - Chain [1] done processing

03:34:13 - cmdstanpy - INFO - Chain [1] start processing

03:34:14 - cmdstanpy - INFO - Chain [1] done processing

03:34:15 - cmdstanpy - INFO - Chain [1] start processing

03:34:17 - cmdstanpy - INFO - Chain [1] done processing

03:34:17 - cmdstanpy - INFO - Chain [1] start processing

03:34:19 - cmdstanpy - INFO - Chain [1] done processing

03:34:20 - cmdstanpy - INFO - Chain [1] start processing

03:34:21 - cmdstanpy - INFO - Chain [1] done processing

03:34:22 - cmdstanpy - INFO - Chain [1] start processing

03:34:24 - cmdstanpy - INFO - Chain [1] done processing

03:34:24 - cmdstanpy - INFO - Chain [1] start processing

03:34:26 - cmdstanpy - INFO - Chain [1] done processing

03:34:26 - cmdstanpy - INFO - Chain [1] start processing

03:34:28 - cmdstanpy - INFO - Chain [1] done processing

03:34:28 - cmdstanpy - INFO - Chain [1] start processing

03:34:30 - cmdstanpy - INFO - Chain [1] done processing

03:34:30 - cmdstanpy - INFO - Chain [1] start processing

03:34:32 - cmdstanpy - INFO - Chain [1] done processing

03:34:33 - cmdstanpy - INFO - Chain [1] start processing

03:34:34 - cmdstanpy - INFO - Chain [1] done processing

03:34:35 - cmdstanpy - INFO - Chain [1] start processing

03:34:37 - cmdstanpy - INFO - Chain [1] done processing

03:34:38 - cmdstanpy - INFO - Chain [1] start processing

03:34:40 - cmdstanpy - INFO - Chain [1] done processing

03:34:40 - cmdstanpy - INFO - Chain [1] start processing

03:34:42 - cmdstanpy - INFO - Chain [1] done processing

03:34:42 - cmdstanpy - INFO - Chain [1] start processing

03:34:44 - cmdstanpy - INFO - Chain [1] done processing

03:34:44 - cmdstanpy - INFO - Chain [1] start processing

03:34:46 - cmdstanpy - INFO - Chain [1] done processing

03:34:47 - cmdstanpy - INFO - Chain [1] start processing

03:34:48 - cmdstanpy - INFO - Chain [1] done processing

03:34:49 - cmdstanpy - INFO - Chain [1] start processing

03:34:52 - cmdstanpy - INFO - Chain [1] done processing

03:34:52 - cmdstanpy - INFO - Chain [1] start processing

03:34:54 - cmdstanpy - INFO - Chain [1] done processing

03:34:54 - cmdstanpy - INFO - Chain [1] start processing

03:34:56 - cmdstanpy - INFO - Chain [1] done processing

03:34:57 - cmdstanpy - INFO - Chain [1] start processing

03:34:58 - cmdstanpy - INFO - Chain [1] done processing

03:34:59 - cmdstanpy - INFO - Chain [1] start processing

03:35:01 - cmdstanpy - INFO - Chain [1] done processing

03:35:01 - cmdstanpy - INFO - Chain [1] start processing

03:35:03 - cmdstanpy - INFO - Chain [1] done processing

03:35:03 - cmdstanpy - INFO - Chain [1] start processing

03:35:05 - cmdstanpy - INFO - Chain [1] done processing

03:35:06 - cmdstanpy - INFO - Chain [1] start processing

03:35:08 - cmdstanpy - INFO - Chain [1] done processing

03:35:08 - cmdstanpy - INFO - Chain [1] start processing

03:35:10 - cmdstanpy - INFO - Chain [1] done processing

03:35:11 - cmdstanpy - INFO - Chain [1] start processing

03:35:12 - cmdstanpy - INFO - Chain [1] done processing

03:35:13 - cmdstanpy - INFO - Chain [1] start processing

03:35:15 - cmdstanpy - INFO - Chain [1] done processing

03:35:15 - cmdstanpy - INFO - Chain [1] start processing

03:35:18 - cmdstanpy - INFO - Chain [1] done processing

03:35:18 - cmdstanpy - INFO - Chain [1] start processing

03:35:21 - cmdstanpy - INFO - Chain [1] done processing

03:35:21 - cmdstanpy - INFO - Chain [1] start processing

03:35:23 - cmdstanpy - INFO - Chain [1] done processing

03:35:24 - cmdstanpy - INFO - Chain [1] start processing

03:35:26 - cmdstanpy - INFO - Chain [1] done processing

03:35:26 - cmdstanpy - INFO - Chain [1] start processing

03:35:28 - cmdstanpy - INFO - Chain [1] done processing

03:35:28 - cmdstanpy - INFO - Chain [1] start processing

03:35:31 - cmdstanpy - INFO - Chain [1] done processing

03:35:31 - cmdstanpy - INFO - Chain [1] start processing

03:35:33 - cmdstanpy - INFO - Chain [1] done processing

03:35:34 - cmdstanpy - INFO - Chain [1] start processing

03:35:35 - cmdstanpy - INFO - Chain [1] done processing

03:35:36 - cmdstanpy - INFO - Chain [1] start processing

03:35:37 - cmdstanpy - INFO - Chain [1] done processing

03:35:38 - cmdstanpy - INFO - Chain [1] start processing

03:35:40 - cmdstanpy - INFO - Chain [1] done processing

03:35:40 - cmdstanpy - INFO - Chain [1] start processing

03:35:42 - cmdstanpy - INFO - Chain [1] done processing

03:35:43 - cmdstanpy - INFO - Chain [1] start processing

03:35:45 - cmdstanpy - INFO - Chain [1] done processing

03:35:45 - cmdstanpy - INFO - Chain [1] start processing

03:35:48 - cmdstanpy - INFO - Chain [1] done processing

03:35:48 - cmdstanpy - INFO - Chain [1] start processing

03:35:50 - cmdstanpy - INFO - Chain [1] done processing

03:35:51 - cmdstanpy - INFO - Chain [1] start processing

03:35:53 - cmdstanpy - INFO - Chain [1] done processing

03:35:53 - cmdstanpy - INFO - Chain [1] start processing

03:35:55 - cmdstanpy - INFO - Chain [1] done processing

03:35:56 - cmdstanpy - INFO - Chain [1] start processing

03:35:58 - cmdstanpy - INFO - Chain [1] done processing

03:35:58 - cmdstanpy - INFO - Chain [1] start processing

03:36:00 - cmdstanpy - INFO - Chain [1] done processing

03:36:00 - cmdstanpy - INFO - Chain [1] start processing

03:36:03 - cmdstanpy - INFO - Chain [1] done processing

03:36:03 - cmdstanpy - INFO - Chain [1] start processing

03:36:05 - cmdstanpy - INFO - Chain [1] done processing

03:36:06 - cmdstanpy - INFO - Chain [1] start processing

03:36:07 - cmdstanpy - INFO - Chain [1] done processing

03:36:07 - cmdstanpy - INFO - Chain [1] start processing

03:36:09 - cmdstanpy - INFO - Chain [1] done processing

03:36:09 - cmdstanpy - INFO - Chain [1] start processing

03:36:12 - cmdstanpy - INFO - Chain [1] done processing

03:36:12 - cmdstanpy - INFO - Chain [1] start processing

03:36:13 - cmdstanpy - INFO - Chain [1] done processing

03:36:14 - cmdstanpy - INFO - Chain [1] start processing

03:36:16 - cmdstanpy - INFO - Chain [1] done processing

03:36:16 - cmdstanpy - INFO - Chain [1] start processing

03:36:18 - cmdstanpy - INFO - Chain [1] done processing

h=12: Prophet cps elegido 0.5
h=12 Paseo aleatorio  [cpu]    0.0 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

h=12 ARIMA            [cpu]   56.6 s

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
C:\miniconda3\envs\deeplearning\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)

h=12 VAR              [cpu]    0.6 s

03:37:16 - cmdstanpy - INFO - Chain [1] start processing

03:37:17 - cmdstanpy - INFO - Chain [1] done processing

03:37:18 - cmdstanpy - INFO - Chain [1] start processing

03:37:20 - cmdstanpy - INFO - Chain [1] done processing

03:37:20 - cmdstanpy - INFO - Chain [1] start processing

03:37:22 - cmdstanpy - INFO - Chain [1] done processing

03:37:22 - cmdstanpy - INFO - Chain [1] start processing

03:37:24 - cmdstanpy - INFO - Chain [1] done processing

03:37:25 - cmdstanpy - INFO - Chain [1] start processing

03:37:28 - cmdstanpy - INFO - Chain [1] done processing

03:37:28 - cmdstanpy - INFO - Chain [1] start processing

03:37:31 - cmdstanpy - INFO - Chain [1] done processing

03:37:31 - cmdstanpy - INFO - Chain [1] start processing

03:37:32 - cmdstanpy - INFO - Chain [1] done processing

03:37:33 - cmdstanpy - INFO - Chain [1] start processing

03:37:35 - cmdstanpy - INFO - Chain [1] done processing

03:37:35 - cmdstanpy - INFO - Chain [1] start processing

03:37:37 - cmdstanpy - INFO - Chain [1] done processing

03:37:38 - cmdstanpy - INFO - Chain [1] start processing

03:37:40 - cmdstanpy - INFO - Chain [1] done processing

03:37:40 - cmdstanpy - INFO - Chain [1] start processing

03:37:42 - cmdstanpy - INFO - Chain [1] done processing

03:37:43 - cmdstanpy - INFO - Chain [1] start processing

03:37:45 - cmdstanpy - INFO - Chain [1] done processing

03:37:45 - cmdstanpy - INFO - Chain [1] start processing

03:37:48 - cmdstanpy - INFO - Chain [1] done processing

03:37:48 - cmdstanpy - INFO - Chain [1] start processing

03:37:50 - cmdstanpy - INFO - Chain [1] done processing

03:37:50 - cmdstanpy - INFO - Chain [1] start processing

03:37:52 - cmdstanpy - INFO - Chain [1] done processing

03:37:52 - cmdstanpy - INFO - Chain [1] start processing

03:37:54 - cmdstanpy - INFO - Chain [1] done processing

03:37:55 - cmdstanpy - INFO - Chain [1] start processing

03:37:57 - cmdstanpy - INFO - Chain [1] done processing

03:37:57 - cmdstanpy - INFO - Chain [1] start processing

03:38:00 - cmdstanpy - INFO - Chain [1] done processing

03:38:01 - cmdstanpy - INFO - Chain [1] start processing

03:38:03 - cmdstanpy - INFO - Chain [1] done processing

03:38:03 - cmdstanpy - INFO - Chain [1] start processing

03:38:05 - cmdstanpy - INFO - Chain [1] done processing

03:38:05 - cmdstanpy - INFO - Chain [1] start processing

03:38:07 - cmdstanpy - INFO - Chain [1] done processing

03:38:08 - cmdstanpy - INFO - Chain [1] start processing

03:38:09 - cmdstanpy - INFO - Chain [1] done processing

03:38:10 - cmdstanpy - INFO - Chain [1] start processing

03:38:12 - cmdstanpy - INFO - Chain [1] done processing

03:38:13 - cmdstanpy - INFO - Chain [1] start processing

03:38:16 - cmdstanpy - INFO - Chain [1] done processing

03:38:16 - cmdstanpy - INFO - Chain [1] start processing

03:38:18 - cmdstanpy - INFO - Chain [1] done processing

03:38:18 - cmdstanpy - INFO - Chain [1] start processing

03:38:20 - cmdstanpy - INFO - Chain [1] done processing

03:38:20 - cmdstanpy - INFO - Chain [1] start processing

03:38:22 - cmdstanpy - INFO - Chain [1] done processing

03:38:22 - cmdstanpy - INFO - Chain [1] start processing

03:38:25 - cmdstanpy - INFO - Chain [1] done processing

03:38:26 - cmdstanpy - INFO - Chain [1] start processing

03:38:28 - cmdstanpy - INFO - Chain [1] done processing

03:38:28 - cmdstanpy - INFO - Chain [1] start processing

03:38:30 - cmdstanpy - INFO - Chain [1] done processing

03:38:31 - cmdstanpy - INFO - Chain [1] start processing

03:38:33 - cmdstanpy - INFO - Chain [1] done processing

03:38:34 - cmdstanpy - INFO - Chain [1] start processing

03:38:36 - cmdstanpy - INFO - Chain [1] done processing

03:38:36 - cmdstanpy - INFO - Chain [1] start processing

03:38:38 - cmdstanpy - INFO - Chain [1] done processing

03:38:38 - cmdstanpy - INFO - Chain [1] start processing

03:38:40 - cmdstanpy - INFO - Chain [1] done processing

03:38:40 - cmdstanpy - INFO - Chain [1] start processing

03:38:43 - cmdstanpy - INFO - Chain [1] done processing

03:38:43 - cmdstanpy - INFO - Chain [1] start processing

03:38:46 - cmdstanpy - INFO - Chain [1] done processing

03:38:46 - cmdstanpy - INFO - Chain [1] start processing

03:38:49 - cmdstanpy - INFO - Chain [1] done processing

03:38:50 - cmdstanpy - INFO - Chain [1] start processing

03:38:52 - cmdstanpy - INFO - Chain [1] done processing

03:38:53 - cmdstanpy - INFO - Chain [1] start processing

03:38:55 - cmdstanpy - INFO - Chain [1] done processing

03:38:55 - cmdstanpy - INFO - Chain [1] start processing

03:38:57 - cmdstanpy - INFO - Chain [1] done processing

03:38:58 - cmdstanpy - INFO - Chain [1] start processing

03:39:01 - cmdstanpy - INFO - Chain [1] done processing

03:39:01 - cmdstanpy - INFO - Chain [1] start processing

03:39:04 - cmdstanpy - INFO - Chain [1] done processing

03:39:04 - cmdstanpy - INFO - Chain [1] start processing

03:39:06 - cmdstanpy - INFO - Chain [1] done processing

03:39:07 - cmdstanpy - INFO - Chain [1] start processing

03:39:09 - cmdstanpy - INFO - Chain [1] done processing

03:39:09 - cmdstanpy - INFO - Chain [1] start processing

03:39:11 - cmdstanpy - INFO - Chain [1] done processing

03:39:11 - cmdstanpy - INFO - Chain [1] start processing

03:39:13 - cmdstanpy - INFO - Chain [1] done processing

03:39:14 - cmdstanpy - INFO - Chain [1] start processing

03:39:16 - cmdstanpy - INFO - Chain [1] done processing

03:39:16 - cmdstanpy - INFO - Chain [1] start processing

03:39:18 - cmdstanpy - INFO - Chain [1] done processing

03:39:18 - cmdstanpy - INFO - Chain [1] start processing

03:39:21 - cmdstanpy - INFO - Chain [1] done processing

03:39:21 - cmdstanpy - INFO - Chain [1] start processing

03:39:23 - cmdstanpy - INFO - Chain [1] done processing

03:39:24 - cmdstanpy - INFO - Chain [1] start processing

03:39:25 - cmdstanpy - INFO - Chain [1] done processing

03:39:26 - cmdstanpy - INFO - Chain [1] start processing

03:39:28 - cmdstanpy - INFO - Chain [1] done processing

03:39:28 - cmdstanpy - INFO - Chain [1] start processing

03:39:31 - cmdstanpy - INFO - Chain [1] done processing

03:39:32 - cmdstanpy - INFO - Chain [1] start processing

03:39:34 - cmdstanpy - INFO - Chain [1] done processing

03:39:35 - cmdstanpy - INFO - Chain [1] start processing

03:39:36 - cmdstanpy - INFO - Chain [1] done processing

03:39:37 - cmdstanpy - INFO - Chain [1] start processing

03:39:39 - cmdstanpy - INFO - Chain [1] done processing

03:39:40 - cmdstanpy - INFO - Chain [1] start processing

03:39:42 - cmdstanpy - INFO - Chain [1] done processing

03:39:42 - cmdstanpy - INFO - Chain [1] start processing

03:39:44 - cmdstanpy - INFO - Chain [1] done processing

03:39:45 - cmdstanpy - INFO - Chain [1] start processing

03:39:47 - cmdstanpy - INFO - Chain [1] done processing

03:39:47 - cmdstanpy - INFO - Chain [1] start processing

03:39:49 - cmdstanpy - INFO - Chain [1] done processing

03:39:50 - cmdstanpy - INFO - Chain [1] start processing

03:39:52 - cmdstanpy - INFO - Chain [1] done processing

03:39:53 - cmdstanpy - INFO - Chain [1] start processing

03:39:55 - cmdstanpy - INFO - Chain [1] done processing

03:39:55 - cmdstanpy - INFO - Chain [1] start processing

03:39:58 - cmdstanpy - INFO - Chain [1] done processing

03:39:58 - cmdstanpy - INFO - Chain [1] start processing

03:40:00 - cmdstanpy - INFO - Chain [1] done processing

03:40:00 - cmdstanpy - INFO - Chain [1] start processing

03:40:03 - cmdstanpy - INFO - Chain [1] done processing

03:40:03 - cmdstanpy - INFO - Chain [1] start processing

03:40:06 - cmdstanpy - INFO - Chain [1] done processing

03:40:06 - cmdstanpy - INFO - Chain [1] start processing

03:40:09 - cmdstanpy - INFO - Chain [1] done processing

03:40:09 - cmdstanpy - INFO - Chain [1] start processing

03:40:11 - cmdstanpy - INFO - Chain [1] done processing

03:40:12 - cmdstanpy - INFO - Chain [1] start processing

03:40:13 - cmdstanpy - INFO - Chain [1] done processing

03:40:14 - cmdstanpy - INFO - Chain [1] start processing

03:40:16 - cmdstanpy - INFO - Chain [1] done processing

03:40:16 - cmdstanpy - INFO - Chain [1] start processing

03:40:19 - cmdstanpy - INFO - Chain [1] done processing

03:40:20 - cmdstanpy - INFO - Chain [1] start processing

03:40:22 - cmdstanpy - INFO - Chain [1] done processing

03:40:22 - cmdstanpy - INFO - Chain [1] start processing

03:40:25 - cmdstanpy - INFO - Chain [1] done processing

03:40:26 - cmdstanpy - INFO - Chain [1] start processing

03:40:27 - cmdstanpy - INFO - Chain [1] done processing

03:40:28 - cmdstanpy - INFO - Chain [1] start processing

03:40:30 - cmdstanpy - INFO - Chain [1] done processing

03:40:30 - cmdstanpy - INFO - Chain [1] start processing

03:40:32 - cmdstanpy - INFO - Chain [1] done processing

03:40:32 - cmdstanpy - INFO - Chain [1] start processing

03:40:35 - cmdstanpy - INFO - Chain [1] done processing

03:40:36 - cmdstanpy - INFO - Chain [1] start processing

03:40:38 - cmdstanpy - INFO - Chain [1] done processing

03:40:39 - cmdstanpy - INFO - Chain [1] start processing

03:40:42 - cmdstanpy - INFO - Chain [1] done processing

03:40:42 - cmdstanpy - INFO - Chain [1] start processing

03:40:44 - cmdstanpy - INFO - Chain [1] done processing

03:40:44 - cmdstanpy - INFO - Chain [1] start processing

03:40:46 - cmdstanpy - INFO - Chain [1] done processing

03:40:46 - cmdstanpy - INFO - Chain [1] start processing

03:40:49 - cmdstanpy - INFO - Chain [1] done processing

03:40:49 - cmdstanpy - INFO - Chain [1] start processing

03:40:52 - cmdstanpy - INFO - Chain [1] done processing

03:40:52 - cmdstanpy - INFO - Chain [1] start processing

03:40:54 - cmdstanpy - INFO - Chain [1] done processing

03:40:55 - cmdstanpy - INFO - Chain [1] start processing

03:40:56 - cmdstanpy - INFO - Chain [1] done processing

03:40:57 - cmdstanpy - INFO - Chain [1] start processing

03:40:59 - cmdstanpy - INFO - Chain [1] done processing

03:40:59 - cmdstanpy - INFO - Chain [1] start processing

03:41:01 - cmdstanpy - INFO - Chain [1] done processing

03:41:02 - cmdstanpy - INFO - Chain [1] start processing

03:41:04 - cmdstanpy - INFO - Chain [1] done processing

03:41:04 - cmdstanpy - INFO - Chain [1] start processing

03:41:07 - cmdstanpy - INFO - Chain [1] done processing

03:41:08 - cmdstanpy - INFO - Chain [1] start processing

03:41:11 - cmdstanpy - INFO - Chain [1] done processing

03:41:11 - cmdstanpy - INFO - Chain [1] start processing

03:41:13 - cmdstanpy - INFO - Chain [1] done processing

03:41:14 - cmdstanpy - INFO - Chain [1] start processing

03:41:17 - cmdstanpy - INFO - Chain [1] done processing

03:41:17 - cmdstanpy - INFO - Chain [1] start processing

03:41:19 - cmdstanpy - INFO - Chain [1] done processing

03:41:20 - cmdstanpy - INFO - Chain [1] start processing

03:41:22 - cmdstanpy - INFO - Chain [1] done processing

03:41:22 - cmdstanpy - INFO - Chain [1] start processing

03:41:25 - cmdstanpy - INFO - Chain [1] done processing

03:41:25 - cmdstanpy - INFO - Chain [1] start processing

03:41:27 - cmdstanpy - INFO - Chain [1] done processing

03:41:28 - cmdstanpy - INFO - Chain [1] start processing

03:41:30 - cmdstanpy - INFO - Chain [1] done processing

03:41:31 - cmdstanpy - INFO - Chain [1] start processing

03:41:33 - cmdstanpy - INFO - Chain [1] done processing

03:41:34 - cmdstanpy - INFO - Chain [1] start processing

03:41:36 - cmdstanpy - INFO - Chain [1] done processing

03:41:37 - cmdstanpy - INFO - Chain [1] start processing

03:41:39 - cmdstanpy - INFO - Chain [1] done processing

03:41:39 - cmdstanpy - INFO - Chain [1] start processing

03:41:42 - cmdstanpy - INFO - Chain [1] done processing

03:41:43 - cmdstanpy - INFO - Chain [1] start processing

03:41:44 - cmdstanpy - INFO - Chain [1] done processing

03:41:45 - cmdstanpy - INFO - Chain [1] start processing

03:41:47 - cmdstanpy - INFO - Chain [1] done processing

03:41:47 - cmdstanpy - INFO - Chain [1] start processing

03:41:50 - cmdstanpy - INFO - Chain [1] done processing

03:41:50 - cmdstanpy - INFO - Chain [1] start processing

03:41:52 - cmdstanpy - INFO - Chain [1] done processing

03:41:53 - cmdstanpy - INFO - Chain [1] start processing

03:41:55 - cmdstanpy - INFO - Chain [1] done processing

03:41:55 - cmdstanpy - INFO - Chain [1] start processing

03:41:58 - cmdstanpy - INFO - Chain [1] done processing

03:41:58 - cmdstanpy - INFO - Chain [1] start processing

03:42:01 - cmdstanpy - INFO - Chain [1] done processing

03:42:01 - cmdstanpy - INFO - Chain [1] start processing

03:42:04 - cmdstanpy - INFO - Chain [1] done processing

03:42:04 - cmdstanpy - INFO - Chain [1] start processing

03:42:07 - cmdstanpy - INFO - Chain [1] done processing

03:42:08 - cmdstanpy - INFO - Chain [1] start processing

03:42:10 - cmdstanpy - INFO - Chain [1] done processing

03:42:10 - cmdstanpy - INFO - Chain [1] start processing

03:42:13 - cmdstanpy - INFO - Chain [1] done processing

03:42:14 - cmdstanpy - INFO - Chain [1] start processing

03:42:16 - cmdstanpy - INFO - Chain [1] done processing

03:42:16 - cmdstanpy - INFO - Chain [1] start processing

03:42:19 - cmdstanpy - INFO - Chain [1] done processing

03:42:19 - cmdstanpy - INFO - Chain [1] start processing

03:42:21 - cmdstanpy - INFO - Chain [1] done processing

03:42:21 - cmdstanpy - INFO - Chain [1] start processing

03:42:23 - cmdstanpy - INFO - Chain [1] done processing

03:42:24 - cmdstanpy - INFO - Chain [1] start processing

03:42:26 - cmdstanpy - INFO - Chain [1] done processing

03:42:26 - cmdstanpy - INFO - Chain [1] start processing

03:42:29 - cmdstanpy - INFO - Chain [1] done processing

03:42:30 - cmdstanpy - INFO - Chain [1] start processing

03:42:33 - cmdstanpy - INFO - Chain [1] done processing

03:42:33 - cmdstanpy - INFO - Chain [1] start processing

03:42:36 - cmdstanpy - INFO - Chain [1] done processing

03:42:36 - cmdstanpy - INFO - Chain [1] start processing

03:42:36 - cmdstanpy - INFO - Chain [1] done processing

03:42:37 - cmdstanpy - INFO - Chain [1] start processing

03:42:37 - cmdstanpy - INFO - Chain [1] done processing

03:42:37 - cmdstanpy - INFO - Chain [1] start processing

03:42:37 - cmdstanpy - INFO - Chain [1] done processing

03:42:38 - cmdstanpy - INFO - Chain [1] start processing

03:42:38 - cmdstanpy - INFO - Chain [1] done processing

03:42:38 - cmdstanpy - INFO - Chain [1] start processing

03:42:39 - cmdstanpy - INFO - Chain [1] done processing

03:42:39 - cmdstanpy - INFO - Chain [1] start processing

03:42:39 - cmdstanpy - INFO - Chain [1] done processing

03:42:40 - cmdstanpy - INFO - Chain [1] start processing

03:42:40 - cmdstanpy - INFO - Chain [1] done processing

03:42:40 - cmdstanpy - INFO - Chain [1] start processing

03:42:40 - cmdstanpy - INFO - Chain [1] done processing

03:42:41 - cmdstanpy - INFO - Chain [1] start processing

03:42:41 - cmdstanpy - INFO - Chain [1] done processing

03:42:41 - cmdstanpy - INFO - Chain [1] start processing

03:42:41 - cmdstanpy - INFO - Chain [1] done processing

03:42:42 - cmdstanpy - INFO - Chain [1] start processing

03:42:42 - cmdstanpy - INFO - Chain [1] done processing

03:42:43 - cmdstanpy - INFO - Chain [1] start processing

03:42:43 - cmdstanpy - INFO - Chain [1] done processing

03:42:43 - cmdstanpy - INFO - Chain [1] start processing

03:42:43 - cmdstanpy - INFO - Chain [1] done processing

03:42:44 - cmdstanpy - INFO - Chain [1] start processing

03:42:44 - cmdstanpy - INFO - Chain [1] done processing

03:42:44 - cmdstanpy - INFO - Chain [1] start processing

03:42:44 - cmdstanpy - INFO - Chain [1] done processing

03:42:45 - cmdstanpy - INFO - Chain [1] start processing

03:42:45 - cmdstanpy - INFO - Chain [1] done processing

03:42:46 - cmdstanpy - INFO - Chain [1] start processing

03:42:46 - cmdstanpy - INFO - Chain [1] done processing

03:42:46 - cmdstanpy - INFO - Chain [1] start processing

03:42:46 - cmdstanpy - INFO - Chain [1] done processing

03:42:47 - cmdstanpy - INFO - Chain [1] start processing

03:42:47 - cmdstanpy - INFO - Chain [1] done processing

03:42:47 - cmdstanpy - INFO - Chain [1] start processing

03:42:48 - cmdstanpy - INFO - Chain [1] done processing

03:42:48 - cmdstanpy - INFO - Chain [1] start processing

03:42:48 - cmdstanpy - INFO - Chain [1] done processing

03:42:49 - cmdstanpy - INFO - Chain [1] start processing

03:42:49 - cmdstanpy - INFO - Chain [1] done processing

03:42:49 - cmdstanpy - INFO - Chain [1] start processing

03:42:50 - cmdstanpy - INFO - Chain [1] done processing

03:42:50 - cmdstanpy - INFO - Chain [1] start processing

03:42:50 - cmdstanpy - INFO - Chain [1] done processing

03:42:51 - cmdstanpy - INFO - Chain [1] start processing

03:42:51 - cmdstanpy - INFO - Chain [1] done processing

03:42:51 - cmdstanpy - INFO - Chain [1] start processing

03:42:51 - cmdstanpy - INFO - Chain [1] done processing

03:42:52 - cmdstanpy - INFO - Chain [1] start processing

03:42:52 - cmdstanpy - INFO - Chain [1] done processing

03:42:52 - cmdstanpy - INFO - Chain [1] start processing

03:42:53 - cmdstanpy - INFO - Chain [1] done processing

03:42:53 - cmdstanpy - INFO - Chain [1] start processing

03:42:53 - cmdstanpy - INFO - Chain [1] done processing

03:42:54 - cmdstanpy - INFO - Chain [1] start processing

03:42:54 - cmdstanpy - INFO - Chain [1] done processing

03:42:54 - cmdstanpy - INFO - Chain [1] start processing

03:42:54 - cmdstanpy - INFO - Chain [1] done processing

03:42:55 - cmdstanpy - INFO - Chain [1] start processing

03:42:55 - cmdstanpy - INFO - Chain [1] done processing

03:42:55 - cmdstanpy - INFO - Chain [1] start processing

03:42:56 - cmdstanpy - INFO - Chain [1] done processing

03:42:56 - cmdstanpy - INFO - Chain [1] start processing

03:42:56 - cmdstanpy - INFO - Chain [1] done processing

03:42:57 - cmdstanpy - INFO - Chain [1] start processing

03:42:57 - cmdstanpy - INFO - Chain [1] done processing

03:42:57 - cmdstanpy - INFO - Chain [1] start processing

03:42:58 - cmdstanpy - INFO - Chain [1] done processing

03:42:58 - cmdstanpy - INFO - Chain [1] start processing

03:42:58 - cmdstanpy - INFO - Chain [1] done processing

03:42:59 - cmdstanpy - INFO - Chain [1] start processing

03:42:59 - cmdstanpy - INFO - Chain [1] done processing

03:42:59 - cmdstanpy - INFO - Chain [1] start processing

03:42:59 - cmdstanpy - INFO - Chain [1] done processing

03:43:00 - cmdstanpy - INFO - Chain [1] start processing

03:43:00 - cmdstanpy - INFO - Chain [1] done processing

03:43:00 - cmdstanpy - INFO - Chain [1] start processing

03:43:01 - cmdstanpy - INFO - Chain [1] done processing

03:43:01 - cmdstanpy - INFO - Chain [1] start processing

03:43:01 - cmdstanpy - INFO - Chain [1] done processing

03:43:01 - cmdstanpy - INFO - Chain [1] start processing

03:43:02 - cmdstanpy - INFO - Chain [1] done processing

03:43:02 - cmdstanpy - INFO - Chain [1] start processing

03:43:02 - cmdstanpy - INFO - Chain [1] done processing

03:43:03 - cmdstanpy - INFO - Chain [1] start processing

03:43:03 - cmdstanpy - INFO - Chain [1] done processing

03:43:03 - cmdstanpy - INFO - Chain [1] start processing

03:43:04 - cmdstanpy - INFO - Chain [1] done processing

03:43:04 - cmdstanpy - INFO - Chain [1] start processing

03:43:04 - cmdstanpy - INFO - Chain [1] done processing

03:43:05 - cmdstanpy - INFO - Chain [1] start processing

03:43:05 - cmdstanpy - INFO - Chain [1] done processing

03:43:05 - cmdstanpy - INFO - Chain [1] start processing

03:43:05 - cmdstanpy - INFO - Chain [1] done processing

03:43:06 - cmdstanpy - INFO - Chain [1] start processing

03:43:06 - cmdstanpy - INFO - Chain [1] done processing

03:43:06 - cmdstanpy - INFO - Chain [1] start processing

03:43:07 - cmdstanpy - INFO - Chain [1] done processing

03:43:07 - cmdstanpy - INFO - Chain [1] start processing

03:43:07 - cmdstanpy - INFO - Chain [1] done processing

03:43:08 - cmdstanpy - INFO - Chain [1] start processing

03:43:08 - cmdstanpy - INFO - Chain [1] done processing

03:43:08 - cmdstanpy - INFO - Chain [1] start processing

03:43:09 - cmdstanpy - INFO - Chain [1] done processing

03:43:09 - cmdstanpy - INFO - Chain [1] start processing

03:43:09 - cmdstanpy - INFO - Chain [1] done processing

03:43:10 - cmdstanpy - INFO - Chain [1] start processing

03:43:10 - cmdstanpy - INFO - Chain [1] done processing

03:43:10 - cmdstanpy - INFO - Chain [1] start processing

03:43:11 - cmdstanpy - INFO - Chain [1] done processing

03:43:11 - cmdstanpy - INFO - Chain [1] start processing

03:43:11 - cmdstanpy - INFO - Chain [1] done processing

03:43:12 - cmdstanpy - INFO - Chain [1] start processing

03:43:12 - cmdstanpy - INFO - Chain [1] done processing

03:43:12 - cmdstanpy - INFO - Chain [1] start processing

03:43:12 - cmdstanpy - INFO - Chain [1] done processing

03:43:13 - cmdstanpy - INFO - Chain [1] start processing

03:43:13 - cmdstanpy - INFO - Chain [1] done processing

03:43:13 - cmdstanpy - INFO - Chain [1] start processing

03:43:14 - cmdstanpy - INFO - Chain [1] done processing

03:43:14 - cmdstanpy - INFO - Chain [1] start processing

03:43:14 - cmdstanpy - INFO - Chain [1] done processing

03:43:15 - cmdstanpy - INFO - Chain [1] start processing

03:43:15 - cmdstanpy - INFO - Chain [1] done processing

03:43:15 - cmdstanpy - INFO - Chain [1] start processing

03:43:15 - cmdstanpy - INFO - Chain [1] done processing

03:43:16 - cmdstanpy - INFO - Chain [1] start processing

03:43:16 - cmdstanpy - INFO - Chain [1] done processing

03:43:16 - cmdstanpy - INFO - Chain [1] start processing

03:43:16 - cmdstanpy - INFO - Chain [1] done processing

03:43:17 - cmdstanpy - INFO - Chain [1] start processing

03:43:17 - cmdstanpy - INFO - Chain [1] done processing

03:43:17 - cmdstanpy - INFO - Chain [1] start processing

03:43:17 - cmdstanpy - INFO - Chain [1] done processing

03:43:18 - cmdstanpy - INFO - Chain [1] start processing

03:43:18 - cmdstanpy - INFO - Chain [1] done processing

03:43:18 - cmdstanpy - INFO - Chain [1] start processing

03:43:19 - cmdstanpy - INFO - Chain [1] done processing

03:43:19 - cmdstanpy - INFO - Chain [1] start processing

03:43:19 - cmdstanpy - INFO - Chain [1] done processing

03:43:20 - cmdstanpy - INFO - Chain [1] start processing

03:43:20 - cmdstanpy - INFO - Chain [1] done processing

03:43:20 - cmdstanpy - INFO - Chain [1] start processing

03:43:20 - cmdstanpy - INFO - Chain [1] done processing

03:43:21 - cmdstanpy - INFO - Chain [1] start processing

03:43:21 - cmdstanpy - INFO - Chain [1] done processing

03:43:22 - cmdstanpy - INFO - Chain [1] start processing

03:43:22 - cmdstanpy - INFO - Chain [1] done processing

03:43:22 - cmdstanpy - INFO - Chain [1] start processing

03:43:22 - cmdstanpy - INFO - Chain [1] done processing

03:43:23 - cmdstanpy - INFO - Chain [1] start processing

03:43:23 - cmdstanpy - INFO - Chain [1] done processing

03:43:23 - cmdstanpy - INFO - Chain [1] start processing

03:43:24 - cmdstanpy - INFO - Chain [1] done processing

03:43:24 - cmdstanpy - INFO - Chain [1] start processing

03:43:24 - cmdstanpy - INFO - Chain [1] done processing

03:43:25 - cmdstanpy - INFO - Chain [1] start processing

03:43:25 - cmdstanpy - INFO - Chain [1] done processing

03:43:25 - cmdstanpy - INFO - Chain [1] start processing

03:43:25 - cmdstanpy - INFO - Chain [1] done processing

03:43:26 - cmdstanpy - INFO - Chain [1] start processing

03:43:26 - cmdstanpy - INFO - Chain [1] done processing

03:43:27 - cmdstanpy - INFO - Chain [1] start processing

03:43:27 - cmdstanpy - INFO - Chain [1] done processing

03:43:27 - cmdstanpy - INFO - Chain [1] start processing

03:43:28 - cmdstanpy - INFO - Chain [1] done processing

03:43:28 - cmdstanpy - INFO - Chain [1] start processing

03:43:28 - cmdstanpy - INFO - Chain [1] done processing

03:43:29 - cmdstanpy - INFO - Chain [1] start processing

03:43:29 - cmdstanpy - INFO - Chain [1] done processing

03:43:29 - cmdstanpy - INFO - Chain [1] start processing

03:43:29 - cmdstanpy - INFO - Chain [1] done processing

03:43:30 - cmdstanpy - INFO - Chain [1] start processing

03:43:30 - cmdstanpy - INFO - Chain [1] done processing

03:43:31 - cmdstanpy - INFO - Chain [1] start processing

03:43:31 - cmdstanpy - INFO - Chain [1] done processing

03:43:31 - cmdstanpy - INFO - Chain [1] start processing

03:43:31 - cmdstanpy - INFO - Chain [1] done processing

03:43:32 - cmdstanpy - INFO - Chain [1] start processing

03:43:32 - cmdstanpy - INFO - Chain [1] done processing

03:43:33 - cmdstanpy - INFO - Chain [1] start processing

03:43:33 - cmdstanpy - INFO - Chain [1] done processing

03:43:33 - cmdstanpy - INFO - Chain [1] start processing

03:43:34 - cmdstanpy - INFO - Chain [1] done processing

03:43:34 - cmdstanpy - INFO - Chain [1] start processing

03:43:34 - cmdstanpy - INFO - Chain [1] done processing

03:43:35 - cmdstanpy - INFO - Chain [1] start processing

03:43:35 - cmdstanpy - INFO - Chain [1] done processing

h=12 Prophet          [cpu]  379.4 s

h=12 Ridge            [cuda]   17.5 s

h=12 Random Forest    [cuda]  696.8 s

h=12 XGBoost          [cuda]  654.7 s

h                   1      3      6      12
modelo
ARIMA            0.346  0.589  0.777  1.441
Paseo aleatorio  0.349  0.602  0.773  1.157
Ridge            0.399  0.723  0.993  1.928
VAR              0.404  0.782  1.605  8.513
XGBoost          0.475  0.838  0.917  1.716
Random Forest    0.553  0.920  0.906  1.658
Prophet          0.947  1.279  1.890  3.248

## 5.4 Mejora frente a los modelos base

In [11]:
for p in ("p1", "p2"):
    f = lambda r: r.groupby("modelo")["RMSE"].mean()
    b, a = pd.read_csv(REPORTS / f"{p}_base_metricas.csv"), pd.read_csv(REPORTS / f"{p}_ajuste_fino_metricas.csv")
    print(p); print(pd.DataFrame({"base": f(b), "ajuste_fino": f(a)}).assign(mejora_pct=lambda d: 100 * (1 - d.ajuste_fino / d.base)).round(3).sort_values("ajuste_fino"))
for p in ("p1", "p2"):
    a = pd.read_csv(REPORTS / f"{p}_ajuste_fino_metricas.csv").drop_duplicates("modelo")
    print(p); print(a[["modelo", "parametros", "segundos"]].to_string(index=False))

p1

                     base  ajuste_fino  mejora_pct
modelo
XGBoost             0.848        1.347     -58.725
Gradient Boosting   1.232        1.535     -24.562
SVR                 2.128        1.683      20.911
Random Forest       1.216        1.724     -41.778
Lasso               2.016        1.807      10.404
Ridge               1.937        1.882       2.838
k-NN                1.950        1.950       0.000
Regresión lineal    1.978        1.978       0.000
Persistencia        2.018        2.018       0.000
Árbol de decisión   1.350        2.239     -65.907
Red neuronal (MLP)  2.610        2.595       0.566
Base (media)        3.521        3.521       0.000
p2
                     base  ajuste_fino  mejora_pct
modelo
Random Forest       0.400        0.489     -22.394
XGBoost             0.441        0.489     -11.097
Gradient Boosting   0.473        0.490      -3.446
Árbol de decisión   0.360        0.499     -38.538
Red neuronal (MLP)  0.501        0.503      -0.531
k-NN                0.483        0.511      -5.704
Ridge               0.508        0.512      -0.832
SVR                 0.500        0.516      -3.235
Lasso               0.634        0.519      18.157
Persistencia        0.561        0.550       2.042
Base (media)        0.634          NaN         NaN
Regresión lineal    0.508          NaN         NaN
p1
            modelo                                                                                                                                                         parametros  segundos
      Base (media)                                                                                                                                                                 {}  1.166914
  Regresión lineal                                                                                                                                                                 {}  0.022588
             Ridge                                                                                                                                           {"modelo__alpha": "100"} 10.235200
             Lasso                                                                                                                                           {"modelo__alpha": "0.1"}  0.140779
              k-NN                                                                                                         {"modelo__n_neighbors": "5", "modelo__weights": "uniform"}  0.614511
 Árbol de decisión                                                                                                       {"modelo__max_depth": "4", "modelo__min_samples_leaf": "20"}  0.324789
     Random Forest                                                                        {"modelo__max_depth": "24", "modelo__min_samples_leaf": "5", "modelo__n_estimators": "200"} 14.419460
 Gradient Boosting                                            {"modelo__estimator__learning_rate": "0.03", "modelo__estimator__max_depth": "3", "modelo__estimator__max_iter": "300"}  4.093527
           XGBoost {"modelo__estimator__learning_rate": "0.03", "modelo__estimator__max_depth": "3", "modelo__estimator__n_estimators": "200", "modelo__estimator__subsample": "0.8"} 91.711557
               SVR                                                           {"modelo__estimator__C": "10", "modelo__estimator__epsilon": "0.1", "modelo__estimator__gamma": "scale"}  0.311884
Red neuronal (MLP)                                                          {"modelo__alpha": "0.0001", "modelo__hidden_layer_sizes": "(32,)", "modelo__learning_rate_init": "0.001"}  4.146403
      Persistencia                                                                                                                                                                 {}  0.000000
p2
            modelo                                                                                                                                         parametros    segundos
             Ridge                                                                                                                           {"modelo__alpha": "100"}    7.045597
             Lasso                                                                                                                           {"modelo__alpha": "0.1"}   60.840386
              k-NN                                                                                       {"modelo__n_neighbors": "60", "modelo__weights": "distance"}   11.292620
 Árbol de decisión                                                                                      {"modelo__max_depth": "4", "modelo__min_child_weight": "100"}    8.565481
     Random Forest                           {"modelo__colsample_bynode": "0.6", "modelo__max_depth": "8", "modelo__n_estimators": "100", "modelo__subsample": "0.6"} 3788.157740
 Gradient Boosting                                                         {"modelo__learning_rate": "0.03", "modelo__max_depth": "3", "modelo__n_estimators": "200"}  148.892513
           XGBoost {"modelo__learning_rate": "0.03", "modelo__max_depth": "3", "modelo__n_estimators": "200", "modelo__reg_lambda": "10", "modelo__subsample": "0.8"}  436.197943
               SVR                                                                     {"modelo__C": "0.1", "modelo__epsilon": "0.1", "modelo__n_components": "2000"}  337.233683
Red neuronal (MLP)                                          {"modelo__alpha": "0.01", "modelo__hidden_layer_sizes": "(64, 32)", "modelo__learning_rate_init": "0.01"}  465.297441
      Persistencia                                                                                                                                                 {}    0.000000